### ISSUE TITLE
Internal server error for single payout in sandbox

### ISSUE THREAD

**Issue by rharishan** [paypal/PayPal-Ruby-SDK#103]
Hi, 
I'm trying to do a single payout using sandbox accounts. I'm getting "Internal server error" continuously. 
Following are the couple of debug ids :+1: 
d9064142765c9 , 23fb2682789e7 , e46e471b086fe, 37e27429b0a32. 

It would be great if I can get the reason for this behaviour. 

Thank you.

**Comment by jaypatel512** [comment]
Few things to check : 

1. Can you confirm if you are seeing the same behavior in samples too ?

2. Also, do you have a PayPal balance of given amount and currency ?

3. Also, make sure you have enabled payout in your app in developer dashboard.

We will look into that debugIds and get back to you !

**Comment by jaypatel512** [comment]
Hey @rharishan ! We were able to reproduce the issue on Sandbox. I have created an internal ticket `PPPLBUS-8749` for further investigation and remedy.

**Comment by rharishan** [comment]
Hey @jaypatel512 !
Thank you for your timely response. Are there any way to skip this issue and test payouts?

**Comment by jaypatel512** [comment]
Hey @rharishan !

Unfortunately, there is no other path that I am aware of. However, this is a high priority bug, and will be resolved as soon as possible.

**Comment by jaypatel512** [comment]
Hey @rharishan ! 

I was able to see a success on Payouts now. The issue was found, and is getting resolved. However, the sandbox seems to be up and going. Let me know if you are still seeing this error. Please re-open this issue if so.

**Comment by rharishan** [comment]
Hi @jaypatel512 !

Yes. It worked. Thank you.
