### ISSUE TITLE
Create payment immediately

### ISSUE THREAD

**Issue by tbhockey** [paypal/PayPal-Ruby-SDK#104]
Is there a way to create a payment that would indicate to the buyer that they will be charged immediately? Currently I'm setting the `intent ` of the payment to `sale`, which the documentation for the API says `Payment intent. Must be set to sale for immediate payment, authorize to authorize a payment for capture later, or order to create an order.`

However, when the user is directed to PayPal to authorize the payment they are given messages suggesting that there will be a further step after returning to the source website (see screenshots). If they still need to confirm after authorizing the payment it's not actually "immediate".

So is there a way to either remove those messages in PayPal or indicate that authorizing themselves in PayPal will execute the payment? Having them authorize themselves and yet still have to confirm payment yet again after returning back is just too many steps for the user and unnecessary.

![screen shot 2015-03-13 at 11 02 17 am](https://cloud.githubusercontent.com/assets/428125/6642558/da82cfa2-c97b-11e4-9a04-13ffcbd5d059.png)

![thumbnail](https://cloud.githubusercontent.com/assets/428125/6643011/8efcf07c-c97f-11e4-9766-5c98a686d0a3.png)

**Comment by jziaja** [comment]
Hi @tbhockey , this is possible by appending `&useraction=commit` to the `approval_url` when redirecting the buyer to PayPal.  Can you try that out and see if it displays in the manner you're wanting?

([Related issue from .NET SDK](https://github.com/paypal/PayPal-NET-SDK/issues/68))

**Comment by tbhockey** [comment]
@jziaja you rock! :metal:  Thank for your help. Wish I'da found this in the docs somewhere.

**Comment by jziaja** [comment]
Glad to help!  The info on using it is available at the very bottom of the [Customizing Express Checkout](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing/) page.  I'll talk to the rest of the SDK team to see if we can add this info to the new SDK docs we're currently working on so it's much easier to find. :)
