### ISSUE TITLE
Webhooks testing

### ISSUE THREAD

**Issue by JensC** [paypal/PayPal-Ruby-SDK#105]
Hi PayPal,
I just have a suggestion for improving the testing of your webhooks. As RoR developer it would be very convenient to test the webhooks on localhost. A service like http://www.ultrahook.com/ does make this possible, but they do only http connections (unfortunatelly no https).
Would it be possible to allow the webhook url in test mode to support http?

Thanks a lot

**Comment by holodigm** [comment]
Perhaps use https://github.com/realestate-com-au/pact or https://github.com/vcr/vcr ?

**Comment by jziaja** [comment]
Hi @JensC , unfortunately, support for testing webhooks against a localhost endpoint is not currently planned.  You'll need to investigate alternate solutions like what @holodigm posted to get that support.  

I'll forward your feedback to the Webhooks team so they are aware of this request.  Thanks!

**Comment by JensC** [comment]
Thanks for the suggestions. For a quick test I would prefer a localhost endpoint. Stripe does support this and it is great because you have an immediate feedback from the api.

**Comment by jaypatel512** [comment]
One other option that I ask people to consider is to use http://requestb.in/.
Also, the request bin by default is http. However, by manually changing the URL to https, would work.

What I do is, generate a URL, add it to paypal sandbox configurations. Run one of our samples, that creates a sale, or anything that generates a webhook. And check out the data you would receive. 

Bonus: You could save the request body and header, and generate a REST call to your localhost to test faster.

**Comment by JensC** [comment]
Thanks @jaypatel512 that seems to be close to what I had in mind. I'll give that a try.

**Comment by j4rs** [comment]
I agree with @JensC that *https* only complicates development, anyway in my case I managed to test webhooks in sandbox using https://ngrok.com, pretty straightforward to use.
