### ISSUE TITLE
PayPal::SDK::Core::Exceptions::ServerError  in Production for Paypal Payouts

### ISSUE THREAD

**Issue by preechan** [paypal/PayPal-Ruby-SDK#109]
Hi,
I am trying to implement Paypal payouts and this is the error i get in production.
PayPal::SDK::Core::Exceptions::ServerError (Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = fc37950b1ad7a.):

**Comment by jziaja** [comment]
Hi @preechan , sorry for the delay in responding.  Are you still encountering this error?  Is this reproducible on sandbox? Do you have a more recent error response with debug ID?  Thanks!

**Comment by tomwhipple** [comment]
Closing this as it is quite old. 

For API errors please contact the [merchant support team](https://www.paypal.com/mts).
