### ISSUE TITLE
Failed.  Response code = 500.  Response message = Internal Server Error. (payment execute in sandbox mode)

### ISSUE THREAD

**Issue by rhugo** [paypal/PayPal-Ruby-SDK#110]
gem version:
paypal-sdk-rest (1.1.2)

Log:
<pre>07-04-2015 11:54:51.439 [INFO ] Parameters: {"paymentId"=>"PAY-4BR02067NY649320AKUR2RSY", "token"=>"EC-5TN535386W163330D", "PayerID"=>"H84KEDYWJ7ZC4", "id"=>"177"}
07-04-2015 11:54:51.587 [DEBUG] Shop::Order Load (0.1ms)  SELECT `shop_orders`.* FROM `shop_orders` WHERE `shop_orders`.`id` = 177 LIMIT 1
07-04-2015 11:54:51.614 [WARN ] undefined method `payment_id=' for #<PayPal::SDK::REST::DataTypes::Payment:0x0000000643ae58>
07-04-2015 11:54:51.881 [INFO ] Request[post]: https://api.sandbox.paypal.com/v1/oauth2/token
07-04-2015 11:54:53.270 [INFO ] Response[200]: OK, Duration: 1.388s
07-04-2015 11:54:53.282 [INFO ] PayPal-Request-Id: 0007ae01-ba2b-48fb-aa2f-1f2f7a44c8a5
07-04-2015 11:54:53.282 [INFO ] Request[post]: https://api.sandbox.paypal.com/v1/payments/payment//execute
07-04-2015 11:54:54.486 [INFO ] Response[500]: Internal Server Error, Duration: 1.204s
07-04-2015 11:54:54.487 [INFO ] Completed 500 Internal Server Error in 3048.0ms
07-04-2015 11:54:54.553 [FATAL] PayPal::SDK::Core::Exceptions::ServerError - Failed.  Response code = 500.  Response message = Internal Server Error.:
</pre>

Code:
<pre>    @payment = PayPal::SDK::REST::Payment.new({:payment_id => params[:paymentId]})
    if @payment.execute( :payer_id => params[:PayerID] )</pre>

The error occurs in the "execute " . "curl " work properly.

<pre>curl -v https://api.sandbox.paypal.com/v1/payments/payment/PAY-1ES804596X770642MKURZ4PQ/execute/ -H 'Content-Type: application/json' -H 'Authorization: Bearer A0155-jvI2RBewH1T-xCHGMM8mUcXFWJ4uWLVqwfISSGuCU' -d '{ "payer_id" : "H84KEDYWJ7ZC4" }'
</pre>

<pre>{"id":"PAY-1ES804596X770642MKURZ4PQ","create_time":"2015-04-07T09:07:10Z","update_time":"2015-04-07T09:43:47Z","state":"approved","intent":"sale","payer":{"payment_method":"paypal","payer_info":{"email":"info-buyer@xxxxxxxx.com","first_name":"test","last_name":"buyer","payer_id":"H84KEDYWJ7ZC4","shipping_address":{"line1":"calle VilamarÃ­ 76993- 17469","city":"Albacete","state":"Albacete","postal_code":"02001","country_code":"ES","recipient_name":"test buyer"}}},"transactions":[{"amount":{"total":"246.24","currency":"EUR","details":{"subtotal":"246.24"}},"description":"Pedido XXXXXXXXX : 1066","related_resources":[{"sale":{"id":"7G490405EH012760A","create_time":"2015-04-07T09:07:10Z","update_time":"2015-04-07T09:43:47Z","amount":{"total":"246.24","currency":"EUR"},"payment_mode":"INSTANT_TRANSFER","state":"pending","reason_code":"PAYMENT_REVIEW","protection_eligibility":"INELIGIBLE","parent_payment":"PAY-1ES804596X770642MKURZ4PQ","transaction_fee":{"value":"8.72","currency":"EUR"},"links":[{"href":"https:/* Connection #0 to host api.sandbox.paypal.com left intact
/api.sandbox.paypal.com/v1/payments/sale/7G490405EH012760A","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/sale/7G490405EH012760A/refund","rel":"refund","method":"POST"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-1ES804596X770642MKURZ4PQ","rel":"parent_payment","method":"GET"}]}}]}],"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-1ES804596X770642MKURZ4PQ","rel":"self","method":"GET"}]}</pre>

Could someone please help?

**Comment by jziaja** [comment]
Hi @rhugo , in your code, change `:payment_id` to just [`:id`](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L41) when you create the `@payment` object.

````ruby
@payment = PayPal::SDK::REST::Payment.new({:id => params[:paymentId]})
if @payment.execute( :payer_id => params[:PayerID] )
````

Give that a try and let me know if you still encounter the error.  Regardless, this looks like an API bug for improper error mapping.  The API should not be returning a 500 - it should return a 400 with a meaningful error message (e.g. "Payment ID missing" or something).

**Comment by rhugo** [comment]
Solved! Thanks!!!
