### ISSUE TITLE
Uninitialized Constant VERSION

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#112]
Works:

    PayPal::SDK::OpenIDConnect::Tokeninfo.authorize_url()

Fails:

    PayPal::SDK::OpenIDConnect::Tokeninfo.create("...")

	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.2/lib/paypal-sdk/core/openid_connect/api.rb:42:in `user_agent'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.2/lib/paypal-sdk/core/api/base.rb:69:in `default_http_header'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.2/lib/paypal-sdk/core/api/base.rb:79:in `api_call'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.2/lib/paypal-sdk/core/api/base.rb:96:in `post'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.2/lib/paypal-sdk/core/openid_connect.rb:63:in `create_from_authorization_code'
	from (irb):7
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/kevin/Development/Surkus/web/bin/rails:8:in `<top (required)>'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kevin/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

The above snippet is from the main README.

**Comment by jziaja** [comment]
Hi @ksylvest , I see you're using version 1.1.2 of the SDK.  Have you tried updating to the most recent version, 1.1.3?  There was [an issue that was fixed](https://github.com/paypal/PayPal-Ruby-SDK/commit/e284f0dd2ff727c05582ec1f56ccc1d1b4eebac6) related to generating the user-agent string.

**Comment by ksylvest** [comment]
@jziaja Thanks that fixed it.
