### ISSUE TITLE
changelog version number behind gem?

### ISSUE THREAD

**Issue by jackphelps** [paypal/PayPal-Ruby-SDK#113]
https://github.com/paypal/PayPal-Ruby-SDK/blob/master/CHANGELOG.txt
https://rubygems.org/gems/paypal-sdk-rest/versions/1.1.3

Might want to bump that and update changelog. I'd make you a pull request but don't know what should be listed.

Thanks as always for the gem :)

**Comment by juwlee** [comment]
Thanks @jackphelps for the catch. Fixed in 06aafd4524096efc0af25b918d9fca1d1cca09ec . It will be pushed out in the next release.
