### ISSUE TITLE
Where I get my client_id and client_secret?

### ISSUE THREAD

**Issue by Igorpollo** [paypal/PayPal-Ruby-SDK#114]
Sorry,
I can't find.

**Comment by jziaja** [comment]
* Login to your [dashboard on PayPal Developer](https://developer.paypal.com/developer/applications)
* In the list of REST apps, click on the one you're wanting to use
* By default, your sandbox credentials will be shown.  If you want to switch to your live credentials, just click the 'Live' button in the top right corner of the page.
