### ISSUE TITLE
Bug on credit card number validation

### ISSUE THREAD

**Issue by defmsy** [paypal/PayPal-Ruby-SDK#115]
I'm currently trying to implement credit card payment in sandbox mode.

I have made some tests but I always get the same result.
```
number: "4417119669820331"
```
```
number: params[:cb][:card_number]
```
```
number: 
params[:cb][:card_number].to_i
```

```
{"name"=>"VALIDATION_ERROR", "details"=>[{"field"=>"payer.funding_instruments[0].credit_card.number", "issue"=>"Must be numeric"}], "message"=>"Invalid request - see details", "information_link"=>"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR", "debug_id"=>"b3021fc00c09d"}
```

**Comment by juwlee** [comment]
@defmsy [credit card number should be string](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L145). Please refer to [sample code](https://github.com/paypal/PayPal-Ruby-SDK/tree/master/spec) to see how it works.
