### ISSUE TITLE
WebHooks for agreements

### ISSUE THREAD

**Issue by rami85** [paypal/PayPal-Ruby-SDK#116]
Hi Paypal,

I would like to know if webhooks for recurring payments is supported actually.

I have read in the documentation how to create a webhook (https://developer.paypal.com/webapps/developer/docs/api/#create-a-webhook). It seems easy but I don't know if they are supported. In rubydoc (http://www.rubydoc.info/github/paypal/PayPal-Ruby-SDK/PayPal/SDK/REST/DataTypes/Notification) I don't see any method for create webhooks.

```ruby
PayPal::SDK::REST::Notification.new({
  :url => "http://example.com/charges/register_payment",
  :event_types => [
    { :name => "PAYMENT.AUTHORIZATION.CREATED" },
    { :name => "PAYMENT.AUTHORIZATION.VOIDED" }]
})
```

```code
undefined method `url=' for #<PayPal::..........>
undefined method `event_types=' for #<PayPal::..........>
```

Any ideas? If webhooks is not supported... are there any solution for get this notifications?

**Comment by jziaja** [comment]
Hi @rami85 , the Subscriptions API team is still working on getting webhooks support added. We're tracking this enhancement over on the [Python SDK](https://github.com/paypal/PayPal-Python-SDK/issues/69).  For the time being, the service uses IPN.

Regarding your question about creating a webhook, it looks like this SDK hasn't been updated to support Webhooks just yet.  We'll make sure to get the support added in the upcoming release.  The current [`Notification`](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L1304) class is actually for [sending invoice reminder notifications](https://developer.paypal.com/docs/api/#send-an-invoice-reminder).  I'll bring this up with the rest of the SDK team to see if we can change this class name to 'InvoiceNotification' to avoid confusion.

I'll leave this issue open as an SDK enhancement for supporting webhooks.

**Comment by jziaja** [comment]
Webhooks support was added to this SDK in [this commit](https://github.com/paypal/PayPal-Ruby-SDK/commit/5280d27b789f90269b60bed2101440c4fccfdf4e).  

Concerning webhook support for subscriptions, we'll continue tracking that feature in the Python SDK's [Issue #69](https://github.com/paypal/PayPal-Python-SDK/issues/69).  We're in the process of requesting a status update on that feature from the API team, so we should have an update to share soon.
