### ISSUE TITLE
Getting BadRequest Exception on Tokeninfo.create

### ISSUE THREAD

**Issue by uishaq** [paypal/PayPal-Ruby-SDK#118]
I receive an OAuth2 token from client similar to this:  

**oauth2_code = "4HPw6I0gKxZCTVUVI2bUcLf6mOUn9Upc9eJWu5l1vJXLp3jRjNyzYyIypztY4Ez3uAoK-h0hK3IerprOqKQVEVBKN5nuN4RrkFwi9G_DvWITR-wW4ywbpY7htK2U2FLnmlE0caDWWiRcFp27pgtu933xsABcE7ZIahdkg1hLbDttP7XigpLGdgws5Ka4JdI5WJy-9E9t17gbgh8b"**

When I use it to get a refresh token:

**token_info = Tokeninfo.create_from_authorization_code(oauth2_code)**

This is what I get on rails console.

**PayPal::SDK::Core::Exceptions::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.**

This was working previously. Do I need to update my gem?

**Comment by uishaq** [comment]
Seems I'm already using the latest version (1.1.2) of gem. Any idea what may have got wrong? I'm using Rails 4.2.0 and trying to use Future Payments.

**Comment by jziaja** [comment]
Hi @uishaq , sorry for not responding sooner.  Is there a body included with the 400 response that you can share?  Also, the latest version is [1.1.3](https://rubygems.org/gems/paypal-sdk-rest/versions/1.1.3).

**Comment by uishaq** [comment]
Below is a snapshot of my rails console and the error I get as a result. You can see there's not much information in the exception except for the one I've posted before:

- Rails console
![5](https://cloud.githubusercontent.com/assets/6950378/7520214/7df5d10e-f4fe-11e4-8463-4080450ac792.png)



After that, I tried the following (using   https://developer.paypal.com/docs/api/#grant-token-from-authorization-code   as reference):

1) I used my web browser to access the following URL, passing my PayPal Client ID and return URL:

https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?client_id=AblpaM2E--ufq4at_TOncIaj63s0p-i58ulvVbQ6PJBFKI6Xw77-5_IGY7bxIxoRtPXbkx2BBuuASuq5&response_type=code&scope=openid&redirect_uri=http%3A%2F%2F10.164.14.62%3A3000%2F

2) After logging into my PayPal account and it returned a code in the URL:

lHwyFCt9AbaxqcKLIsrhCyOFoiQatc-VMtGz3eivQ48h07WLuPQrTk9BYuQ9JcesFYWoC91xI7BZoAsZ4AR3ZrtHfBhcrlRFzJSoaxMbGa8SwkNo-HwTnD34rPiXNAdr7eSkyjJXjj2soHSHGsfC8IQdbDCEuES3sjD51_ZIOCLxQTDeRG0cq6wx2_DkgSNtC1KapUMey53LyxxR

3) So I used this code in a cURL command like shown in the image below and it gives me "Unsupported grant type". (last line of the screen shot)

![1](https://cloud.githubusercontent.com/assets/6950378/7516693/5ad5b09a-f4ea-11e4-95f6-169ba5fbf925.png)

**Comment by jaypatel512** [comment]
Hey @uishaq ! Can you please do me one favor. Can you please try making the same curl call, but remove the redirect_uri parameter in the body. I think it feels like the issue is with improper encoding to the URL data. 

Let me know if that works.

**Comment by uishaq** [comment]
Tried without redirect_uri, still the same result:

![6](https://cloud.githubusercontent.com/assets/6950378/7538487/b4ea57f0-f5b9-11e4-855c-6deee7732eff.png)

**Comment by jaypatel512** [comment]
I just realized, you are using two different clientIds for both operations. In your earlier message, you mentioned the URL that has clientId as : `AblpaM2E-...` but in your curl request, it starts with `AacIrRAVdkZ....`

Please use the same clientId for both operations and you should be fine. Please re-open the issue if you still see this error.

**Comment by uishaq** [comment]
It's just that I was using a different account for experimenting. Here I'm posting both the URL and cURL request which use the same Client ID. Just to be clear, cURL call uses Client ID and Secret from the same sandbox account as used by the URL:

https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?client_id=AacIrRAVdkZ4dVkt0udJqk7kZvcg_DQ-VJW--UUwoxAg7PaCFbzCqLRzTQii&response_type=code&scope=openid&redirect_uri=http%3A%2F%2F10.164.14.62%3A3000%2F

![8](https://cloud.githubusercontent.com/assets/6950378/7541061/c16173e4-f5cb-11e4-87c5-4347cf8eed95.png)

Even, if the cURL call succeeds, the point I'm trying to make is that the Ruby SDK is giving error as well. I used cURL calls just to see if the issue is with PayPal REST SDK or the Ruby SDK wrapper.

**Comment by juwlee** [comment]
@uishaq can you try another request without whitespace or new line between ```grant_type=authorization_code``` and ```&code=``` ? Looks like it might be what the API is complaining about.

**Comment by uishaq** [comment]
@juwlee yes, cURL worked when I trimmed whitespace/new line  between parameters. But that's not the reason why I raised this issue. My original problem stands as it is. I can't use the same OAuth2 code in my rails console using:

**token_info = Tokeninfo.create_from_authorization_code(oauth2_code)**

It gives me **400 Bad Request** error like I've posted earlier. Is there a change in the Ruby API?

**Comment by uishaq** [comment]
Can we this issue reopened please? I have the cURL call working but that hasn't solved my original Rails issue so far.

**Comment by juwlee** [comment]
@uishaq thanks for confirming. I understand why you opened this issue, but wanted to make sure curl works first because SDK will not work for sure if curl does not. Trying curl will tell whether it is an SDK issue or API issue.

With that said, I am re-opening this issue to investigate the initially mentioned 400 error.

**Comment by uishaq** [comment]
@juwlee, Thanks for reopening the issue, but I see the activity on this thread has declined since then. Anything you've investigated so far?

**Comment by uishaq** [comment]
Do I need to open a separate issue?

**Comment by juwlee** [comment]
@uishaq I cannot seem to reproduce the issue as I get token info successfully. Just to confirm, 

- does the SDK token info call fail with the same authorization code with which a cURL call succeeds?
- when did it stop working? Did you upgrade SDK then?
- A new version was just released. It may not resolve your issue, but it should print out a Debug ID along with error message "Bad Request". Could you grab and share it here?
- can you pull the "last known good" version while this is being looked into?

**Comment by uishaq** [comment]
@juwlee 
* Yes, the DSK token info call fails with the same authorization code with which a cURL call succeeds.
* It was working perfectly until early April, then broke all of a sudden. I haven't upgraded SDK (gem) from 1.1.2
* I'll have it updated and share the Debug ID here.
* Unfortunately there was no "last known good version" for my case. Like I said, it used to work fine, nothing changed and it started breaking all of a sudden.

One more thing, I have a feeling that there is some issue with *Tokeninfo* class (or some code that's related to it) Because as I test it further, I see that any method that uses *Tokeninfo* class fails the same way. For example, another piece of code that's failing for me is  **Tokeninfo.refresh(refresh_token)**   So I think the problem's not limited to just  **create_from_authorization_code**  method
