### ISSUE TITLE
For a Failed PayPal::SDK::REST::Payout Lookup by sender_item_id or sender_batch_id Fails

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#120]
I had a few failed payouts and now trying to re-process them returns `duplicate batch request`. I'm trying to lookup the requests to see if they went through or not, but I'm getting a 404:

```
#<PayPal::SDK::REST::DataTypes::PayoutBatch:0x007fcc71320010 @error={"name"=>"USER_BUSINESS_ERROR", "message"=>"User business error.", "debug_id"=>"4854e55f0e1b3", "information_link"=>"https://developer.paypal.com/webapps/developer/docs/api/#USER_BUSINESS_ERROR", "details"=>[{"field"=>"SENDER_BATCH_ID", "issue"=>"Duplicate batch request"}]}>
```

```ruby
PayPal::SDK::REST::Payout.get("4854e55f0e1b3")
```

```
PayPal::SDK::Core::Exceptions::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.  Response debug ID = 6de4e7d16899d
```

How can you lookup a payout by `sender_item_id` or `sender_batch_id` to see if it went through?

**Comment by jziaja** [comment]
@ksylvest , you should be able to look up a Payout Item by calling [`PayPal::SDK::REST::PayoutItem.get("...")`](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L1051) with the `payout_item_id`.  This will return the `transaction_status`, as well as the `payout_batch_id` you can then use to make the `PayPal::SDK::REST::Payout.get("...")` call to get more details about the status of the batch.

As far as I'm aware, you can't lookup or search for a Payout using the `sender_item_id` at this time.

The PayPal Developer site has a bit more information on these two calls:
* [Get the status of a payout item](https://developer.paypal.com/docs/api/#get-the-status-of-a-payout-item)
* [Get the status of a batch payout](https://developer.paypal.com/docs/api/#get-the-status-of-a-batch-payout)

**Comment by ksylvest** [comment]
How can you get the `payout_item_id`? Is it the `debug_id` returned on a subsequent call?

**Comment by jziaja** [comment]
Ah, I didn't realize you were trying to lookup a Payout using the returned `debug_id`.  The `debug_id` is a PayPal-internal ID used for tracking specific requests.  Instead of using the `debug_id`, you should lookup the Payout Batch status using the `payout_batch_id` for the batch.  The returned Payout will include its list of items and their transaction statuses.

**Comment by ksylvest** [comment]
How can I get a `payout_batch_id` from my `sender_item_id ` or `batch_item_id`?

**Comment by jziaja** [comment]
By "`batch_item_id`", are you referring to a `payout_item_id` or a different ID?

**Comment by ksylvest** [comment]
Sorry, meant: `sender_batch_id`.

**Comment by jziaja** [comment]
Gotcha, and unfortunately, no.  You'll need a `payout_batch_id` in order to lookup details about a Payout.  Do you have access to the `payout_batch_id` or any of the associated `payout_item_id`s?

The error you're getting indicates that a Payout has already been processed that's associated with the `sender_batch_id` you specified.  Unfortunately, there's no way to lookup the details of that payout from that API response...  I'm checking to see if it's possible to get information about the payout if you don't have the `payout_batch_id`, but you may need to contact [PayPal Merchant Technical Support](https://ppmts.custhelp.com/) directly.

**Comment by ksylvest** [comment]
@jziaja Nope, these requests most likely failed without a response being returned.

**Comment by jziaja** [comment]
Do you have the original failure response?  Or are all the failures (including the first failure) responding with `USER_BUSINESS_ERROR` and `{"field"=>"SENDER_BATCH_ID", "issue"=>"Duplicate batch request"}`?

**Comment by ksylvest** [comment]
@jziaja I don't have the original failure (which probably would happen if it timed out). Then each subsequent response is a `USER_BUSINESS_ERROR`. It seems a bit strange that this error is raised if the request isn't processed.

**Comment by jziaja** [comment]
Are you seeing payments being made from your account dashboard related to the payout?  I'm going to reclassify this as an API enhancement (though could be convinced it's a bug) in that the API doesn't provide any way to retrieve the details of a payout that timed out.

Out of curiosity, when you call `Payout.create()`, are you defining `sync_mode`?  The default should be `false` if not specified, meaning the payout will occur asynchronously and return the `payout_batch_id` immediately.  If you set `sync_mode` to `true`, the payout will occur synchronously and block until the payout has completed.  For a large payout, this may take a while, which could trigger the HTTP timeout built into the SDK.

**Comment by ksylvest** [comment]
I'm sending in the `sync_mode` as true, but we only ever use the payout API for paying a single user at a time.

**Comment by jziaja** [comment]
I've forwarded this question to the Payouts API team to see if they know the best way to find the `payout_batch_id` for payouts that have timed out and will followup here once I have a response from them.

Something else you can try is setting `http_timeout` in your application's config to something higher than 30 seconds (maybe a minute or two?) and see if that helps to reduce the chance of encountering this issue.

**Comment by ksylvest** [comment]
@jziaja Do you have any followup? This has been open for four months now.

**Comment by jziaja** [comment]
@ksylvest Apologies for not following up sooner here.  The team did get back to me saying the transaction should show up in your PayPal account if the payout went through.  I tried to get more clarification from them regarding whether or not the transaction details could be traced back to a `payout_batch_id` but never heard back.  

At this point, I'd recommend contacting [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) directly with this question (and share this thread with them).  They'll be able to more directly support you and help track down the status of any payout batches that are in an unknown state to you.

**Comment by juwlee** [comment]
Closing per the above comment.

**Comment by ksylvest** [comment]
@juwlee @jziaja Why did you close this? No one fixed this... If you aren't hearing back from these people it doesn't mean you should close out these issues. MTS is not a solution (they don't return my support requests either).

**Comment by tomwhipple** [comment]
@ksylvest We're trying to get to a point where the issues in the SDK GitHub repos reflect defects/questions about the code that lives in the associated repository only. This question seems to involve more depth in the underlying API, so the support team really are the right people to help.

That said, I understand your concerns about timeliness of responses. We're working to come up with a better process that will bring transparency, but clearly we're not there yet.

Separately, will you please email the MTS ticket ID(s) or email(s) to me at `twhipple@paypal.com` so I can understand what you mean by "they don't get back to me"?

**Comment by pngnviko** [comment]
Hi! I have the same problem. 

I create payouts with sync_mode=True, so I don't get payout_batch_id or payout_item_id in responce. All I have is sender_item_id and sender_batch_id. In some cases payouts have a status pending or another. How can I cancel those payouts?

**Comment by pngnviko** [comment]
hi @ksylvest 
have you overcome this problem? if yes, say me how, please.
