### ISSUE TITLE
Issue with configuring and using different accounts in the same ruby process

### ISSUE THREAD

**Issue by flori** [paypal/PayPal-Ruby-SDK#122]
I have found a problem when changing configurations by calling `PayPal::SDK.configure` with a hash. I have two different accounts configured in two hashes `config1` and `config2`. If I first configure with `config1` and _then_ query a payment with `id1` from the REST Api (successfully) and after that change the configuration to `config2` and query a payment with `id2` I receive a 404 http result code. However the payment for `id2` was created successfully under account `config2` some time before and I stored it's `paymentId` value `id2`.

```
PayPal::SDK.configure config1
PayPal::SDK::REST::Payment.find(id1) # ok
PayPal::SDK.configure config2
PayPal::SDK::REST::Payment.find(id2) # not found
```

I debugged this problem further and found out that while the configuration is actually changed correctly the instance variable `@token_hash` in the `PayPal::SDK::Core::API::REST` is never nulled, so every query will still go to the account with configuration `config1`. The method `Paypal::SDK::Core::API::REST#set_config` (https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/api/rest.rb#L31) isn't called when changing the configuration and the rescue clause for `UnauthorizedAccess` in `Paypal::SDK::Core::API::REST#api_call` (https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/api/rest.rb#L92) isn't executed because `ResourceNotFound` is raised in: https://github.com/paypal/PayPal-Ruby-SDK/blob/ed3e58b0c6ad629b4edbadbe7ae0799df1f8f481/lib/paypal-sdk/core/util/http_helper.rb#L138

I have now found this rather ugly workaround:

```
  PayPal::SDK.configure config # Avoid crashing b/c we don't have a config file
  PayPal::SDK::REST.api.set_config config # reset @token_hash and configure everything
```

I hope you can implement a way to make `PayPal::SDK.configure` work as expected. Maybe by calling a bunch of callbacks on all components that are affected by changing the configuration and flush their caches?

**Comment by jackphelps** [comment]
I'm also running into issues doing this, haven't dug into @flori 's solution yet, will do now.

**Comment by boxmo** [comment]
:+1:

**Comment by KentoMoriwaki** [comment]
:+1:

**Comment by danijel** [comment]
👍

**Comment by eiwi1101** [comment]
:+1:
Also running into this developing a multi-tenant application which requires runtime switching of which PayPal account is being used for payments.

The ability to configure a particular instance of the API and place calls against that instance would be most secure, but swapping out global config could be wrapped in a secure manner.

**Comment by jackphelps** [comment]
I thought I might have posted this elsewhere previously, but it works perfectly fine. here's our ruby wrapper for paypal calls:
```
class PaypalPaymentWrapper
  attr_reader :custom_api_key, :custom_client_id
  def initialize(custom_client_id, custom_api_key)
    @custom_client_id = custom_client_id
    @custom_api_key = custom_api_key
  end

  def self.call(*args)
    new(*args).wrap { yield }
  end

  protected

  def wrap
    set_config(custom_config) if custom?
    return yield
  ensure
    reset_config if custom?
  end

  # bug in paypal sdk doesn't reset auth token correctly unless we force it
  # https://github.com/paypal/PayPal-Ruby-SDK/issues/122
  def set_config(config)
    PayPal::SDK.configure(config)
    PayPal::SDK::REST.api.set_config(config)
  end

  def reset_config
    set_config(Rails.application.config_for(:paypal))
  end

  def custom?
    # your logic here
  end

  def custom_config
    Rails.application.config_for(:paypal).merge(
      client_id: custom_client_id,
      client_secret: custom_api_key
    )
  end
end
```

**Comment by eiwi1101** [comment]
@jackphelps That's a good solution for this. Have you checked that for thread safety?

**Comment by jackphelps** [comment]
Aggressively, and it's been in production for ~8 months.

**Comment by yob** [comment]
We've also run into this issue on a multi-tenant app.

> The ability to configure a particular instance of the API and place calls against that instance would be most secure

This would be our strong preference - configuring a short-lived API object with the required credentials feels safer than setting global configuration.

**Comment by jackphelps** [comment]
@yob while I 100% agree with you in principle, I'll note that we've had (a version of) the wrapper above in production since late 2015, and in the last month we've processed something like ~16K paypal payments over close to 1K different API keys. No issues -- it's safe, again with the disclaimers I added before.

**Comment by sharang-d** [comment]
Is there still no official implementation for this?

**Comment by sarge** [comment]
@jackphelps could it be that you are running under a multi-process app server like unicorn?

**Comment by jackphelps** [comment]
How is that relevant? Each process has its own config, the wrapper is safe regardless.

**Comment by sarge** [comment]
I wanted to be sure I understood the environment the solution was designed for. This issue thread discusses both processes and threads.

As I understand it your solution looks valid for a process forking solution like Unicorn where each process is only dealing with a single web request at a time. In this case re-configuring before each call will should be ok.

Puma / Passenger or Sidekiq use a threaded model where memory will be shared and the class variables and there will be a problem as the _write_ to the central config could be interleaved with _reads_ from the central config.

The use of the @@configuration variable store looks dangerous in a multi-threaded environment.
https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/config.rb#L161

**Comment by jackphelps** [comment]
the config is an instance and doesn't rely on the class vars, so the setters for the client id / secret should be perfectly thread safe. 

I mean, as per above I can't guarantee anything for your environment (and please do check for yourself and understand the code), but it ought to work on both puma and unicorn with MRI (and we've used it on both as well as sidekiq in production.

**Comment by sarge** [comment]
Thanks for the explanation @jackphelps I will dig in a little deeper.

**Comment by jackphelps** [comment]
You're reading the part of the code where the class stores the default config. If you don't want to follow the code, try setting the config and you'll get back an instance of `PayPal::SDK::Core::Config < Object`. That's the config object the gem actually uses when making calls.

**Comment by deashay** [comment]
Ok, so I did something similar, but maybe I'm missing something(not sure how to use your code exactly, so sorry if I did it wrong):
```ruby
def test
  t1 = Thread.new do 
    PaypalPaymentWrapper.call('first_id', 'first_api_key') do
      10.times { puts "t1 id: #{PayPal::SDK::REST.api.config.client_id} secret: #{PayPal::SDK::REST.api.config.client_secret}" }
    end
  end
  t2 = Thread.new do 
    PaypalPaymentWrapper.call('second_id', 'second_api_key') do
      10.times { puts "t2 id: #{PayPal::SDK::REST.api.config.client_id} secret: #{PayPal::SDK::REST.api.config.client_secret}" }
    end
  end
  t1.join
  t2.join
end
```
and the result:
```
2.4.1 :031 > test
====t2 id: second_id secret: second_api_key
====t2 id: second_id secret: second_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
====t2 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
t1 id: first_id secret: first_api_key
```
Of course I'm using wrapper just once and do multiple operations inside, normally I'd just probably wrap one call, but if second thread is able to change my config in different thread the possibility of this happening grows as I add more threads, for Puma it's 16 threads by default.

Am I missing something?

**Comment by sucithrashanu** [comment]
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
