### ISSUE TITLE
Paypal error: PayPal::SDK::Core::Exceptions::ServerError

### ISSUE THREAD

**Issue by mohit167** [paypal/PayPal-Ruby-SDK#123]
Failed. Response code = 500. Response message = Internal Server Error. Response debug ID = dddf5378947d2.

**Comment by mohit167** [comment]
please tell me the cause of this error....

**Comment by jziaja** [comment]
Hi @mohit167, was this from a call on sandbox or live?  What SDK call were you making?  Can you share some code that can reproduce the issue?

**Comment by mohit167** [comment]
Hi jziaja, thanks for the reply, this was form sandbox account. I am using Sdk for Ruby on Rails, but now i have resolved this problem causing the invalid credit card number
