### ISSUE TITLE
Any plans for support of the recurring payment apis?

### ISSUE THREAD

**Issue by dscataglini** [paypal/PayPal-Ruby-SDK#124]
Are there any plans for support of the recurring payment apis?
I implemented the support for recurring payments apis in active merchants. 
Unfortunately active merchant is going to remove all of recurring apis from the gem.
Is in the plan for paypal-ruby-sdk to support recurring payments?

I'm currently using the now legacy web payments pro api to make CreateRecurringPaymentsProfile and similar calls. I can't quite figure out how would you do that with this new rest api.

**Comment by juwlee** [comment]
@dscataglini please see [future payments](https://github.com/paypal/PayPal-Ruby-SDK#create-future-payment). Developer docs also have some info on it: https://developer.paypal.com/webapps/developer/docs/integration/mobile/make-future-payment/
