### ISSUE TITLE
OpenID Connect Returning 'invalid_scope' Error

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#125]
I'm trying to do a login to PayPal integration. I'm creating my redirect URI using:

```ruby
scope = "openid profile"
url = PayPal::SDK::OpenIDConnect::Tokeninfo.authorize_url(redirect_uri: pay_pal_authenticate_url, scope: scope)
```

However, this returns to my redirect URI with:

```ruby
{"error_uri"=>".../paypal/authenticate", "error_description"=>"Client Validation Error: Invalid scope.", "error"=>"invalid_scope", "controller"=>"pay_pal/authenticates", "action"=>"create"}
```

If I remove `profile` from the scope everything works (but I need that scope). I added in all the permissions for my sandbox account:

![screen shot 2015-05-13 at 11 54 08 am](https://cloud.githubusercontent.com/assets/73432/7618547/96c0bdb2-f967-11e4-9c78-63b2d235644f.png)

Anything else I'm missing?

**Comment by tomwhipple** [comment]
The [merchant technical support team](https://www.paypal.com/mts) is in a much better position to answer account specific questions.
