### ISSUE TITLE
Payout returns 500 in production

### ISSUE THREAD

**Issue by dballona** [paypal/PayPal-Ruby-SDK#126]
Hello everyone,

I keep getting this response in production mode. Things seem to work in development/test environments.
`Failed. Response code = 500. Response message = Internal Server Error. Response debug ID = 7769369de4270.`

Currently trying to achieve this by doing:

```ruby
Payout.new(
        {
          :sender_batch_header => {
            :email_subject => "You have a new payment."
           },
           items: [
              {
                :recipient_type => "email",
                :amount => {
                  :value => self.amount,
                  :currency => "USD"
                },
                :receiver => self.user.paypal_email,
                :note => "Payment for working ...",
              }
           ]
        }
      )
```

Thanks for your time.

**Comment by dballona** [comment]
Recent debug id: `c0e948f75080e`

**Comment by dballona** [comment]
New debug ID `431b1610089bc` using exactly the [samples provided in here](https://github.com/paypal/PayPal-Ruby-SDK/blob/05cd192a89ab38b3c06f66e9d127cfd3846f3366/samples/payouts/create.rb)

```ruby
 Payout.new(
        {
          :sender_batch_header => {
            :sender_batch_id => SecureRandom.hex(8),
            :email_subject => 'You have a Payout!',
          },
          :items => [
            {
              :recipient_type => 'EMAIL',
              :amount => {
                :value => '1.0',
                :currency => 'USD'
              },
              :note => 'Thanks for your work!',
              :receiver => 'root@dballona.com',
              :sender_item_id => "2014031400023",
            }
          ]
        }
      )
```

**Comment by juwlee** [comment]
@dballona is payouts enabled for the account?

**Comment by dballona** [comment]
@juwlee, yes! for the one which provides the client_id and client_secret...
Not sure about `root@dballona.com`. Taking a look now.

**Comment by dballona** [comment]
Nevermind, @juwlee... Payouts wasn't enabled for the account.
Can I add Payouts to the project's README?
