### ISSUE TITLE
Not able to fetch payment or user data  using PayPal-Ruby-SDK

### ISSUE THREAD

**Issue by sandeepsharma-tudip** [paypal/PayPal-Ruby-SDK#129]
When i use my Paypal app client id and secret key (Sandbox account) do not get any data using any API calls
Following result i got with different API calls:

We are able to get token and refresh token from authorize code but after that we are not getting any data using following API calls.

#  Not Getting Userinfo by using access token, even i have used schema as openid
userinfo = Userinfo.get("Replace with access_token")

only user_id will be returned in reponse
{
  "user_id": "https://www.paypal.com/webapps/auth/server/XXXXXXXXX"
}

# Not Getting List of Payments
payment_history = Payment.all( :count => 10 )
payment_history.payments

here does not return any data and found count = 0;

Help me if there is anything missing. I referred given steps on below link.
https://github.com/paypal/PayPal-Ruby-SDK

**Comment by juwlee** [comment]
@sandeepsharma-tudip can you give [curl](https://developer.paypal.com/webapps/developer/docs/api/) a try and see what the API returns?

**Comment by sandeepsharma-tudip** [comment]
we tried with curl call too but same response we get from both ways.
Not able to find out the way how access token is going to use to fetch paypal payment records

**Comment by juwlee** [comment]
CURL returning the same response indicates that SDK is working as designed. I wonder if all user info fields are set correctly and if you can see payment transaction history from UI. Please contact [PayPal MTS](http://www.paypal.com/mts) to verify.
