### ISSUE TITLE
undefined method `include' when trying to do a payment

### ISSUE THREAD

**Issue by indie-rok** [paypal/PayPal-Ruby-SDK#130]
I am trying to use the gem.

First  I install the gem:

    gem 'paypal-sdk-rest', :git => 'https://github.com/paypal/PayPal-Ruby-SDK.git'

Then I run

    bundle

Also I tried 

'bundle install'  and 'bundle update'

Then I include my gem into the controller and include the REST Lib to make it Work

    def doPayment
	    require 'paypal-sdk-rest'
	    include PayPal::SDK::REST
    end

But when i run doPayment I receive the following error (Note that i am not doing any payment yet, just initializing the libraries)

    undefined method `include' for #<UsuarioController:0x007f2b210da040>

What am I doing wrong?

Thanks

**Comment by juwlee** [comment]
Hi @indie-rok [Main readme docs](https://github.com/paypal/PayPal-Ruby-SDK#paypal-rest-api-ruby-sdk-) include setup guide. Also, stackoverflow might be more suitable for general questions related to language syntax.

With that said, I think this may help explain the error: http://ithaca.arpinum.org/2010/07/29/ruby-dynamic-includes.html
