### ISSUE TITLE
API Returning Transaction Was Declined "RISK_DECLINE"

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#131]
For some batch payout APIs:

name="RISK_DECLINE"
message="Transaction was declined", information_link="https://developer.paypal.com/webapps/developer/docs/api/#RISK_DECLINE

The link doesn't have any information and I don't know how to fix this error.

**Comment by juwlee** [comment]
@ksylvest it would be better handled by [PayPal MTS](https://manager.paypal.com/jsp/common/contactUs.jsp). Please contact them.
