### ISSUE TITLE
Service Unavailable live

### ISSUE THREAD

**Issue by anthonyshull** [paypal/PayPal-Ruby-SDK#132]
In a Sinatra application:

    require 'paypal-sdk-rest'

    include PayPal::SDK::REST

    get '/payments' do
      Payment.all(:count => 10).inspect
    end

On live I get:

I, [2015-06-15T10:58:43.198709 #12436]  INFO -- : Request[get]: https://api.paypal.com/v1/payments/payment?count=10
I, [2015-06-15T10:58:43.699023 #12436]  INFO -- : Response[503]: Service Unavailable, Duration: 30.508s
2015-06-15 10:58:43 - PayPal::SDK::Core::Exceptions::ServerError - Failed.  Response code = 503.  Response message = Service Unavailable.  Response debug ID = cfc0f4b58e5c3.

On sandbox I get:

I, [2015-06-15T11:07:52.640261 #12483]  INFO -- : Request[get]: https://api.sandbox.paypal.com/v1/payments/payment?count=10
I, [2015-06-15T11:07:54.890221 #12483]  INFO -- : Response[200]: OK, Duration: 2.250s

**Comment by juwlee** [comment]
@anthonyshull thanks for reporting. Can you share any other debug ID if this still persists? The system cannot seem to find the ID.

**Comment by anthonyshull** [comment]
2015-06-16 11:30:25 - PayPal::SDK::Core::Exceptions::ServerError - Failed.  Response code = 503.  Response message = Service Unavailable.  Response debug ID = 6be429a547ad8.:
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/util/http_helper.rb:151:in `handle_response'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/api/rest.rb:110:in `handle_response'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/util/http_helper.rb:85:in `http_call'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/api/base.rb:86:in `api_call'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/api/rest.rb:95:in `api_call'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/core/api/base.rb:104:in `get'
	/usr/local/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.2.1/lib/paypal-sdk/rest/data_types.rb:91:in `all'
	server.rb:28:in `block in <main>'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/logger.rb:15:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/usr/local/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'

**Comment by juwlee** [comment]
Thanks @anthonyshull . Can you please see if increasing [timeout](https://github.com/paypal/PayPal-Ruby-SDK/blob/d6a8b7e83ef1733ecd989be83888835088eee461/spec/config/paypal.yml#L8) helps?

**Comment by juwlee** [comment]
[Another issue](https://github.com/paypal/PayPal-PHP-SDK/issues/326#issuecomment-113615594) was opened for the same problem. We can track it there.
