### ISSUE TITLE
NameError: `@protection-eligibility' is not allowed as an instance variable name

### ISSUE THREAD

**Issue by Mistifyed** [paypal/PayPal-Ruby-SDK#133]
I'm trying to access the Order object for authorization, but the hyphen in the instance name is throwing an exception, has anyone else experienced this?

**Comment by juwlee** [comment]
@Mistifyed thanks for reporting this issue. I will release a fix soon.

**Comment by juwlee** [comment]
@Mistifyed a fix was released in v1.2.2. Please try it out and let us know if the problem persists.

**Comment by Mistifyed** [comment]
Thanks a lot for the patch! Will test it out right away.
