### ISSUE TITLE
Issues with the class name

### ISSUE THREAD

**Issue by harenderymca** [paypal/PayPal-Ruby-SDK#135]
Many gems in ruby use the same class name like Transaction , Invoice, Payment , PaymentDetails & InvoiceItem.

Please Use the unique name like PayPalTransaction , i have faced so many issues dealing with class name & i am assuming many will face the same issues.

Please update the class names.

**Comment by juwlee** [comment]
Hi @harenderymca can you please elaborate the problem to help me understand?
- what other gems are you using with this gem?
- what kind of issues have you dealt with?

**Comment by harenderymca** [comment]
Basically these are common name Transaction , Invoice, Payment , PaymentDetails & InvoiceItem every one use these name while dealing with payments stuff & create the class with same name .

Same thing happen in my case , In my application i have implemented all paypal classic API not when i tried to implement the new REST API in my application class name override & raise the use because PayPal's Rest gem is also using the same class name.

According to me class name in this name must be change & must be unique so that override issue will not raise for other developers.

for my solution i have modified the whole gem  used it inside my application.

**Comment by juwlee** [comment]
@harenderymca do you mean you get namespace conflicts with other PayPal gems?  [Merchant SDK has a different namespace](https://github.com/paypal/merchant-sdk-ruby/blob/master/lib/paypal-sdk/merchant/data_types.rb#L6), so the same class names can be resolved correctly if you specify the name space.

It would be great if you can share 
- what gems you are using
- the error message

**Comment by tristang** [comment]
@juwlee No, he means that the data types have been given generic names that are likely to clash with identically named classes from your application. Not necessarily other gems (which usually do the type of namespacing that @harenderymca is requesting), but from your application's own code.

For example, the `Payment` class is likely to conflict with any applications that also used the class name `Payment`:
https://github.com/paypal/PayPal-Ruby-SDK/blob/e6e0515dc7596808f4b259a9ddf1a1ee62d0648c/lib/paypal-sdk/rest/data_types.rb#L43

This issue could be avoided by namespacing these classes under `Paypal`, like `Paypal::Payment` and `Paypal::Invoice`.

**Comment by tristang** [comment]
Actually, I might have gotten the wrong idea from the documentation which uses the unscoped class names.

If you don't include `PayPal::SDK::REST::DataTypes` the data types are scoped as:

`PayPal::SDK::REST::DataTypes::Payout`

**Comment by juwlee** [comment]
@tristang you are right. If there is a conflict between two classes with the same name, their modules need to be specified to resolve correctly.

**Comment by madakopihub** [comment]
any update for this issue? @juwlee
