### ISSUE TITLE
503 error when creating a Payment

### ISSUE THREAD

**Issue by kofronpi** [paypal/PayPal-Ruby-SDK#136]
Hello,

I set up the ruby sdk in my Rails app and tried to create a payment several times in the rails console, but I always end up with a 503 error:

2.2.2 :088 > @payment = Payment.new({
2.2.2 :089 >         :intent => "sale",
2.2.2 :090 >         :payer => {
2.2.2 :091 >             :payment_method => "credit_card",
2.2.2 :092 >             :funding_instruments => [{
[...]
2.2.2 :109 >                       :subtotal => "7.41",
2.2.2 :110 >                       :tax => "0.03",
2.2.2 :111 >                       :shipping => "0.03"}},
2.2.2 :112 >               :description => "This is the payment transaction description." }]})
 => #<PayPal::SDK::REST::DataTypes::Payment:0x00000006cc77b0 @error=nil, @intent="sale", @payer=#<PayPal::SDK::REST::DataTypes::Payer:0x00000006cc74b8 @error=nil, @payment_method="credit_card", @funding_instruments=[#<PayPal::SDK::REST::DataTypes::FundingInstrument:0x00000006cc7170 @error=nil, @credit_card=#<PayPal::SDK::REST::DataTypes::CreditCard:0x00000006cc6f90 @error=nil, @type="visa", @number="4417119669820331", @expire_month=11, @expire_year=2018, @cvv2="874", @first_name="Joe", @last_name="Shopper", @billing_address=#<PayPal::SDK::REST::DataTypes::Address:0x00000006cc65e0 @error=nil, @line1="52 N Main ST", @city="Johnstown", @state="OH", @postal_code="43210", @country_code="US">>>]>, @transactions=[#<PayPal::SDK::REST::DataTypes::Transaction:0x00000006cc5e60 @error=nil, @amount=#<PayPal::SDK::REST::DataTypes::Amount:0x00000006cc5d48 @error=nil, @total="7.47", @currency="USD", @details=#<PayPal::SDK::REST::DataTypes::Details:0x00000006cc58e8 @error=nil, @subtotal="7.41", @tax="0.03", @shipping="0.03">>, @description="This is the payment transaction description.">]> 
2.2.2 :113 > 
2.2.2 :114 >   @payment.create
Request[post]: https://api.sandbox.paypal.com/v1/payments/payment
I, [2015-06-29T16:57:51.956079 #21733]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/payments/payment
Response[503]: Service Unavailable, Duration: 31.340s
I, [2015-06-29T16:58:23.296093 #21733]  INFO -- : Response[503]: Service Unavailable, Duration: 31.340s
PayPal::SDK::Core::Exceptions::ServerError: Failed.  Response code = 503.  Response message = Service Unavailable.  Response debug ID = 9fbb6f066f5c4.

What could be wrong ? Thanks !

**Comment by juwlee** [comment]
Hey @kofronpi there is a known issue with overused card number. Please try [a card number generator](https://ppmts.custhelp.com/app/answers/detail/a_id/750)

**Comment by kofronpi** [comment]
@juwlee thanks ! it works.

**Comment by juwlee** [comment]
@kofronpi great. I will update docs/code with a different credit card number.

**Comment by mahesh08** [comment]
I am using the npm paypal-rest-sdk in that calling the payout api. I am sending the body like email and amount for that.When I am calling that api/payments it gives the error like Response Status : 503.

Here is my code:

app.post('/api/payment',function(req,res){
    paypal.configure({
        'mode':"live", //sandbox or live
        'client_id': "*******",
        'client_secret': "*******"
      });


      var sender_batch_id = Math.random().toString(36).substring(9);
      var create_payout_json = {
        "sender_batch_header": {
            "sender_batch_id": sender_batch_id,
            "email_subject": "You have a payment"
        },
        "items": [
            {
                "recipient_type": "EMAIL",
                "amount": {
                    "value": req.body.amount,
                    "currency": "USD"
                },
                "receiver": req.body.email,
                "note": "Thank you.",
                "sender_item_id": Date.now()
            }
        ]
    };

    var sync_mode = 'true';

          paypal.payout.create(create_payout_json,sync_mode, function (error, payout) {
        if (error) {
            console.log(error.response);
            throw error;
        } else {
            console.log("Create Payout Response");
            console.log(payout);
        }
    });
})
I am getting the error response like 503.Please help me to solve this problem.Thanks

**Comment by pp-randy** [comment]
@mahesh08 can you provide the response JSON, or the debug_id value from the JSON response? 

The code looks like you are in live mode. If this is impacting your production integration you should reach out to PayPal Technical Support here:  https://www.paypal-techsupport.com/app/ask
