### ISSUE TITLE
"Unauthorized" when trying to capture future payment

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-Ruby-SDK#137]
I've implemented future payments in my iOS app, but I'm having some issues creating the actual payment when that time comes. This is the code I've implemented for capturing the payment:

      # Create future payment hash
      future_payment_hash = {
        "intent" =>  "authorize",
        "payer" =>  { "payment_method" =>  "paypal" },
        "transactions" =>  [ {
          "amount" =>  {
            "total" =>  "#{charge_amount.to_i}.00",
            "currency" =>  "USD" },
          "description" =>  "Slang - #{listing.headline}" } ]
        }

      # Get new payment token
      begin
        token  = Tokeninfo.refresh(buyer.paypal_token)
      rescue PayPal::SDK::Core::Exceptions::ServerError => err
        error_message("Couldn't authorize code.")
      end

      # Create payment
      ap future_payment_hash.merge( "token" => token )
      future_payment = FuturePayment.new(future_payment_hash.merge( "token" => token ))

      # Pay using Paypal
      ap "@paypal_metadata_id: #{@paypal_metadata_id}"
      if !future_payment.create(@paypal_metadata_id)
        ap future_payment.error
        error_message(future_payment.error.to_s)
      end

And the response I receive from the server:

      Parameters: {"listing_id"=>"-Jt0aCRDEJqMB8grMz7n", "paypal_metadata_id"=>"39d85aa85be74ba7a8375c020e9400db", "rate_id"=>"rate_8e2f2fcc935c4006a0de24204166b6b1", "shipment_id"=>"shp_e338c1ccf2144ee592ebbc4a3ab9d93d", "user_id"=>"-JslyXoILkyw3Zs9SvHq"}
      Request[post]: https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
      Response[200]: OK, Duration: 0.801s
      {
                "intent" => "authorize",
                 "payer" => {
              "payment_method" => "paypal"
          },
          "transactions" => [
              [0] {
                       "amount" => {
                         "total" => "57.00",
                      "currency" => "USD"
                  },
                  "description" => "Slang - Adidas ZX Flux "
              }
          ],
                  :token => {
              "access_token" => "A015M46jDKwAYYp0EHl9tG1zqb5DsitYNn1AbezsLm4MSQw",
                "token_type" => "Bearer",
                "expires_in" => 900
          }
      }
      "@paypal_metadata_id: 39d85aa85be74ba7a8375c020e9400db"
      PayPal-Request-Id: 0577a752-1c5f-40c5-95b4-9d1abd9a34d7
      Request[post]: https://api.sandbox.paypal.com/v1/payments/payment
      Response[401]: Unauthorized, Duration: 0.497s
      Completed 500 Internal Server Error in 3904ms

      PayPal::SDK::Core::Exceptions::UnauthorizedAccess (Failed.  Response code = 401.  Response message = Unauthorized.):
        app/controllers/v1/stripe_customer_controller.rb:166:in `charge'

I'm in Sandbox here. What could be the issue? What am I doing wrong?

**Comment by juwlee** [comment]
@holgersindbaek what version of SDK are you using? I wonder if it captured ```[paypal-debug-id](https://github.com/paypal/PayPal-Ruby-SDK/blob/d6a8b7e83ef1733ecd989be83888835088eee461/lib/paypal-sdk/core/exceptions.rb#L23)```. Also, can you elaborate what `buyer.paypal_token` has in `# Get new payment token` part?

**Comment by holgersindbaek** [comment]
@juwlee  Using 1.2.2 SDK.

The Paypal token I'm sending along is the refresh token, I've saved on the user. This one in other words:

token  = FuturePayment.exch_token(@auth_code)

I don't see any debug id.

**Comment by holgersindbaek** [comment]
@juwlee I'm a bit concerned, that I might be trying to refresh the access token in the wrong way. If I look at this guide: 

https://github.com/paypal/PayPal-Ruby-SDK/blob/d6a8b7e83ef1733ecd989be83888835088eee461/lib/paypal-sdk/core/api/rest.rb

I see that the path for refreshing the token is - https://api.paypal.com/v1/oauth2/token - but when I send the request using "Tokeninfo.refresh(buyer.paypal_token)", it sends it to this path - https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice.

So it seems like I'm receiving an access token, but am I receiving the right one? Could that be the issue?

**Comment by holgersindbaek** [comment]
@juwlee Any guesses?

**Comment by juwlee** [comment]
@holgersindbaek 2 things:
- You should pass authorization code that you got from mobile SDK, not refresh token. If you want to exchange refresh token for access token, please see [here](https://github.com/paypal/PayPal-Ruby-SDK#openid-connect)
- We will release a fix for the endpoint soon.

I will close the iOS SDK issue as we can track it here.

**Comment by holgersindbaek** [comment]
@juwlee Thanks for getting back to me. I still don't understand what I'm doing wrong.

Can you write the code that will get me the authorization code I'll need to use, using the refresh token I already have on the user? Generally, can you just give me a quick code example, charging a user that has already agreed to the future payments on the server side.

Generally how you'd do the server side stuff shown here - https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md - using this Ruby SDK?!

**Comment by juwlee** [comment]
@holgersindbaek 

It might be worth reading 
 - [future payment code sample](https://github.com/paypal/PayPal-Ruby-SDK#create-future-payment)
 - [future payment docs on developer docs](https://developer.paypal.com/webapps/developer/docs/integration/mobile/make-future-payment/)
as well as [the iOS SDK docs on future payment](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md) that you already have.

**Comment by holgersindbaek** [comment]
@juwlee Thank you for the links. I've already read through them and there's still one question to be answered:

How do I use a refresh token to get a new authorization token?

In the site you've linked to - future payment docs on developer docs - it says "For any future payment or authorization/capture, since the access token will have expired, use the refresh token to get a new access token for use calling the Payment API." in the "Exchange the auth code for refresh and access tokens" section. How would I do this using the Paypal Ruby SDK?

**Comment by holgersindbaek** [comment]
Ok... figured it out. All that was wrong, was that this piece of code:

    future_payment = FuturePayment.new(future_payment_hash.merge( :token => token ))

Which should have been like this:

    future_payment = FuturePayment.new(future_payment_hash.merge( :token => token.access_token ))

**Comment by juwlee** [comment]
@holgersindbaek glad that you found it! FuturePayment.exch_token()[https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/payment/create_future_payment.rb#L32] returns a token instance that has all attributes that are in [the response from the iOS SDK docs](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#response). [The code sample](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/payment/create_future_payment.rb#L34) also shows how to access those attributes.
