### ISSUE TITLE
Duplicate sender_item_id In Different Payout Items

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#138]
I've recently noticed that some retries are resulting in duplicate payouts using the bulk payments API.

From: https://developer.paypal.com/docs/integration/direct/create-batch-payout/
> For items, you can specify a sender_item_id. If the value for the sender_item_id is a duplicate of a payout item that was processed in the last 30 days, the item will not be processed. For example, in a call response, if the batch_status is DUPLICATE, it means your value for the sender_item_id is a duplicate. As a result, the new item is ignored.

However, running:

```ruby
PayPal::SDK::REST::PayoutItem.get("LTN...")
# <PayPal::SDK::REST::DataTypes::PayoutItemDetails @payout_item_id="LTN...", @transaction_status="SUCCESS", @payout_batch_id="SKM...", @payout_item=#<PayPal::SDK::REST::DataTypes::PayoutItem @sender_item_id="payment:2811">>

PayPal::SDK::REST::PayoutItem.get("F9V...")
# <PayPal::SDK::REST::DataTypes::PayoutItemDetails @payout_item_id="F9V...", @transaction_status="SUCCESS", @payout_batch_id="QGN...", @payout_item=#<PayPal::SDK::REST::DataTypes::PayoutItem @sender_item_id="payment:2811">>
```

Note: The two different payout items have the **SAME** `sender_item_id`.

This shouldn't be possible right? The documentation states that duplicate `sender_item_id`s should be ignored correct? My code for sending is:

```ruby
PayPal::SDK::REST::Payout.new({
  items: [{
    sender_item_id: "payment:#{payment.id}",
    recipient_type: 'EMAIL',
    amount: { value: payment.amount, currency: 'USD' },
    note: "...",
    receiver: email
  }]
})
```

**Comment by juwlee** [comment]
@ksylvest the doc means that `sender_item_id` can be a duplicate. if it is a duplicate and if the payout item was processed in the last 30 days, it will not be processed, and you should get `batch_status` as `DUPLICATE` in the response. Are you seeing different behavior?

**Comment by ksylvest** [comment]
@juwlee In the example pasted both payouts were submitted with the same `sender_item_id` and both were processed (i.e. the recipient received double the payment).

**Comment by juwlee** [comment]
Thanks @ksylvest for reporting. I reached out to Payouts API team. I will update this thread once I hear back from them.

**Comment by juwlee** [comment]
@ksylvest please see below for the payouts validation criteria for `sender_batch_id` and `sender_item_id`. In short, `sender_item_id` is not bound to the 30 day duplicate rule. There is a bit of gap between the docs and payouts current behavior, and I have let the documentation team know to update them.

- Sender_batch_id is optional. This id can be used by the sender to uniquely identify the batch submitted from his side.
- If the sender_batch_id is used, the same id cannot be used for next 30 days. If the batch processing hits denied state (some reason the batch doesn’t successfully process), then the sender_batch_id can be reused. We in fact, resubmit batches in the next 6 hours after it hits the denied state. In this case, the same sender batch id is used.
- The sender_item_id is never accounted for validation on the basis similar to sender_batch_id. Sender_item_id can be duplicate. There is no cut off period like 30 days for sender_item_id.

Hope this helps.

**Comment by ksylvest** [comment]
@juwlee Does the `sender_item_id` do anything? This is more than a little gap and extremely frustrating.

**Comment by juwlee** [comment]
[Developer docs](https://developer.paypal.com/webapps/developer/docs/api/#payoutitem-object) has description on the `sender_item_id`.

**Comment by ksylvest** [comment]
The docs for `sender_item_id` state:

> For items, you can specify a sender_item_id. If the value for the sender_item_id is a duplicate of a payout item that was processed in the last 30 days, the item will not be processed.

Doesn't this make sense as functionality?

**Comment by ksylvest** [comment]
@juwlee Hey, any followup? This issue has been open for a week and then was closed without a fix! Really frustrating and the functionality ISN'T clear.

**Comment by thisisbalajibabu** [comment]
Hi @ksylvest  ,
Apologies for the confusion. The documentation needs to be updated.

•	Currently, when the Payouts API is used for sending bulk/single payments, the sender_batch_id alone is validated accordingly.
•	The sender_item_id is not considered for any kind of validation. The sender_item_id can be duplicate.
•	The sender_batch_id is optional. If the sender_batch_id is used, it cannot be duplicated within 30 days of its earlier usage.


The documentation will be updated shortly with all these details. 

Best Regards
Balaji Babu

**Comment by ksylvest** [comment]
@thisisbalajibabu This doesn't sound like a documentation bug. This sounds like an API bug. The `sender_item_id` is the only way to de-dupe a single item when queueing up bulk batches. Can this not be fixed?

**Comment by thisisbalajibabu** [comment]
Hi @ksylvest 
 I just confirmed on the current behaviour of how the payouts API behaves. I appreciate and understand your use case perspective with respect to sender_item_id. We will look on the existing integration with Payouts API and will conclude on ways to include your request. I will keep you posted on the updates.

Best Regards
Balaji Babu

**Comment by juwlee** [comment]
Re-opening to track a fix for duplicate single items.

**Comment by ksylvest** [comment]
@juwlee Do you have any followup? This has been open for over a month.

**Comment by juwlee** [comment]
@ksylvest we are trying from our end to push for this bug. However, your directly requesting this to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) would help prioritize the bug.

@thisisbalajibabu Please post any news here if you have any to keep @ksylvest updated.

**Comment by thisisbalajibabu** [comment]
@ksylvest 
You will get a validation error as below when you send a duplicate item ID **within the same batch**
`"errors": {
        "name": "DUPLICATE_ITEM",
        "message": "REF_ID matches with another item in the batch",
        "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_ITEM"
      },
`
However the same item_id can be reused for another item in a different batch.

Thanks
Balaji Babu

**Comment by ryanorrico** [comment]
This is old and I have no idea if It will help someone, but I got hung up and @thisisbalajibabu's comment helped me.

I just added a short random-string to the end of each sender_item_id and that fixed it. I don't know why I didn't realize I was assigning all of them the same id.
