### ISSUE TITLE
How Should Retries Be Handled For Errors

### ISSUE THREAD

**Issue by ksylvest** [paypal/PayPal-Ruby-SDK#139]
When the API errors with messages like: **RECEIVER_UNCONFIRMED** or **RECEIVER_ACCOUNT_LOCKED** what is the correct way to re-process the failed `PayPal::SDK::REST::PayoutItem` to ensure multiple payments aren't processed after the user has resolved account issues?

**Comment by thisisbalajibabu** [comment]
Hi @ksylvest 
For RECEIVER_UNCONFIRMED,
 you get this error only when the receiver's email is unconfirmed. When you get the RECEIVER_UNCONFIRMED error, the transaction status for the item will be displayed as "transaction_status": "UNCLAIMED", In this case, once the receiver confirms his/her email, the payment processed will be available in receiver's PayPal Balance. We need not reprocess or resubmit the payment. There is a limitation with respect to the number of days the item status can remain UNCLAIMED. After 30 days, still if the receiver doesn't confirm the email,  the payment will be reversed back to the sender's PayPal Balance. You can see this transaction activity in Account OverView Page of the sender account. In this case, the sender has to submit a new Payment.

For RECEIVER_ACCOUNT_LOCKED,
 you get this error only when the receiver's account is locked. When you get the RECEIVER_ACCOUNT_LOCKED error, the transaction status for the item will be displayed as "transaction_status": "FAILED", In this case, the funds will be returned to sender. So the sender has to inform the receiver about the account being locked. When the account is unlocked, sender can submit a new payment.

**Comment by juwlee** [comment]
Closing per [@thisisbalajibabu 's answer](https://github.com/paypal/PayPal-Ruby-SDK/issues/139#issuecomment-121602649). (Thanks @thisisbalajibabu !). @ksylvest please re-open if you have any further question.
