### ISSUE TITLE
Chained Payments

### ISSUE THREAD

**Issue by lws68825** [paypal/PayPal-Ruby-SDK#141]
Hi,
Is chained payments available with REST api now?

**Comment by juwlee** [comment]
Hi @lws68825 . It is the plan to add the functionality, however, it is not available yet. We can probably track the progress with [this issue](https://github.com/paypal/PayPal-iOS-SDK/issues/9)

**Comment by garfieldmypet** [comment]
Hi, @juwlee . Is chained payment already in progress? I know that we have been asking so many times in the forum, however, we have waited for 2 years. 

Please do help to push forward to let PayPal team know how this feature is so important to us, please do give it some priority as we really need it.
