### ISSUE TITLE
URGENT: Intermittent VALIDATION_ERROR returned by PayPal in Live!

### ISSUE THREAD

**Issue by caphun** [paypal/PayPal-Ruby-SDK#142]
It's always returning the same error. The customer tried 2 separate cards. Both MasterCard and still get the same error:

```
{
  "debug_id": "b782680e2d17d",
  "details": "[{\"field\"=>\"payer.funding_instruments[0].credit_card.type\", \"issue\"=>\"Value is invalid (must be visa, mastercard, amex, or discover)\"}]",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
  "message": "Invalid request - see details",
  "name": "VALIDATION_ERROR"
}
```

More debug_id's:

99bb918606244
8bf04dd4a6a58
e86fc9fff420f

**Comment by juwlee** [comment]
@caphun did you specify `type` as shown [here](https://developer.paypal.com/webapps/developer/docs/api/#create-a-payment)?

**Comment by caphun** [comment]
I am using the credit_card_validator gem to get the type:
```
card_type = CreditCardValidator::Validator.card_type(credit_card_options[:number])
```
Sorry, I should be more specific in my original post. This is an intermittent error so I am getting successful transactions but not always as in the 4 cases above.

**Comment by juwlee** [comment]
Does it always return one of `visa`, `mastercard`, `discover`, `amex`? It would be helpful to log full requests to check if there is any difference between failures and success.

**Comment by caphun** [comment]
I fixed it! Thanks for pointing me in the right direction. the credit_card_validator was returning type as `master_card` whereas PayPal is expecting `marstercard`
