### ISSUE TITLE
PayPal Plus compatible?

### ISSUE THREAD

**Issue by swelther** [paypal/PayPal-Ruby-SDK#143]
Hello,

maybe you heard already of this new "PayPal Plus" started beginning of the year. I'm not sure if it is only a European/German thing or a world wide one?

Does anybody know if this gem and it's APIs are compatible with PayPal Plus? As always, the PayPal documentation is confusing and unclear. Could found anything about this "Plus" thing.

Has anybody any experience or knowledge?

**Comment by juwlee** [comment]
Hi @swelther 

- It is only available for German merchant accounts.
- It should be compatible. Please feel free to open an issue if not.

**Comment by swelther** [comment]
Thx for the answer. At the moment I hesitate a bit to change the merchant account and hope everything works with the gem. But if it should work I will give it a try :)

**Comment by KjellMorgenstern** [comment]
Facing the same question, and after a good time of searching this thread is the only reference I found.
Anyone with a working implementation who can confirm it works?
