### ISSUE TITLE
How to interpret the express checkout success process using in context modals.

### ISSUE THREAD

**Issue by jcdavison** [paypal/PayPal-Ruby-SDK#145]
Hi Devs, I'm sure that what I'm about to post isn't a bug in the library but I'm quite unclear on a few things and SO isn't giving me much feedback so I'm just going to outline my situation here and maybe someone can politely confirm or negate a few of my assumptions.

I'm attempting to implement a standard 'use paypal to checkout' flow using express checkout with in context modals.

I'm rendering a button to a user that successfully uses the paypal checkout.js to listen for a click on a given button.  The button has a href that looks like 

`'https://www.sandbox.paypal.com/checkoutnow?token=EC-7TM50207WN762413T#checkout/login'`

The value of the token I retrieved via

`curl -s --insecure  https://api-3t.sandbox.paypal.com/nvp  -d  "USER=person-facilitator_api1.gmail.com&PWD=foofoofoo&SIGNATURE=barbarbarN2&METHOD=SetExpressCheckout&VERSION=78&PAYMENTREQUEST_0_PAYMENTACTION=SALE&PAYMENTREQUEST_0_AMT=19&PAYMENTREQUEST_0_CURRENCYCODE=USD&cancelUrl=http://localhost:3000/hook&returnUrl=http://localhost:3000/hook"`

which returned 

`TOKEN=EC%2d8PB28566YL9742127&TIMESTAMP=2015%2d07%2d29T19%3a16%3a11Z&CORRELATIONID=ba8948c4b5df3&ACK=Success&VERSION=78&BUILD=000000`

Once my user gets to the in context modals, I'm a little nervous because nowhere is the price displayed, see screenshot 

https://www.dropbox.com/s/ucumrs88b7z7ms6/Screenshot%202015-07-29%2015.18.19.png?dl=0

But my real question(s) revolve around what does it actually mean to click 'continue', the callback to my server has the params

`{"token"=>"EC-7TM50207WN762413T", "PayerID"=>"KLR8BRB4T2DCN", "controller"=>"home", "action"=>"hook"}`

And I'm pretty unclear if these params indicate that the transaction has been properly processed for payment or more steps need to be taken as in 

`curl -s --insecure https://api-3t.sandbox.paypal.com/nvp -d "USER=person-facilitator_api1.gmail.com&PWD=foooU79FH3TK&SIGNATURE=fooo0N2&METHOD=DoExpressCheckoutPayment&VERSION=93&TOKEN=EC-7TM50207WN762413T&PAYERID=KLR8BRB4T2DCN&PAYMENTREQUEST_0_PAYMENTACTION=SALE&PAYMENTREQUEST_0_AMT=19.00&PAYMENTREQUEST_0_CURRENCYCODE=USD"`

Different indicators would kind of communicate to me that the transaction was processed including the server response from the above curl that says something like 

`L_LONGMESSAGE0=A%20successful%20transaction%20has%20already%20been%20completed%20for%20this%20token%2e&L_SEVERITYCODE0=Warnin` 

which indicates that the transaction is considered to already have been confirmed and also, if I attempt to reroute a user through the checkout flow i'm presented with the below screenshot,

https://www.dropbox.com/s/p6629g1yflvolb1/Screenshot%202015-07-29%2015.16.22.png?dl=0

So I'm thinking that once the user clicks the 'continue' button in the in context express checkout modal, the transaction IS considered to be confirmed and at that point the purchasing user should expect to be charged something.  I would generally expect that I could see these transactions in the developer console, but alas, I'm getting some kind of error message from the paypal interface. 

https://www.dropbox.com/s/hhaaf20oydu85w7/Screenshot%202015-07-29%2015.24.47.png?dl=0

Any feedback on my perception of this situation would be greatly appreciated. 

Thanks,

JD
:swimmer:

**Comment by juwlee** [comment]
@jcdavison I opened [an issue in merchant SDK](https://github.com/paypal/merchant-sdk-ruby/issues/22) as that SDK uses Express Checkout and hence a better place to discuss EC issues.
