### ISSUE TITLE
PayPal::SDK::Core::Exceptions::ServerError 500 error on create and execute payment

### ISSUE THREAD

**Issue by aiperon** [paypal/PayPal-Ruby-SDK#148]
Same type of issue as https://github.com/paypal/PayPal-Ruby-SDK/issues/109 appeared in production mode on create and execute processes:

    Failed. Response code = 500. Response message = Internal Server Error. Response debug ID = debc26a576f5f.

Few debug ids on:
* create - c8f6b2a5c9813, ef1b4913d3b95
* execution - debc26a576f5f, de6351ed40e12, 1b7e90e8ba0e5

We didn't noticed these errors in sandbox mode.

**Comment by tomwhipple** [comment]
@aiperon since this is an underlying API problem, the [merchant support team](https://www.paypal.com/mts) is best able to look up these debug IDs to figure out what's happening.
