### ISSUE TITLE
Is it possible to get a list of all transactions a user has made on paypal?

### ISSUE THREAD

**Issue by Deekor** [paypal/PayPal-Ruby-SDK#151]
Please see: http://stackoverflow.com/questions/32260871/is-it-possible-to-get-a-list-of-all-transactions-a-user-has-made-on-paypal/32261054

Again I don't want a list of transactions I have made or my app has made. I want a user to be able to login to my website via paypal and then using the `access_token` allow me to read any transactions they have made on paypal with any merchant. Is this possible?

**Comment by juwlee** [comment]
Hi @Deekor it sounds like [this API](https://developer.paypal.com/webapps/developer/docs/api/#list-payment-resources) might be what you are looking for. See [here](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L92) for implementation in this SDK.

**Comment by juwlee** [comment]
You should be able to specify 3rd party `access_token` by passing `: access_token` parameter.

**Comment by Deekor** [comment]
@juwlee thats the api I was trying but the `access_token` I receive from the user when they auth through OpenID doesn't work.

To be clear I'm not trying to search my transactions, I'm trying to search the transactions of a random user who logs into my website via paypal whether the transaction has anything to do with me or not is irrelevant. This is for accounting software and Id like to import the transactions to add to the users credits and debits. Does that make sense?

**Comment by juwlee** [comment]
@Deekor yes, it does. A few questions:

- how did you pass the `access token` for the end user?
- what error did you get in response?
- do you have some `debug ID`s for those errors handy?

**Comment by Deekor** [comment]
I was just trying to pass the access token in through a curl request to test it and was receiving a `401 unauthorized`
