### ISSUE TITLE
Paypal payment update issue

### ISSUE THREAD

**Issue by Akshatha357** [paypal/PayPal-Ruby-SDK#152]
I want to update shipping address after creating payment through Paypal, when I updating shipping address with update PATCH request. I got the following errors.

     shipping_address = {
      line1: 'Address Line 1',
      line2: 'Address Line 2',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400001',
      country_code: 'USD',
      phone: '123456789',
      recipient_name: 'TestName'
    }
    if @payment.create
      # Redirect the user to given approval url
      @redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
      logger.info "Payment[#{@payment.id}]"
      logger.info "Redirect: #{@redirect_url}"

      patch = {
                op: "add",
                path: "/transactions/0/item_list/shipping_address",
                value: shipping_address
              }
      patch_request = PatchRequest.new(patch)
      if @payment.update( patch )
        logger.info "Payment[#{@payment.id}]"
        logger.info "Redirect Shippment: #{@redirect_url}"
      else
        logger.error @payment.error.inspect
      end

undefined method `op=' for #<PaypalExpress::PatchRequest:0x00000006925af8>
undefined method `path=' for #<PaypalExpress::PatchRequest:0x00000006925af8>
undefined method `value=' for #<PaypalExpress::PatchRequest:0x00000006925af8>
undefined method `op=' for #<PayPal::SDK::REST::DataTypes::PatchRequest:0x00000005f73a50>
undefined method `path=' for #<PayPal::SDK::REST::DataTypes::PatchRequest:0x00000005f73a50>
undefined method `value=' for #<PayPal::SDK::REST::DataTypes::PatchRequest:0x00000005f73a50>
PayPal-Request-Id: 08842095-f321-dtxzd6fgxfh8
Request.body={"op":"add","path":"/transactions/0/item_list/shipping_address","value":{"recipient_name":"Gruneberg, Anna","line1":"Kathwarinenhof 1","city":"Flensburg","postal_code":"24939","country_code":"DE"}}	request.header={"X-PAYPAL-SANDBOX-EMAIL-ADDRESS"=>"test@test.com", "Authorization"=>"Bearer A015iDVLWtgNgdbtfgsdtsb sxtsdrt bzew", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.3.3 (paypal-sdk-core 1.3.3; ruby 2.2.2p95-x86_64-linux)", "PayPal-Request-Id"=>"44fbccde-4d6236546-346cddbe8c"}

Response[400]: Bad Request, Duration: 5.622s
Response.body={"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"ea5e654612a58"}	Response.header={"date"=>["Thu, 10 Sep 2015 08:52:36 GMT"], "server"=>["Apache"], "proxy_server_info"=>["host=slcsbplatformapiserv3002.slc.paypal.com;threadId=131999"], "paypal-debug-id"=>["ea5e654612a58"], "correlation-id"=>["ea5e654612a58"], "content-language"=>["*"], "connection"=>["close", "close"], "content-length"=>["213"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D3561288021; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-type"=>["application/json"]}

**Comment by juwlee** [comment]
@Akshatha357 please see [this sample](https://github.com/paypal/PayPal-Ruby-SDK/blob/9a91c41ec1688b1e963e20dfffb77976a2ec020d/spec/subscription_examples_spec.rb#L87). `Patch` should be used in place of `PatchRequest`.
