### ISSUE TITLE
An Unknown Error occurred while making payment

### ISSUE THREAD

**Issue by ErPuneetGoel** [paypal/PayPal-Ruby-SDK#156]
Hi Team, 

While making a payment on my sandbox and live environment i am getting error 
"An unknown error has occurred"
debug_id = "f36acfbb36397"

Earlier it was working fine. But this is happening from past few days (not sure). I actually checked it today as reported by me. Please check what is the issue.

**Comment by ppmtscory** [comment]
This has to do with the test credit card that you are using.  Please refrain from using the 41111.... test card as it's way overused in our system and therefore can cause problems.  You can utilize our [help page](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US) to generate a card number under Step 4.  Also, if you have any further questions regarding payment errors, please feel free to consult our [Merchant Tech Support](https://www.paypal.com/mts).
