### ISSUE TITLE
WARN -- : DEBUG log level not allowed in sandbox mode for security of confidential information. Changing log level to INFO..

### ISSUE THREAD

**Issue by dmitrypol** [paypal/PayPal-Ruby-SDK#157]
I keep getting those messages in my logs which makes it hard to see real issues.  .  

My initializers/paypal.rb has
PayPal::SDK.logger.level = Logger::INFO

Any ideas on how to turn it off?

**Comment by ppmtscory** [comment]
@dmitrypol are you certain that your application is not setting the logging level to DEBUG somewhere?  The SDK is set to only throw that warning when the environment is set to live AND the logger is set to DEBUG.

**Comment by dmitrypol** [comment]
I actually do not have a PayPal environment set to live (it will be specific to each customer in our system).  I have just one environment for my own testing where I am using sandbox mode (even though my rails app is running in Rails production environment).

**Comment by ppmtscory** [comment]
Hmm... I'm not able to reproduce this with the samples from the SDK so let me call out @juwlee to have a look and see what I'm missing here.

**Comment by juwlee** [comment]
@dmitrypol how is the environment set? Is it set as shown in [this sample](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/config/paypal.yml#L10)?

**Comment by dmitrypol** [comment]
No.  In our system customers enter their credentials into a web UI and then they are stored in encrypted DB.  Then depending on which customer we are processing 

Here is my paypal.yml:

test: &default

  # Credentials for REST APIs
  # client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  # client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  #app_id: APP-80W284485P519543T
  #username: jb-us-seller_api1.paypal.com
  #password: WX4WTU3S8MY44S7F
  #signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  #sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live

And config/initializers/paypal.rb:
#PayPal::SDK.load("config/paypal.yml", Rails.env)
PayPal::SDK.logger = Rails.logger.money # using multi_logger gem.  
PayPal::SDK.logger.level = Logger::INFO

When I process transaction I do:
PayPal::SDK::REST.set_config(
 :mode => customer.credit_card_processor_gateway,
 :client_id => customer.cc_proc_login,
 :client_secret => customer.cc_proc_key

**Comment by juwlee** [comment]
Can you check if `config.mode` is set to `live` and `logger.level` to `DEBUG` in any occasion? That is the condition to print the warning message.

**Comment by anthonyalberto** [comment]
Same thing happening to us. Log level was set to DEBUG, I then set to INFO and redeployed. After that, it still complains that log level is DEBUG, but there's no instance of DEBUG at all in the code base, confusing

**Comment by bluk** [comment]
I've tried reproducing on Heroku but wasn't able to. I thought the issue may be that the `paypal.yml` has this section by default:

```
production:
<<: *default
mode: live
```

So if you deploy your Rails application in production mode, you may have set the PayPal environment mode to `live`.

If this is still an issue for anyone, please leave a comment.
