### ISSUE TITLE
Is there a way to verify API credentials via test API call?

### ISSUE THREAD

**Issue by dmitrypol** [paypal/PayPal-Ruby-SDK#158]
We have a platform where multiple customers have different PayPal credentials.  They enter them into our system but it would be nice to ping PayPal API and verify that credentials are correct.

**Comment by ppmtscory** [comment]
@dmitrypol are you referring to the classic API credentials of username, password, signature/certificate or are you referring to the REST credentials of client ID and secret?

**Comment by dmitrypol** [comment]
Sorry, REST API.

**Comment by ppmtscory** [comment]
You could do an immediate call to generate an access token....
```
curl -v https://api.sandbox.paypal.com/v1/oauth2/token \
 -H "Accept: application/json" \
 -H "Accept-Language: en_US" \
 -u "clientID:clientSecret" \
 -d "grant_type=client_credentials"
```
If the credentials are not valid, then you should get an error stating as such.  If the access token is created, then they've entered valid credentials.

**Comment by dmitrypol** [comment]
sorry for the silly question but how would I do that via the PayPal-Ruby-SDK?  I don't want to create future payment or use any OpenID stuff.  Thank you again for your help.

**Comment by ppmtscory** [comment]
You should be able to call methods [here](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/set_api.rb#L31) to set the credentials and then the method [here](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/api/rest.rb#L48) can be used to create an access token.
