### ISSUE TITLE
Creating an agreement in the sandbox returns an invalid token?

### ISSUE THREAD

**Issue by jay-snee** [paypal/PayPal-Ruby-SDK#159]
12:08:06 web.1    | Started GET "/created_subscription?token=EC-8BD530652L760033T" for 127.0.0.1 at 2015-    10-12 12:08:06 +0100
    12:08:06 web.1    | Processing by HomeController#created_subscription as HTML
    12:08:06 web.1    |   Parameters: {"token"=>"EC-8BD530652L760033T"}
    12:08:06 web.1    |   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER     BY "users"."id" ASC LIMIT 1  [["id", 22]]
    12:08:06 web.1    |   Subscription Load (0.5ms)  SELECT  "subscriptions".* FROM "subscriptions" WHERE     "subscriptions"."user_id" = $1 AND "subscriptions"."paypal_id" = $2  ORDER BY "subscriptions"."id" ASC     LIMIT 1  [["user_id", 22], ["paypal_id", "EC-8BD530652L760033T"]]
    12:08:06 web.1    | PayPal-Request-Id: 99a4120a-0da8-422a-ad1d-65b9d11d2d43
    12:08:06 web.1    | Request[post]: https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-    8BD530652L760033T/agreement-execute
    12:08:06 web.1    | Request.body={} request.header={"Authorization"=>"Bearer <my-auth-string>", "Content-Type"=>    "application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.3.3 (paypal-sdk-core 1.3.3; ruby 2.2.2p95-    x86_64-darwin14)", "PayPal-Request-Id"=>"99a4120a-0da8-422a-ad1d-65b9d11d2d43"}
    12:08:08 web.1    | Response[400]: Bad Request, Duration: 2.665s
    12:08:08 web.1    | Response.body={"name":"CANNOT_FIND_PROFILE_DESC","message":"Profile description is     invalid","information_link":"https://developer.paypal.    com/webapps/developer/docs/api/#CANNOT_FIND_PROFILE_DESC","debug_id":"191f787ec23bd"}  Response.    header={"date"=>["Mon, 12 Oct 2015 11:08:07 GMT"], "server"=>["Apache"], "proxy_server_info"=>[    "host=slcsbplatformapiserv3002.slc.paypal.com;threadId=360"], "paypal-debug-id"=>["191f787ec23bd",     "191f787ec23bd"], "correlation-id"=>["191f787ec23bd"], "content-language"=>["*"], "content-length"=>[    "208"], "vary"=>["Authorization"], "content-type"=>["application/json"], "set-cookie"=>["X-PP-    SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D2543065942; domain=.    paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"],     "connection"=>["close"]}
    12:08:08 web.1    | Redirected to http://localhost:5000/
    12:08:08 web.1    | Completed 302 Found in 2684ms (ActiveRecord: 2.8ms)

This is from a Rails app - `/created_subscription` is the redirect_url from the agreement authorisation redirect so the token provided by the API should be valid? Attempting to execute the agreement triggers the `CANNOT_FIND_PROFILE_DESC` error. Any clues?

**Comment by ppmtscory** [comment]
@jay-snee as the error suggests, it seems that you didn't include a `description` in your [agreement creation](https://developer.paypal.com/docs/api/#create-an-agreement).  Can you validate how you are creating the agreement prior to executing?

**Comment by jay-snee** [comment]
Hi @ppmtscory - Er actually, no that wasn't the case at all. I should have closed this already, although the docs could do with updating. 

As far as I could tell, it had nothing to do with the description (as it was present). It was due to the sandbox merchant account I was using for testing being quite old. After I generated a new sandbox account and switched the credentials round everything began working as expected. I found the answer in the comments of an SO post, but I can't for the life of my find the link now, sorry!

**Comment by ppmtscory** [comment]
Hmm.. that seems strange, however, thank you for the update!  I'll close the issue as resolved for now but please do post the SO issue on here if you find it so that I can reproduce and, if need be, get the error message and/or docs updated accordingly.
