### ISSUE TITLE
Problems updating a payment

### ISSUE THREAD

**Issue by RafaelFMori** [paypal/PayPal-Ruby-SDK#163]
Hello there!

I'm having a problem trying to update the amount of a payment.(though I really think that I'm doing something wrong).

I'm doing something like this:

  payment = Payment.find(payment_id) -- it returns me the payment that was previously created
    updated_payment = {
      :op=> "replace",
      :path=> "/transactions/0/amount",
      :value=> {
        :total=> "40.00",
        :currency=> "BRL",
        :details=> {:shipping=>"25.00", :subtotal=>"15.00"}
       }
     }
      patch_request = Patch.new(updated_payment)

But when I try to do the update ----- payment.update( updated_payment )

it gives me this error:

NameError: undefined local variable or method `object' for #<PayPal::SDK::REST::DataTypes::Payment:0x00000003ea12a0>

**Comment by juwlee** [comment]
@RafaelFMori Can you try it on the latest version? Please note a commit 87b4016a031d6ea5f95441ec68b45b30e4313d16 related to payment update.

**Comment by RafaelFMori** [comment]
Hi Juwlee I'm already using the latest version of the gem. Thanks for pointing me this commit but I had seen this already. And did you notice something wrong in my code whatsoever?

**Comment by juwlee** [comment]
@RafaelFMori can you please share the full error dump?

**Comment by RafaelFMori** [comment]
Yes, here it is, sorry for not posting it before.

    begin
      payment.update(updated_payment)  
    rescue => e  
      puts e.backtrace  
    end  
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/paypal-sdk-rest-1.3.3/lib/paypal-sdk/rest/data_types.rb:74:in `update'
(pry):2:in `update_payment'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `eval'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:323:in `handle_line'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `block in eval'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `catch'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `eval'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:77:in `block in repl'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:67:in `loop'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:67:in `repl'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:38:in `block in start'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/input_lock.rb:61:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/input_lock.rb:79:in `with_ownership'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:38:in `start'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/repl.rb:15:in `start'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/pry_class.rb:169:in `start'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/pry-0.10.3/lib/pry/core_extensions.rb:43:in `pry'
/home/rafaelmouri/projects/checkout/app/services/paypal_payment_service.rb:27:in `update_payment'
/home/rafaelmouri/projects/checkout/app/use_case/change_package_default_shipping.rb:14:in `execute'
/home/rafaelmouri/projects/checkout/app/controllers/v1/order_packages_controller.rb:5:in `update'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activerecord-4.2.4/lib/active_record/migration.rb:377:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/commonlogger.rb:31:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
/home/rafaelmouri/.rvm/gems/ruby-2.2.2@checkout/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

**Comment by RafaelFMori** [comment]
@juwlee, did it help? Is there anything else i could help you with?

**Comment by juwlee** [comment]
@RafaelFMori Thanks for sharing the stack trace. We will look into it and circle back to you.

**Comment by RafaelFMori** [comment]
@juwlee Thanks a lot.

**Comment by juwlee** [comment]
@RafaelFMori The problem has been identified. Looks like PR #153 changed the behavior. I pushed a commit d97f6c27033fb55e021d3bee3f80da02e3f09b7d that should address this problem. It will be shipped in the next release shortly. Also, please see [payment update sample code here](https://github.com/paypal/PayPal-Ruby-SDK/blob/v1.3.4/samples/payment/update.rb).
