### ISSUE TITLE
How to update a credit card

### ISSUE THREAD

**Issue by benross** [paypal/PayPal-Ruby-SDK#166]
Hey Guys,

Looking for any documentation / help on how to update an existing credit card. 

Let's say I want to change the expire year...I'd expect to able to do
cc = @api::CreditCard.find(the_paypal_id)
cc.expired_year = 2020
cc.update

This returns MALFORMED_REQUEST error. Tried looking at update examples for other models but couldn't find anything that translates. Really appreciate any pointers in the right direction.

**Comment by ppmtscory** [comment]
Documentation for updating a stored card can be found [here](https://developer.paypal.com/docs/api/#update-a-stored-credit-card).  That is a standard curl example but you can also use the [update payment](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/payment/update.rb) sample as a reference point.

**Comment by benross** [comment]
Hey @ppmtscory thanks for the response. I've looked at both the examples you referenced. Seems like the CreditCard object behaves differently than the Payment object. Based on that example, I would expect this to work:

require 'paypal-sdk-rest'
@api = PayPal::SDK::REST
card = @api::CreditCard.find('CARD-73Y20605AY903523PKY5YIMA')
updated_card = {
  :op=> "replace",
  :path=> "/billing_address",
  :value=> {
  "line1": "111 First Street",
  "city": "Saratoga",
  "country_code": "US",
  "state": "CA",
  "postal_code": "95070"
  }
}
patch_request = @api::Patch.new(updated_card)
card.update(updated_card)

The first problem is that card.update(updated_card) gives an error that it doesn't take any arguments (ArgumentError: wrong number of arguments (1 for 0)). 

If I just run card.update with no arguments again PayPal returns Malformed Request(Incoming JSON request does not map to API request)

Any ideas what is going on here? Any documentation or details about how CreditCard.update works?

**Comment by ppmtscory** [comment]
After further digging, it appears that the `update()` method for credit card was not correct.  This has been fixed and will be released some time next week with the next planned release.

**Comment by benross** [comment]
Well that's good news I'm not (completely) crazy! Looking forward to the release. Really appreciate your help.

**Comment by benross** [comment]
Looks like this works with the new update pushed :-). For anyone stumbling upon this in the future, here an example to update the year of a credit card:

require 'paypal-sdk-rest'
@api = PayPal::SDK::REST
card = @api::CreditCard.find('CARD-XXXXXX')
updated_card = {
  :op=> "replace",
  :path=> "/expire_year",
  :value=> 2017
}
patch_request = @api::Patch.new(updated_card)
card.update(updated_card)

**Comment by ppmtscory** [comment]
Thanks for the update, @benross, glad it's working after the fix!
