### ISSUE TITLE
Strange Warnings

### ISSUE THREAD

**Issue by RafaelFMori** [paypal/PayPal-Ruby-SDK#168]
Hi guys,
I have a paypal rest implementation working perfectly, but yesterday I've noticed some warnings that I don't recognize.

    W, [2015-11-12T21:54:37.790171 #19504]  WARN -- : undefined method `recurring_flag=' for   #<PayPal::SDK::REST::DataTypes::PaymentOptions:0x000000072ac338>
    W, [2015-11-12T21:54:37.790323 #19504]  WARN -- : undefined method `skip_fmf=' for #<PayPal::SDK::REST::DataTypes::PaymentOptions:0x000000072ac338>

**Comment by juwlee** [comment]
@RafaelFMori  it seems there is some discrepancy between API behavior and its documentation. Please reach out to [MTS](https://www.paypal-techsupport.com/app/ask/session) to raise this issue.
