### ISSUE TITLE
OpenSSL::X509::StoreError: system lib

### ISSUE THREAD

**Issue by Zmokizmoghi** [paypal/PayPal-Ruby-SDK#170]
Hi!

I'm getting OpenSSL::X509::StoreError exception, when i try to validate event via WebhookEvent.verify method.

I've already found dirty solution: hardcode full path to certificates on line 1265 and 1266, inside https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L1265
Thats how it looks:
```
root_cert = "/Users/zmoki/.rvm/gems/ruby-2.2.1/gems/paypal-sdk-rest-1.4.1/data/DigiCertHighAssuranceEVRootCA.pem"
            intermediate_cert = "/Users/zmoki/.rvm/gems/ruby-2.2.1/gems/paypal-sdk-rest-1.4.1/data/DigiCertSHA2ExtendedValidationServerCA.pem"
```

I use OS X 10.11.1, rvm 1.26.11, ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14], openssl 1.0.2e and paypal-sdk-rest 1.4.1

I cannot reproduce this problem on any other linux or osx machines, sadly.

Thanks.

**Comment by juwlee** [comment]
@Zmokizmoghi do the other environments have the same setup? I cannot seem to reproduce this issue either but wonder what is the difference that causes it. Can you try dumping the directory at the beginning of `get_cert_chain()` to see if it is in the right path?

**Comment by marmarko** [comment]
Seeing the same issue

**Comment by marmarko** [comment]
@juwlee getting this error OpenSSL::X509::StoreError·system lib even when we deploy to Heroku. Any ideas?

**Comment by adriansanmigel** [comment]
Hey I realize the odds and ends I am sowing right not. With above mentions spider ,but all your absolutes are your let goes. Accelarator info, and data.  Download something. If you contact me call ny phone I will tell you. Or mirror my PC. talk no messages

**Comment by juwlee** [comment]
@marmarko I am unfortunately not able to recreate the issue but can you check if @Zmokizmoghi 's workaround above works?

**Comment by marmarko** [comment]
@juwlee not sure how to attack this one. Has this functionality tested for in the gem tests? It seems that the certificates are just not referenced correctly in any environment. Is there a more robust way to specify the path to certificates inside the gem?

**Comment by juwlee** [comment]
@marmarko can you run these tests? As @Zmokizmoghi reported, it seems to run on some environments while does not on some others. I cannot seem to recreate the issue, so it would be great if you could provide debugging information.

```
10:39:10-juwlee@LM-AUN-00874679:~/workspace/public/PayPal-Ruby-SDK$ bundle exec rspec spec/webhooks_examples_spec.rb:45/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local/lib in PATH, mode 040777
Run options:
  include {:locations=>{"./spec/webhooks_examples_spec.rb"=>[45]}}
  exclude {:disabled=>true, :integration=>true}

Webhooks
  Validation
    verify common name
    verify get expected signature
    verify expiry
    verify cert chain
    verify

Finished in 1.34 seconds (files took 1.06 seconds to load)
5 examples, 0 failures
```

**Comment by marmarko** [comment]
@juwlee when i clone the repo locally and run rspec, all tests pass. I think the issue is that when it runs as a gem, it's not able to reference the files. Have you tried including this gem in a project and running this?

PayPal::SDK::REST::WebhookEvent.verify(transmission_id, timestamp, webhook_id, event_body, cert_url, actual_signature, auth_algo)

**Comment by GMMan** [comment]
Here's how [Coinbase's SDK handles making the correct path](https://github.com/coinbase/coinbase-ruby/blob/master/lib/coinbase/wallet/api_client.rb#L713):

```
def self.callback_signing_public_key
  @@callback_signing_public_key ||= nil
  return @@callback_signing_public_key if @@callback_signing_public_key
  path = File.expand_path(File.join(File.dirname(__FILE__), 'coinbase-callback.pub'))
  @@callback_signing_public_key = OpenSSL::PKey::RSA.new(File.read(path))
end
```

They do it by expanding the path of the currently executing file and substituting the key path relative to that. This works whether the code's dropped into a project or installed as a gem.

**Comment by bluk** [comment]
@GMMan Thanks for the info. Looking to see if a similar fix can be made.

**Comment by adriansanmigel** [comment]
meta
