### ISSUE TITLE
Items are not saved after transaction is approved

### ISSUE THREAD

**Issue by jakubstraka** [paypal/PayPal-Ruby-SDK#171]
i'm working with Sandbox at this moment and have a problem to get `items` from `item_list` after the payment is approved.

During the whole process I can see in the console the content of the `items` but when I look back for a payment then `items` is just empty array (other values are correct).

Any thoughts/suggestions?

---
````ruby
@payment = PayPal::SDK::REST::Payment.new({
      :intent =>  "sale",
      :payer =>  {
        :payment_method => "paypal" },
      :redirect_urls => {
        :return_url => "http://localhost:3000/execute-order",
        :cancel_url => "http://localhost:3000/" },
      :transactions =>  [{
        :item_list => {
          :items => current_cart.items_array },
        :amount => {
          :total => sprintf('%.2f', current_cart.total_price),
          :currency => "EUR" },
        :description => "This is the payment transaction description." }
        ]
      }
    )
````
---
````ruby
def items_array
  res = []
  self.products.each do |product|
    p = Hash.new
    p[:name] = product.full_name
    p[:description] = product._type
    p[:price] = sprintf('%.2f', product.price * self.total_multiplier)
    p[:currency] = "EUR"
    p[:quantity] = "1"
    res << p
  end
  res
 end
````
---

**Comment by juwlee** [comment]
Hi @jakubstraka have you tried `curl` with the same request? Does it show the same issue?

**Comment by jakubstraka** [comment]
Hi @juwlee, yes, `curl` returns empty `items` as well.

**Comment by juwlee** [comment]
Thanks for verifying @jakubstraka . I would suggest that you reach out to [Paypal MTS](https://www.paypal-techsupport.com/app/ask/session) as it is associated with API rather than this SDK. I will close this issue now.
