### ISSUE TITLE
Add USPS tracking number to charge?

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-Ruby-SDK#174]
We've been talking to PayPal and seems like you guys really want us to add the USPS tracking number to our transactions. So how would I go about adding that to a transaction?

**Comment by holgersindbaek** [comment]
Is there anyone out there who has encountered this issue? Any help to get? Is this even possible?

**Comment by juwlee** [comment]
@holgersindbaek once you receive money for goods, we put a prompt in the account that allows them to enter the tracking number that will then be sent to the buyer.

**Comment by holgersindbaek** [comment]
I understand it can be done manually. What I'm asking for, is a programattic way to do it! 
We've been talking with the guys at PayPal and they really want us to put the tracking ID in. So how do we do that programmatically?!

-- 

All the best

Holger Sindbaek · HolgerSindbaek.com




On Tue, Dec 29, 2015 at 8:07 AM -0800, "Juwon Lee" <notifications@github.com> wrote:












Closed #174.

**Comment by ppmtscory** [comment]
There isn't a way to do this programmatically at the moment.  You can file a ticket with our [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) team and they will be able to track the feature request accordingly.

**Comment by holgersindbaek** [comment]
We've been talking with your support team on the phone and it really sounds like they want us to add the tracking ID to every single sale people make on PayPal. We make around 15-20 sales and growing a day on PayPal. It's an immensely big hassle for us, if we can't do this programatically. You sure there's no way around this?!

**Comment by ppmtscory** [comment]
We may automatically attach it, if you buy the shipping label through PayPal (web flow), but that would be the only way that I know of.  I'm not aware of any variables in any of the APIs that would allow the addition of tracking to a transaction.  This would need to happen before anything could be added to the SDKs.  Please continue to work with the [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team on this feature enhancement.
