### ISSUE TITLE
Build Failing on Travis

### ISSUE THREAD

**Issue by jethroo** [paypal/PayPal-Ruby-SDK#178]
currently the build is failing due to some ssl errors 

On Travis:
```
$ bundle exec rspec --tag unit

/home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)

	from /home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	....
	from /home/travis/build/paypal/PayPal-Ruby-SDK/lib/paypal-sdk/rest/data_types.rb:1260:in `get_cert'
```
~~Locally 5 test are failing all with kind of the same message~~
used the wrong ruby version(ruby-1.9.3-p547), ruby-2.2.0 and above works fine locally

**Comment by juwlee** [comment]
@jethroo thanks for reporting. Indeed, the requirements changed a bit (please see [here](https://github.com/paypal/PayPal-Ruby-SDK#prerequisites) due to `TLS 1.2` support. It should run on Ruby >= 2.0.0.

**Comment by jethroo** [comment]
@juwlee but your build is failing on travis still, sorry maybe I created confusion with my last  part of the report which just is intended to state that I can't reproduce it locally ;)

**Comment by juwlee** [comment]
Thanks for clarification @jethroo . I will take a look.

**Comment by juwlee** [comment]
@jethroo it has been resolved (see [here](https://travis-ci.org/paypal/PayPal-Ruby-SDK/builds/105606985)). Thanks again for letting us know!
