### ISSUE TITLE
Correct way to access IPN Module for validation

### ISSUE THREAD

**Issue by krsyoung** [paypal/PayPal-Ruby-SDK#179]
I'm looking to use this library to help process an IPN payment.  I have the following in my controller and was curious if it is actually supported and if this is the right way to get at it:

     if PayPal::SDK::Core::API::IPN.valid?(request.raw_post)
       # to stuff with the params
     end

If yes I'll update http://stackoverflow.com/a/21174859/851145 as it seems to be about the only reference of an official PayPal library way to do this for Ruby.

**Comment by juwlee** [comment]
@krsyoung actually, IPN is used in classic APIs. In REST, please use [webhooks](https://github.com/paypal/PayPal-Ruby-SDK/blob/v1.4.2/lib/paypal-sdk/rest/data_types.rb#L1338) The classic code base will be removed in the next release.

**Comment by krsyoung** [comment]
Thanks for the info @juwlee :+1:.  I'll investigate moving over to webhooks.
