### ISSUE TITLE
unknown SSL method `TLSv1_2'.

### ISSUE THREAD

**Issue by BrunoAwdd** [paypal/PayPal-Ruby-SDK#180]
I'm having this error when trying to connect to authenticate to the server. I'm developing locally, and do not know what else to do.

**Comment by bluk** [comment]
What is your environment (Ruby version, OpenSSL version, etc.)?

You need to upgrade your environment to use a fairly recent (preferably latest) version of OpenSSL and Ruby >=2.0.0. Please see the [PayPal TLS Update site](https://github.com/paypal/TLS-update#ruby) for more information. If you still have questions, please leave a comment. Thanks.

**Comment by hkmaly** [comment]
Patching the ruby with https://garajau.com.br/2015/07/tls-1-1-and-1-2-support-for-ruby-1-9-3 might also work. I mean, it solves this problem, not sure if there is any other reason to use Ruby >= 2.0.0
