### ISSUE TITLE
PayPal 500 on payment capture

### ISSUE THREAD

**Issue by davidflores2** [paypal/PayPal-Ruby-SDK#181]
We are trying to capture a payment that was authorized before and are getting a 500 response from PayPal. This is what we get back. 

`PayPal::SDK::Core::Exceptions::ServerError (Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = 54dc7eb12c6ec.):`

Any clue what it is?

**Comment by pp-randy** [comment]
@davidflores2 To me this looks like a possible system. Can you please reach out to PayPal Technical Support here? https://www.paypal-techsupport.com/app/ask/

**Comment by davidflores2** [comment]
@pp-randy we did this. Waiting for a response. Thanks!

**Comment by pp-randy** [comment]
@davidflores2 What is your ticket number?

**Comment by davidflores2** [comment]
Ref # #160202-000202

**Comment by pp-randy** [comment]
Closing this issue, looks like Tech Support figured this out (total in amount missing) and is following up with you otherwise.
