### ISSUE TITLE
Refund a capture

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-Ruby-SDK#185]
I'm trying to refund a capture, but I'm getting the following error:

    2016-02-25T22:46:12.388536+00:00 app[worker.1]: wrong number of arguments (0 for 1)
    2016-02-25T22:46:12.388599+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/paypal-sdk-rest-1.3.3/lib/paypal-sdk/rest/data_types.rb:762:in `refund'

This is my capture refund code:

    capture = Capture.find(@transaction.paypal_capture_id)
    capture.refund

I'm guessing that i need to pass in the amount I want to refund, like you do in your example:

  @capture = Capture.find("7YR91301C22810733")
  @refund  = @capture.refund({
    :amount => {
      :currency => "USD",
      :total => "0.01" }
  })

Issue is that I want to refund the whole capture and I don't necessarily know how big the capture was. When I'm refunding sales, I can do the following:

    sale = Sale.find(@transaction.paypal_charge_id)
    sale.refund

Why can't I do the same with captures? Can I refund the whole amount using the authorization ID I used to capture the authorization?

**Comment by ppmtscory** [comment]
@holgersindbaek I am testing this and will respond back here afterwards.....

**Comment by ppmtscory** [comment]
@holgersindbaek I'm not able to reproduce your issue.  You are allowed to pass through an empty payload.  Make sure you're passing an empty payload instead of simply no payload whatsoever.  Below is what I used in the Sample code to complete the refund of a capture.
```
@capture = Capture.find("3SH46868NP745082M")
@refund = @capture.refund({})
```

**Comment by holgersindbaek** [comment]
Aha... I wasn't passing anything in the payload. And what about refunding a sale. I can successfully refund a sale without passing a payload along - @sale.refund - why is that possible, but it's not with a capture?

**Comment by ppmtscory** [comment]
I'm not able to reproduce that either.... I get the same error when I try to refund a sale with no payload included.  I have to do the same `@refund = @sale.refund({})` for it to complete successfully.

**Comment by holgersindbaek** [comment]
Ok... thank you very much for he clarification... and I'm guessing it will refund the full amount if no payload is included, right?

**Comment by ppmtscory** [comment]
That is correct - empty payload == full refund.

**Comment by holgersindbaek** [comment]
Ok. Thanks again.
