### ISSUE TITLE
Shifting transaction fees to payer

### ISSUE THREAD

**Issue by farnoy** [paypal/PayPal-Ruby-SDK#187]
I'm trying to figure out how to send invoices with PayPal fees included so that my account receives the desired amount. Billing from a US account and knowing if the recipient is from the US or not, I could charge an extra 2.9% + $0.30 or 3.9% + $0.30 for international recipients but it seems fragile. I know I can check the paid fees by looking at the sale object but it's too late then to use that information. Is there a better way of shifting transaction fees to the payer?

**Comment by pp-randy** [comment]
For invoicing I am not aware of a way.  You could possibly collect the country of the account using Log In With PayPal (Identify) service, but it would require the payer to log in, or a form you create.    

Some considerations charging extra to cover the fee would raise the overall fee.  However, if you can determine the average of the fees, you could consider charging everyone evenly and raising the amount evenly for all your invoices regardless of country. 

Adaptive Payments currently is the only option I am aware of that lets you specify the fees payer.
