### ISSUE TITLE
Paypal Internal Service Error

### ISSUE THREAD

**Issue by maximus242** [paypal/PayPal-Ruby-SDK#188]
I am getting a Paypal 500 Internal Service Error using both the samples provided with rack and with my own application. This was not happening before. It occurs using both my own API credentials and the ones provided by paypal in the samples file. They worked previously.

Debug id: 4167f37435ec4

Using the SDK sample code I am getting Debug Id: 4370bd0783

**Comment by ppmtscory** [comment]
@maximus242 I'm assuming this is for the sandbox environment?  We're currently experiencing some issues at the moment, with the sandbox, so I'll update here once those are resolved.

**Comment by flori** [comment]
I am having the same problem (debug id: 2a861c2af6f9). Only the sandbox system seems to be affected.

**Comment by jcleblanc** [comment]
Hi all, sandbox appears to be experiencing some downtime. We're tracking the issue over at https://github.com/paypal/PayPal-PHP-SDK/issues/531, so I'm going to close this one as a duplicate so that we don't have multiple threads. We'll provide back information as we can there.
