### ISSUE TITLE
Internal Server Error - Payout.

### ISSUE THREAD

**Issue by nsantiago2719** [paypal/PayPal-Ruby-SDK#190]
I'm having a `Failed. Response code = 500. Response message = Internal Server Error.` error while creating a payout. I have almost the same code on your samples by the way. I have seen some of your issues but it doesn't solve my problem. I don't know if this is the debug ID that your talking about on some of the issues `PayPal-Request-Id: 874d1231-bb9b-4dc2-8db0-09ac0ff5a715`

**Comment by juwlee** [comment]
Hi @nsantiago2719 , it seems sandbox is experiencing some downtime. We're tracking the issue over at paypal/PayPal-PHP-SDK#531. We will close this one as a duplicate so that we don't have multiple threads.
