### ISSUE TITLE
De-authorizing future payment?

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-Ruby-SDK#191]
Is this possible? My users are authorizing future payments from my iOS app using this code - https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md - and now I want them to have the possibility to de-authorize future payments as well. How would I go about that?

**Comment by bluk** [comment]
Consumers can de-authorize the PayPal Future Payments consent by going to the PayPal website as documented in the [`Deleting consent on the paypal.com website`](https://developer.paypal.com/docs/integration/mobile/make-future-payment/). There are some other requirements for telling how customers can do this in your app/web site.

In the app, you will have to develop a flow to delete the access/refresh tokens on your server to de-authorize the user. There is no public API call that you can make currently to "de-consent".
