### ISSUE TITLE
What is the point of non-working defaults ?

### ISSUE THREAD

**Issue by alexey** [paypal/PayPal-Ruby-SDK#194]
in rails console:
`2.2.2 :014 > PayPal::SDK.configure`
Return:
`#<PayPal::SDK::Core::Config:0x007fca3e2a9300 @client_id="", @client_secret=nil, @mode="sandbox", @app_id="APP-80W284485P519543T", @username="jb-us-seller_api1.paypal.com", @password="WX4WTU3S8MY44S7F", @signature="AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy", @sandbox_email_address="Platform.sdk.seller@gmail.com", @ssl_options={}>
`

**Comment by juwlee** [comment]
@alexey See [SDK config guide](https://github.com/paypal/PayPal-Ruby-SDK#configuration). If you do not have an account, you would probably need to set up your own one (either sandbox or live) and either 1) put it in a config file or 2) set it as shown in the docs.
