### ISSUE TITLE
Paypal security updates

### ISSUE THREAD

**Issue by gustavoschmidt** [paypal/PayPal-Ruby-SDK#202]
Today I received an email from Paypal about security updates. 
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1913&viewlocale=en_US

Do you guys think we should update the gem to accommodate these changes?
I don't know the inner workings of the SDK, but I'd happily help.

Best

**Comment by bluk** [comment]
@gustavoschmidt The latest version of the Gem should be compatible with the TLS updates. You can find more specific information for this SDK at the [PayPal TLS repository](https://github.com/paypal/TLS-update#ruby) and what is required for your environment to upgrade.

If you find an issue or have a specific question, please feel free to add a comment or open a new issue. Thanks!
