### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Ajmal** [paypal/PayPal-Ruby-SDK#208]
Can I create subscription with this sdk?

**Comment by jrasanen** [comment]
https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/subscription_examples_spec.rb

**Comment by Ajmal** [comment]
@jrasanen thanks

**Comment by jrasanen** [comment]
@Ajmal I've just finishing implementing this with Ruby. If you have any questions, I can try answering to them. Feel free to ask on Twitter (jussiras) or by Skype (jussi.rasanen).

Only thing I haven't yet figured out is that where does PayPal ping after a successful monthly payment. :|
