### ISSUE TITLE
WebProfile.flow_control.user_action

### ISSUE THREAD

**Issue by zverok** [paypal/PayPal-Ruby-SDK#211]
So, docs have setting for payment experience profile, named `user_action`:  https://developer.paypal.com/docs/api/payment-experience/#definition-flow_config

There is nowhere to be seen acceptable values for it. And Ruby SDK doesn't implement it (as well as PHP one, for example). I've tried to add the field in my local gem copy, it was saved successfully (I've used "commit" string), but it seems to be absolutely ignored while creating payment ("Continue" instead of "Pay Now").

The only "official" way of immediate payments in REST API is "add useraction=commit" to approval URL manually (https://github.com/paypal/PayPal-Ruby-SDK/issues/104#issuecomment-79128798), am I right? With no docs, no helper methods, and misleading ghost field in API docs on paypal.com? Or am I missing something?

**Comment by pp-randy** [comment]
@zverok sorry for the delay.  Looking through some internal documentation that value should be commit, but this isn't working so I will need to follow up internally on this.  

It seems the URL change is the current working way to do this.

**Comment by pp-randy** [comment]
For internal tracking SRE-42281

**Comment by zverok** [comment]
Thanks. I really hope the things will became better with time...

**Comment by pp-randy** [comment]
@zverok the functionality has been added.  
user_action=commit 
In your Payment Experience should work as intended now.
