### ISSUE TITLE
Getting tokeninfo from authorization code throws 400 error.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [paypal/PayPal-Ruby-SDK#217]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): b589f6ebd5ba6, be250bb93e117.
- Version of Ruby used: 2.3
- SDK Version:  1.4.8

### Issue Description

Hello. I have created business account in PayPal and added sandbox application. Then I have checked **Login with PayPal** option.

In my rails project I have added my `client_id`, `client_secret`, `username`, `password`, `signature`. APP ID I have left with `APP-80W284485P519543T`.

In my android applicaiton, I have added Android SDK with same `client_id`. When in android I have logged in, I have received this message:

    "response": { 
          "code":"mock_code_EJhi9jOPswug9TDOv93qg4Y28xIlqPDpAoqd7biDLpeGCPvORHjP1Fh4CbFPgKMGCHejdDwe9w1uDWnjPCp1lkaFBjVmjvjpFtnr6z1YeBbmfZYqa9faQT_71dmgZhMIFVkbi4yO7hk0LBHXt_wtdsw"
     },
    "client": {
        "platform": "Android",
        "paypal_sdk_version": "2.14.4",
        "product_name": "PayPal-Android-SDK",
        "environment": "mock"
     },
         "response_type": "authorization_code"
    }

I take this `code` and try to get refresh token from my ruby sdk:

    tokeninfo = Tokeninfo.create('mock_code_EJhi9jOPswug9TDOv93qg4Y28xIlqPDpAoqd7biDLpeGCPvORHjP1Fh4CbFPgKMGCHejdDwe9w1uDWnjPCp1lkaFBjVmjvjpFtnr6z1YeBbmfZYqa9faQT_71dmgZhMIFVkbi4yO7hk0LBHXt_wtdsw')

This throws me this error:

    PayPal::SDK::Core::Exceptions::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.  Response debug ID = b589f6ebd5ba6, be250bb93e117.
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paypal-sdk-rest-1.4.8/lib/paypal-sdk/core/util/http_helper.rb:135:in `handle_response'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paypal-sdk-rest-1.4.8/lib/paypal-sdk/core/util/http_helper.rb:78:in `http_call'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paypal-sdk-rest-1.4.8/lib/paypal-sdk/core/api/base.rb:86:in `api_call'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paypal-sdk-rest-1.4.8/lib/paypal-sdk/core/api/base.rb:98:in `post'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paypal-sdk-rest-1.4.8/lib/paypal-sdk/core/openid_connect.rb:71:in `create_from_authorization_code'
	from (irb):3
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'

Why this is happening?

**Comment by bluk** [comment]
It seems your Android application is in `mock` mode which doesn't really interact with sandbox or issue server traffic. The response authorization code is just a mocked response so when you try to send it to the sandbox server environment, it doesn't recognize the code.

See the [sample app where it sets the environment](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/main/java/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L64) and change it to `PayPalConfiguration.ENVIRONMENT_SANDBOX`

**Comment by bluk** [comment]
If this is still an issue, please leave a comment or open a new issue. Thanks.
