### ISSUE TITLE
PayPal Pro Ruby SDK and Recurring Payments with credit card ?

### ISSUE THREAD

**Issue by CirrusThink** [paypal/PayPal-Ruby-SDK#218]
### General Information
- Mode (Sandbox/Live): sandbox
- PayPal-Debug-ID(s) (from any logs): 
- Version of Ruby used: 2.0.0
- SDK Version: 
### Issue Description

Is it possible with Ruby SDK to create a recurring payment with the PayPal Business PRO account ?
I am able to perform the recurring method in activemerchant and I see samples to perform with ruby merchant sdk, but cant find anything in the ruby rest sdk ?

**Comment by sankarbhavanib** [comment]
This is the closest we have at this point of time ‘https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/subscription_examples_spec.rb'. We are working on adding more samples and I will keep you notified once those are made available.

**Comment by kaiomagalhaes** [comment]
no news @sankarbhavanib ?

**Comment by jaypatel512** [comment]
As @sankarbhavanib mentioned, we have a sample to demonstrate how to use PayPal Billing Agreement (Subscription APIs), to create a recurring payments. 

For more information on that API, please read [Billing Plans](https://developer.paypal.com/docs/api/payments.billing-plans) and [Billing Agreements](https://developer.paypal.com/docs/api/payments.billing-agreements).
