### ISSUE TITLE
PayPal::SDK::Core::Exceptions::ServerError - Failed.  Response code = 500.  Response message = Internal Server Error.

### ISSUE THREAD

**Issue by tballarin** [paypal/PayPal-Ruby-SDK#222]
### General Information

- Mode (Sandbox/Live): Sandbox
- Version of Ruby used: 2.2.4p230
- Rails version : 5.0.0
- SDK Version: gem v - 1.4.9

### Issue Description

Hello all,
I get an error on @payment.execute()

`   @payment = Payment.new({
                               :intent =>  "sale",
                               :payer =>  {
                                   :payment_method =>  "paypal"
                               },
                               :redirect_urls => {
                                   :return_url => @website_config_opts["paypal_return_url"],
                                   :cancel_url => @website_config_opts["paypal_cancel_url"]
                               },
                               :transactions =>  [{
                                    :item_list => {
                                        :items => items
                                    },
                                    :amount =>  {
                                        :total =>  totCart,
                                        :currency =>  "EUR",
                                        :details =>{
                                          :subtotal => subTotalCart,
                                          :shipping => deliveryCost
                                         }
                                    },
                                    :description =>  ""
                                }]
                           })`

After I redirect user to => redirect link
User enter is account info and make payment

On my callback controller : 

`@payment = Payment.find(params[:paymentId])
    if @payment.execute(:payer_id => params[:PayerID])
      Rails.logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      Rails.logger.debug "Payment[#{@payment.id}] execute successfully"
      Rails.logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      Rails.logger.debug @payment
      Rails.logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    else
      Rails.logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      Rails.logger.debug @payment.error.inspect
      Rails.logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    end`

But on each test I get the => PayPal::SDK::Core::Exceptions::ServerError - Failed.  Response code = 500.  Response message = Internal Server Error.

Thanks in advance for your help

**Comment by bluk** [comment]
This error should have been fixed in sandbox. If this error still occurs, please leave a comment. Thanks!

**Comment by anand-rajput** [comment]
It is still present 
[Rollbar] Reporting exception: Failed.  Response code = 500.  Response message = Internal Server Error.
[Rollbar] Exception not reported because Rollbar is disabled

PayPal::SDK::Core::Exceptions::ServerError (Failed.  Response code = 500.  Response message = Internal Server Error.):
