### ISSUE TITLE
Get Internal Server Error

### ISSUE THREAD

**Issue by antprt** [paypal/PayPal-Ruby-SDK#223]
Hi,

I'm getting an Internal Server Error when I create a payment.

The response is always: 

PayPal::SDK::Core::Exceptions::ServerError (Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = ec71dea1380a6, ec71dea1380a6.)

Is sandbox mode. 

Is there any problem with paypal?

**Comment by pp-randy** [comment]
There was a sandbox issue earlier which should now be resolve. 

Closing issue for now.  If the error continues please provide a new response log.
