### ISSUE TITLE
Getting internal service error in sandbox mode

### ISSUE THREAD

**Issue by sureshaluka** [paypal/PayPal-Ruby-SDK#224]
Error code : 500 with response : {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"d0e8fa20ac516"}

**Comment by pp-randy** [comment]
@sureshaluka can you try again?  This looks like it was a sandbox issue, but my attempts are working now.

**Comment by pp-randy** [comment]
Closing the issue for now as the 500 issue should be resolve.  Reply back if the error persists for you and provide a new response string.
