### ISSUE TITLE
Keep getting "internal service error occurred" in LIVE mode for /v1/payments/payment

### ISSUE THREAD

**Issue by dmitrypol** [paypal/PayPal-Ruby-SDK#226]
### General Information

- Mode (Sandbox/Live): LIVE
- PayPal-Debug-ID(s) (from any logs): 8366626d1dfec, 96508397440e0, 4a17fd7bd5db5
- Version of Ruby used:  2.3.1p112 
- SDK Version: paypal-sdk-rest (1.4.8)

### Issue Description

This works in Sandbox mode (with sandbox creds) but NOT in Live mode (with correct creds which I tested).

Here is the snippet from the response:
"body": {
"message": "An internal service error occurred.",
"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
"name": "INTERNAL_SERVICE_ERROR",
"debug_id": "8366626d1dfec"
},

**Comment by bluk** [comment]
I've opened PPPLPAYPT-12064 to track this issue, but I strongly advise also requesting support from [PayPal Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) in case there are account specific issues.

**Comment by dmitrypol** [comment]
bluk - thank you for quick response.  Is there a portal where I can access PPPLPAYPT-12064 to check it's status?  I also filed https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1290933 ticket with this info.

**Comment by bluk** [comment]
@dmitrypol Unfortunately, no public portal. Having an official issue opened via the PayPal Support website is the best way to get contacted about status and to ensure that your issue is resolved.

**Comment by dmitrypol** [comment]
@bluk  - I understand.  Any idea what the ETA is for the resolution?

**Comment by bluk** [comment]
Sorry, I don't know of an ETA, but the issue is actively being investigated.

**Comment by snovity** [comment]
@bulk around the time @dmitrypol opened the issue, we started getting exceptions from SDK for POST calls to `v1/payments/payouts`. It is always one of the 
*  `Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = d7e4174aecfaf`
*   `Failed. Response code = 503. Response message = Service Unavailable. Response debug ID = f8d1520ceb51`

Especially nasty is that despite server responding with 500 or 503, sometimes payouts are successful. Even worse, there is no way to list all payouts via REST API and programmatically cross check the states with our internal transactions...

**Comment by snovity** [comment]
I've also filed an incident report https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1292347

**Comment by drewfg** [comment]
I am also have the same issue, started about a week ago. Filed incident report https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1294625

**Comment by dmitrypol** [comment]
My issue was with the account setup but the message was extremely confusing.  Finally got through to the tech support (long wait on the phone) and they fixed the account config.

**Comment by bluk** [comment]
Sorry for the troubles. It seems this was an account specific error so if anyone else also encounters this error, please open an issue with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/home).
