### ISSUE TITLE
CurrencyConversion

### ISSUE THREAD

**Issue by danielwestendorf** [paypal/PayPal-Ruby-SDK#228]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of Ruby used:
- SDK Version:

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

CurrencyConversion is partially described [here](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/api/data_types/base.rb#L10-L15), yet it isn't included as a data type. 

Are there any resources on how to translate [API documentation](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/ConvertCurrency_API_Operation/) into a working example?

**Comment by bluk** [comment]
You may want to look at https://github.com/paypal/adaptivepayments-sdk-ruby/blob/4b4a4317921869b9e836eb09358c6b1386940669/spec/convert_currency_spec.rb which is a spec for the [adaptivepayments-sdk-ruby](https://github.com/paypal/adaptivepayments-sdk-ruby) which is probably what you want.

**Comment by SaimonL** [comment]
I did something like this:

```ruby
pp = PayPal::SDK::REST::CurrencyConversion.new
pp.from_currency = 'USD'
pp.from_amount = 1000.00
pp.to_currency = 'CAD'
pp.to_amount = 1.0
```

Now I don't know the last step on how to call PayPal to get the response.

**Comment by xiaoleih41** [comment]
There's no currency conversion API in REST API set. Are you using adaptive payment API?

**Comment by SaimonL** [comment]
Oh sorry, I thought this gem had it by looking at the source code. Please disregard the post above.
