### ISSUE TITLE
Plan.find returns Internal Service Error 500 in Live Mode

### ISSUE THREAD

**Issue by mattLummus** [paypal/PayPal-Ruby-SDK#230]
### General Information

- Mode (Sandbox/Live): LIVE
- PayPal-Debug-ID(s) (from any logs): c33337e4e415a, b91159f629b16, 685d37a093f4f
- Version of Ruby used: 2.3.0
- SDK Version: 1.4.7

### Issue Description
About 12-15 hours ago we started seeing issues with new users of ours trying to sign up with PayPal. After going through our error logs we traced it to a certain line in our codebase.

During the process of creating an agreement we attempt to retrieve an associated plan: `::Plan.find(plan_id)`

PayPal::SDK::Core::Exceptions::ServerError: Failed. Response code = 500. Response message = Internal Server Error

**Comment by bluk** [comment]
If this is still occurring (or if you encounter any other live errors), please open an issue with [Merchant Technical Support](https://www.paypal-techsupport.com). I've followed up with an internal ticket PPPLPAYPT-12464 to verify the error isn't happening.

**Comment by mattLummus** [comment]
@bluk This is not still occurring but this is the first response we've heard from PayPal in just short of a week (including still never hearing back from PayPal tech support which we had already filed that day) and I've seen a number of these issues popping up in the SDK threads lately. Some amount of transparency or communication  would be nice when your services/endpoints are having failures.

**Comment by bluk** [comment]
@mattLummus Thank you for your feedback, and I agree. I'll forward your feedback on to help improve everyone's experience.
