### ISSUE TITLE
Not being able to use the subscription

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#248]
### General Information

- Mode Sandbox:
- PayPal-Debug-ID(s) (from any logs): "443cdbb4f3a64", "443cdbb4f3a64"
- Version of Ruby used: 2.3.1p112
- SDK Version: 1.5

### Issue Description

I'm not being allowed to create a subscription. It returns me a 401.

The code I'm using is from the spec folder of this project and can be found here: https://gist.github.com/kaiomagalhaes/d279fd8f9eb6fcf50e4b60c7dfa1684f

The logs can be found here:
https://gist.github.com/kaiomagalhaes/ee4205b668584296027eee71212740a8

**Comment by bluk** [comment]
There seemed to be a temporary issue with your requests. Can you please try again?

**Comment by bluk** [comment]
Seems the 401 issue was resolved for you in issue #250 but if not, please leave a comment.
