### ISSUE TITLE
Initial Payment success / failure

### ISSUE THREAD

**Issue by Kyderman** [paypal/PayPal-Ruby-SDK#249]
I have a working piece of subscription code where I charge an initial payment (to ensure a first payment is made), and then have the agreement start for the next period.

I am finding that lots of people tend to fail the initial payment, why is this happening (by fail, I mean that the state comes back as "cancelled" at which point I dont let them have access to the paid content.

Why is this?

**Comment by bluk** [comment]
Can you please contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) ? They should have access to your live account information and can help you understand the cancellation failures. Thanks.
