### ISSUE TITLE
Payment.Find returns state created after payment

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#250]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):  c2a877cc8317c, c2a877cc8317c
- Version of Ruby used: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- SDK Version: 1.5

### Issue Description

> WIth the following steps:

1. Create paypal Payment
2. Get URL
3. Pay  it with a test user provided by paypal sandbox 
4. In the call back response I get the payment ID and find it using Payment.find 
5. I check the payment state and it is: `@state="created"`

As I paid shouldn't it be approved? When I try to use Payment.execute with the payer_id it returns an 401

**Comment by bluk** [comment]
Sorry for the late response. The payment state changes to `approved` after payment execution.

Can you please post a `PayPal-Debug-ID` for when you try to execute the payment and get a 401? If you're using the right `payer_id` and payment ID, you should be able to execute the payment.

**Comment by kaiomagalhaes** [comment]
After some tentatives it started to work yesterday. It was probably an issue with my sandbox keys.
