### ISSUE TITLE
Code error while executing a paypal payment

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#251]
### General Information

- Mode (Sandbox/Live):Sandbox
- PayPal-Debug-ID(s) (from any logs): ["7b66323590a24", "7b66323590a24"],
- Version of Ruby used: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- SDK Version: paypal-sdk-rest (1.5.0)

### Issue Description

When I execute the payment I got the error:
undefined method `billing_plan_units=' for #<PayPal::SDK::REST::DataTypes::Payment:0x000000020cbde8>
Did you mean?  billing_agreement_tokens=
ArgumentError: invalid data("GE3CSP88C3B94") for PayPal::SDK::REST::DataTypes::PaymentExecution class
from /var/lib/gems/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/data_types/base.rb:126:in `merge!'

**Comment by bluk** [comment]
@kaiomagalhaes Just to be clear, are you GETting the payment (before executing) and running into this issue? Or are you seeing this error during the execute response?

**Comment by kaiomagalhaes** [comment]
The steps are:
```
I get the payment: Payment.find(id)
I execute it: Payment.find(id).execute(payer_id:id)
````
After applying this solution: https://github.com/paypal/PayPal-Ruby-SDK/pull/214

It worked fine.

**Comment by kaiomagalhaes** [comment]
@bluk one question, after executing it, should I be receiving any webhook in my sandbox accounts? Atm I'm receiving none.

**Comment by bluk** [comment]
@kaiomagalhaes I believe the web hooks should occur within 30 minutes on sandbox. If you do not see any, please open a new issue with the payment ID and the PayPal-Debug-ID for the execute. Thanks.
