### ISSUE TITLE
Express Checkout

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#256]
What kind of method is used for the Payment.create/Payment.execute flow with paypal? Is it the express-checkout?

**Comment by pp-randy** [comment]
Yes, it is using Express Checkout.

**Comment by kaiomagalhaes** [comment]
@pp-randy  any idea to why it would not send the webhooks?

**Comment by pp-randy** [comment]
Were the Payments Created with the REST API?  The REST API enables the webhooks; otherwise, you would want to use Instant Payment Notification if you are using the Classic API.

**Comment by kaiomagalhaes** [comment]
@pp-randy  the payment are being created with: https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/payment/create_with_paypal.rb

so I need to use the webhooks or the classic api?

**Comment by pp-randy** [comment]
You can use both with the REST API.  Since you are using this SDK I advise using Webhooks.  You have registered your webhook listener?  

Does the Webhook Simulator on the Dashboard at https://developer.paypal.com work to send a webhook to your listener? 

Do you see your Webhook Events at https://developer.paypal.com/developer/dashboard/webhooks/sandbox?

**Comment by kaiomagalhaes** [comment]
@pp-randy the simulator: https://developer.paypal.com/developer/webhooksSimulator/  works fine, but I don't see any events in https://developer.paypal.com/developer/dashboard/webhooks/sandbox. It is what is bugging me most, I've already configured the IPN in my sandbox account, but nothing so far.

**Comment by pp-randy** [comment]
@kaiomagalhaes I think what you are needing is to register your webhook listener using this API https://developer.paypal.com/docs/api/webhooks/#webhooks_create  

Once this is done you should start seeing webhooks in your dashboard.  

Webhooks are the more recent of the two notifications mechanisms, the classic being IPN; however, when implementing the REST API you can utilize both.

**Comment by kaiomagalhaes** [comment]
@pp-randy  YOU ARE JUST GREAT! thanks man, really really thanks!

If you ever come to Brazil let me know and I will buy you and ice cream
