### ISSUE TITLE
Is there any gem out of there that uses the classic request?

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#259]
Hey guys, I'm on brasil and here it seems we can't use the rest api, is there any gem that would allow me to get the payment url?

**Comment by ppmtscory** [comment]
@kaiomagalhaes you can have a look at our merchant SDK [here](https://github.com/paypal/merchant-sdk-ruby) for the Classic API.  There's other classic SDKs as well if you just visit github.com/paypal and search the repo list for Ruby.
