### ISSUE TITLE
any webhook is not received to our listener in Sandbox mode

### ISSUE THREAD

**Issue by kevin-jj** [paypal/PayPal-Ruby-SDK#263]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): ["b40062cc4ccf2", "b40062cc4ccf2"]
- Version of Ruby used: 2.4.0
- SDK Version: 1.6.0

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

We was not receiveing any webhook notifications to our listener as completed the payment in Sandbox but made it in Webhook simulator.

@bluk @pp-randy @ppmtscory @braebot

**Comment by pp-randy** [comment]
@kevin-jj did you start getting the webhooks?

**Comment by kevin-jj** [comment]
@pp-randy yes, we got it.  Thanks for your quick feedback.

The Webhook notifications seems to be delayed to our listener  by about 3-4 minutes.

In addition,  the example of "verify_webhook_event" function in the gem need to be improved further and fix bug.
