### ISSUE TITLE
chained payment

### ISSUE THREAD

**Issue by dcalixto** [paypal/PayPal-Ruby-SDK#265]
### General Information

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of Ruby used:
- SDK Version:

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

can i make chained payment with PayPal-Ruby-SDK istead of using adaptivepayments-sdk-ruby?

**Comment by pp-randy** [comment]
Unfortunately, not at this time. We are tracking the feature request for adaptive payment support here: https://github.com/paypal/PayPal-iOS-SDK/issues/9

You have some possible options with this SDK.  If you are the primary receiver you could combine a payment with a payout and achieve a similar result.  If you are a secondary receiver you could consider submitting an invoice to the primary receiver if you are charging for a service.

**Comment by pp-randy** [comment]
Closing this issue for now, let me know if you have further questions.
