### ISSUE TITLE
How to dont place the funds on hold

### ISSUE THREAD

**Issue by Kitton** [paypal/PayPal-Ruby-SDK#267]
Looks like it's possible to achieve with orders - https://developer.paypal.com/docs/integration/direct/payments/create-process-order/ .

I've tried to do this with the following code - 
```
require 'paypal-sdk-rest'
include PayPal::SDK::REST

payment = Payment.new({intent: 'order', 
	payer: {payment_method: 'paypal'}, 
	redirect_urls: {return_url: 'https://www.google.es/?gfe_rd=cr&ei=PUOTWJvrFMup8weRhoXgDw#q=return', cancel_url: 'https://www.google.es/?gfe_rd=cr&ei=PUOTWJvrFMup8weRhoXgDw#q=cancel'}, 
	transactions: [{amount: {total: '10000', currency: 'EUR'}}]})

payment.create
# redirect user to payment.approval_url
```
User has only card connected with less than 10k on it (Sandbox mode) and receives an error message 
```
Lo sentimos, pero no podemos completar la compra en este momento.
Vuelva al vendedor y elija otra forma de pago.
```
The question - Is it possible to create an order for amount more than user has on it's account and later charge the user a few times with different amount(up to the total amount in sum)?

**Comment by pp-randy** [comment]
I think it would fail if you are trying to create an amount higher than the balance. Does this fail against a sandbox account that has a bank account associated to it?  

There might be some country specific settings as well, but a regional customer support team would be better able to answer any country limitations.
