### ISSUE TITLE
INVALID_RESOURCE_ID using previous returned ID

### ISSUE THREAD

**Issue by amedrz** [paypal/PayPal-Ruby-SDK#273]
### General information

* SDK/Library version: 1.6.0
* Environment: production
* `PayPal-Debug-ID` values: "53db75c9346e8", "53db75c9346e8"
* Language, language version, and OS: Ruby 2.3.0, OS X.

### Issue description

I'm confused why I can't find a Payment with an ID previously returned after a `.create` action using this same library:

```
PayPal::SDK::REST::Payment.find('PAY-XXX')
Request[get]: https://api.paypal.com/v1/payments/payment/PAY-XXX
Request.body=null	request.header={"Authorization"=>"Bearer A101.XXX", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.0 (paypal-sdk-core 1.6.0; ruby 2.3.0p0-x86_64-linux;OpenSSL 1.0.1f 6 Jan 2014)"}
Response[404]: Not Found, Duration: 0.469s
Response.body={"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"53db75c9346e8"}	Response.header={"date"=>["Thu, 23 Mar 2017 00:20:24 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["53db75c9346e8", "53db75c9346e8"], "content-language"=>["*"], "http_x_pp_az_locator"=>["dcg11.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DLIVE5.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D3356808024%26HTTP_X_PP_AZ_LOCATOR%3Ddcg11.slc; Expires=Thu, 23 Mar 2017 00:50:24 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["185"], "cache-control"=>["max-age=0, no-cache, no-store, must-revalidate"], "pragma"=>["no-cache"], "connection"=>["close"], "content-type"=>["application/json"]}
```
I couldn't find in the documentation why would that happen beyond it just "doesn't exist"... Like, that's expected to happen with rejected payments or something... Can you please give me some guidance?

Thanks in advance.

**Comment by pp-randy** [comment]
Are you able to get a correlation id for the create as well?  

I've seen this if you've created a Payment with one REST App and trying access with a different REST App. You are using the same REST App credentials for everything?

**Comment by amedrz** [comment]
Hey, thanks for replying.

Not sure what do you mean by correlation id, can you elaborate on that please?

I can confirm that those were created with the same credentials, on production.

This is very weird. A very significant amount of the payments we've tried to process doesn't exist anymore on Paypal... 

Under which circumstances Paypal would delete them?

**Comment by pp-randy** [comment]
This is called debug-id on rest instead of correlation id, so I apologize for asking for the wrong field.  I did further digging and found the payment request for the 404 you are getting.   

When you get a completed and successfully executed payment does the lookup work for you?  I noticed this particular one failed to execute.

I will follow up further my guess is that they do not last longer than a day if the payment is never completed.

**Comment by amedrz** [comment]
Ah, got it. Unfortunately I cannot get the debug-id for the creates... I'll start storing it from now on.

I can confirm all the payments we have set as _approved_ do exist in Paypal. What you said makes sense now.

I'll appreciate a lot if we can confirm that, I couldn't find related information in the docs.

**Comment by pp-randy** [comment]
What I can tell you about the lookup is that the minimal amount of time by default is 3 hours, that is how long you have from create to execute normally.  

If you do need further troubleshooting it isn't horrible to store the debug-id, for a success API call though its found in the headers.
