### ISSUE TITLE
Payment not adding to the Paypal balance

### ISSUE THREAD

**Issue by amitej1** [paypal/PayPal-Ruby-SDK#274]
I was able to create a payment successfully to the Paypal account, but it does not add to balance on the account. 
I can see the payments in payments received, but still cannot see any additions to the balance on my account.

**Comment by pp-randy** [comment]
Is this in sandbox?  Can you give me a transaction id from one of the payments created or the sandbox account email address (if sandbox).

**Comment by amitej1** [comment]
Yes this is in Sandbox mode:

amitejkalra-facilitator@poplify.com
Transaction ID - ID4418848667260551E

**Comment by pp-randy** [comment]
I am seeing the same thing on the account, transactions look good but are not increasing the balance; this is most likely a delay in the history log in sandbox. I will see if I can reproduce with a different account.

**Comment by amitej1** [comment]
Ok Cool. Do let me know as soon as you find more. Just to add to this, when I made the payment using the Activemerchant gem, it went through to the balance immediately. So, I do think it is something to do with SDK.

**Comment by pp-randy** [comment]
Try a randomly generated card number, we see issues with the overused cards in sandbox. 

You can create a random card at the bottom of this FAQ https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

**Comment by amitej1** [comment]
if i do try to use one of the test cards that paypal mentions on their site, the payment fails with:
DCC_PREPROCESSOR_ERROR

**Comment by pp-randy** [comment]
Did the random generated card not work, or are you referring to a particular documentation?

**Comment by pp-randy** [comment]
If a random card is failing can I get the latest debug_id from you?

**Comment by pp-randy** [comment]
Closing due to lack of response.
