### ISSUE TITLE
Android SDK Internal error while payment using credit card

### ISSUE THREAD

**Issue by ravibvinfotech** [paypal/PayPal-Ruby-SDK#275]
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"84acbda9d2549"}

**Comment by pp-randy** [comment]
The credit card number you are using is causing the issue, which we are tracking here https://github.com/paypal/PayPal-REST-API-issues/issues/22, so please follow this issue for further information. 

The bottom of this FAQ has a credit card generator that should work for you in sandbox https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413.
