### ISSUE TITLE
Choosing the currency in which the payment should add to the balance.

### ISSUE THREAD

**Issue by amitej1** [paypal/PayPal-Ruby-SDK#276]
My paypal account is based in the UK, and I have suppliers all over the world who will be getting paid through the system. I want to be able to choose the currency the payment is converted to in my Paypal balance, at the time the payment is made. e.g An end user sees the price of an item in EUR based on his location, but the supplier is based in US, so when I receive the payment in my account in UK, I want to convert the payment to USD, and add to the balance in USD, and not EUR.

Is there any way to achieve that while creating a new payment through the SDK?

**Comment by pp-randy** [comment]
No, currently the opposite can be done with an account setting. Say you charged them in USD then it could be converted to EUR or another single primary currency. 

An option would be for you to charge them in USD if you want to receive USD then you would not need to pay conversion fees.  That is also an account setting to receive multiple currencies; this would mean you would need to know the price of your items in USD as well though before making the API call.

**Comment by amitej1** [comment]
Hi,

So is there anyway to achieve the following:
1. A payment comes through to my account in USD. It is automatically converted to GBP(my account's base currency) and added to my balance. Say this is $10
2. A dollar mass-payout is made through the API to another Paypal account(base currency - USD). 

At the moment if I try this, I can see the payout gets rejected, but if I do a single payment by logging onto Paypal, it goes through.

Thanks

**Comment by pp-randy** [comment]
For a Payout you need to have the amount in the currency in your account.   Why convert to GBP if you want to send USD as well though?   With your manual way you have two conversion fees if you have the payment converted to GBP and then manually send USD.  If you hold the USD balance as well as GBP you could receive and send USD and not pay a conversion fee.

**Comment by amitej1** [comment]
Ok, so here is the issue: 
1. I have global suppliers on my website who will have their own products, and they should be able to price their products in the choice of their currency, USD, GBP, or, EUR.
2. The end users can pay in a currency based on their location, USD, GBP or EUR again. 

So, a supplier in US, puts in a product for $10, and a buyer in Europe can buy the product for €9.37. The payment comes through to my UK paypal account as €9.37. I only pay the supplier once the product is delivered, so I need to able to hold the payment in order to refund it, in case the product is not delivered. Now, at the time of payout to the supplier, I have balance in €, but I need to payout in $. If I payout in €, I will again be hit by conversion, and the supplier may get an amount less or greater than $10 based on the conversion rate on that day.

Any workaround for this?

**Comment by xiaoleih41** [comment]
I understand that you are providing some kind of escrow services. you will have to manually convert the funds to USD when you do your payout to your US supplier. PayPal does need your explicit consent to accept our conversion rate and  complete this type of conversion.  Unfortunately, there's no way to automate this part of process. Thank you for your questions. Thanks, Xiaolei
