### ISSUE TITLE
We was not receiving any webhook event using credit card payment but paypal payment received it.

### ISSUE THREAD

**Issue by kevin-jj** [paypal/PayPal-Ruby-SDK#277]
### General information

* SDK/Library version:  PayPalSDK/PayPal-Ruby-SDK 1.6.0
* Environment: Sandbox
* `PayPal-Debug-ID` values:  8daea768-0a0c-49e2-9c70-e3ca43720fba
* Language, language version, and OS: Ruby, 2.4.0p0, MacOS

### Issue description

```ruby
@payment = PayPal::SDK::REST::Payment.new(
        options.merge(payer: {
          payment_method: 'credit_card',
          funding_instruments: [{
          # ###CreditCard
          # A resource representing a credit card that can be
          # used to fund a payment.
            :credit_card => {
              :type => "visa",
              :number => "4567516310777851",
              :expire_month => "11",
              :expire_year => "2018",
              :cvv2 => "874",
              :first_name => "Joe",
              :last_name => "Shopper",
            }
          }]
        })
)
```

**Comment by pp-randy** [comment]
Currently, a webhook is only sent for PayPal funded payments. 

A feature request has been submitted for this issue and we will be tracking it here: https://github.com/paypal/PayPal-REST-API-issues/issues/59
Please follow the above issue for further updates.
