### ISSUE TITLE
Item amount must add up to specified amount subtotal (or total if amount)

### ISSUE THREAD

**Issue by Ingosmar89219** [paypal/PayPal-Ruby-SDK#278]
Someone can help me? i get this in the console:
Completed 500 Internal Server Error in 735ms (ActiveRecord: 2.0ms)

RuntimeError (--- !ruby/hash:PayPal::SDK::REST::ErrorHash
name: VALIDATION_ERROR
details:

!ruby/hash:PayPal::SDK::REST::ErrorHash
field: transactions[0]
issue: Item amount must add up to specified amount subtotal (or total if amoun
t
details not specified)
message: Invalid request - see details
information_link: https://developer.paypal.com/docs/api/payments/#errors
debug_id: 91f873d68dd0
):
app/controllers/payments_controller.rb:47:in `create'
Details code: stackoverflow
http://stackoverflow.com/questions/43299511/i-cant-get-the-total-money-of-the-shopping-cart-when-i-update-the-number-of-prod

anyways i pasted code here

Well i have a website where i have a model ShoppingCart, InShoppingCart, Payment and Product. when i add InshoppingCarts to ShoppingCart i get a number of products, always is 1 product for each InShoppingCart into ShoppingCart but the user can update the number of products from the view. The issue happens when the user updates the number of products > 1 for example: 2,3,4,5...n but if the number is 1 all works fine :(, the view is this:

view CODE:
=render "payments/card_data"
.col-lg-10.col-lg-offset-1.col-md-10.col-md-offset-1.col-sm-10.col-sm-offset-1.col-xs-12.bottom.top-space
.card.large-padding
.table-responsive
%table.table.table-bordered.table-hover.medium#table_shopping_cart
%thead
%td.success Producto
%td.success Costo
%td.success Cantidad
%td.success Acciones
%tbody
-@shopping_cart.in_shopping_carts.each do |i_sh|
-product = i_sh.product
%tr{id: "#{product.id}"}
%td= product.name
%td= product.pricing / 100
%td
= form_tag i_sh, method: :put, class:"top-space" do
.form-group
=number_field_tag :num_products,nil, class:"form-control floating-label", placeholder: "#{i_sh.num_products}", required: true
=content_tag :button, type: :submit, class:"btn btn-primary bold" do
Actualizar
%td
%button.red-text.button-active-pink.no-underline{'data-toggle': "modal", 'data-target': "#"+"#{product.id}"}
Eliminar
.modal.fade{id: "#{product.id}", tabindex:"-1", role:"dialog", 'aria-labelledby': "#{product.id}"}
.modal-dialog{role: "document"}
.modal-content
.modal-header
%button.close{type: "button", 'data-dismiss': "modal", 'aria-label': "Close"}
%span{'aria-hidden': "true"}
×
%h4.modal-title.red-text{id: "#{product.id}"} Alerta
.modal-body
%h4.text-center ¿Estas seguro de eliminar el producto del carrito?
.modal-footer
%button.btn.btn-warning.bold{type: "button", 'data-dismiss': "modal"}
Cerrar
= link_to "Aceptar",i_sh, method: :delete,class: "btn btn-success bold margin-bottom"
.top-scape.large-padding.text-center#payment_form
%p.medium
%strong

if @shopping_cart.total != 0
Total: $
= @shopping_cart.total / 100
USD
elsif @shopping_cart.total == 0 || @shopping_cart.total == nil
%h3 Compra con confianza en naturecode.com
.top-space
if @shopping_cart.total != 0
=render "payments/buttons"
elsif @shopping_cart.total == 0 || @shopping_cart.total == nil
=link_to "Agregar producto", products_path, class: "btn btn-primary bold"
Product
class Product < ActiveRecord::Base
acts_as_votable
belongs_to :user
has_many :attachments
validates_presence_of :name,:user,:pricing
validates :pricing, numericality: { greater_than: 0 }

has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100"},default_url: "missing.png"
validates_attachment_content_type :avatar, content_type: /\Aimage/.*\Z/

def paypal_form
{name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:1}
end

i believe that the issue happens for this: the quantity is one but when the user updates the inshoppingcart for example 2 products,3,4,5...n i get the error :/

def paypal_form {name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:1}

ShoppingCart
class ShoppingCart < ActiveRecord::Base
include AASM
has_many :products, through: :in_shopping_carts
has_many :in_shopping_carts

aasm column: "status" do
state :created, initial: true
state :payed
state :failed

event :pay do
    after do
        # TO DO
    end
    transitions from: :created, to: :payed
end
end

def items
self.products.map{ |product| product.paypal_form }
end

def total
$res=0
self.in_shopping_carts.map { |i_sh|
product = i_sh.product
$res += product.pricing * i_sh.num_products
}
return $res
end
end

InShoppingCart
class InShoppingCart < ActiveRecord::Base
belongs_to :product
belongs_to :shopping_cart
has_one :user, through: :product
end

Mypayment
class MyPayment < ActiveRecord::Base
belongs_to :shopping_cart
include AASM

aasm column: "status" do
state :created, initial: true
state :payed
state :failed

event :pay do
    after do
        shopping_cart.pay!
        self.update_stock_products()
    end
    transitions from: :created, to: :payed
end
end

def update_stock_products
self.shopping_cart.in_shopping_carts.map { |i_sh|
product = i_sh.product
res = product.stock - i_sh.num_products
Product.update(product.id,stock: res)
}
end
end

PaymentsController

class PaymentsController < ApplicationController

def checkout
@my_payment = MyPayment.find_by(paypal_id: params[:paymentId])
if @my_payment.nil?
redirect_to "/carrito"
else
Stores::Paypal.checkout(params[:PayerID],params[:paymentId]) do
@my_payment.pay!
redirect_to ok_path, notice: "Se proceso el pago con Paypal"
return
end
redirect_to carrito_path, notice:"Hubo un error al procesar el pago"
end
end
def process_card
paypal_helper = Stores::Paypal.new(@shopping_cart.total,
@shopping_cart.items,
return_url: checkout_url,
cancel_url: carrito_url)
if paypal_helper.process_card(params).create
@my_payment = MyPayment.create!(paypal_id: paypal_helper.payment.id,
ip:request.remote_ip,
email: params[:email],
shopping_cart_id: cookies[:shopping_cart_id])
@my_payment.pay!
redirect_to carrito_path, notice:"El pago se realizo correctamente"
else
redirect_to carrito_path, notice: paypal_helper.payment.error
end
end
def create
paypal_helper = Stores::Paypal.new(@shopping_cart.total,
@shopping_cart.items,
return_url: checkout_url,
cancel_url: carrito_url)
if paypal_helper.proccess_payment.create

@my_payment = MyPayment.create!(paypal_id: paypal_helper.payment.id,
                                ip:request.remote_ip,
                                shopping_cart_id: cookies[:shopping_cart_id])
redirect_to paypal_helper.payment.links.find{|v| v.method == "REDIRECT" }.href
else
raise paypal_helper.payment.error.to_yaml
end
end
end

**Comment by pp-randy** [comment]
What is the amount of one item `playera djs`?  If one costs $250, then `items[n].price` should be set to $250, as this value is multiplied by `3` based on your `items[n].quantity`. 

 `3 * 250 = 750` for a total.

Here is the request for reference. 
```
 "transactions": [
        {
            "item_list": {
                "items": [
                    {
                        "sku": "item",
                        "currency": "USD",
                        "price": "750",
                        "name": "playera djs ",
                        "quantity": "3"
                    }
                ]
            },
            "amount": {
                "currency": "USD",
                "total": "750"
            }
        }
```

**Comment by pp-randy** [comment]
Looking over http://stackoverflow.com/questions/43299511/i-cant-get-the-total-money-of-the-shopping-cart-when-i-update-the-number-of-prod

**Product**
```
def paypal_form(pricing,quantity)
    {name: name,sku: :item, price: ((pricing*quantity) / 100),currency:"USD",quantity:quantity}
end
```
The above code should be the price per item, so don't multiply by the quantity.  
```
def paypal_form(pricing,quantity)
    {name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:quantity}
end
```

---------------------------------------
Your initial code provided is hard to read, here is a reference for how to format your comments on GitHub that you might find helpful https://help.github.com/articles/about-writing-and-formatting-on-github/.

**Comment by pp-randy** [comment]
Closing due to lack of further responses.
