### ISSUE TITLE
Why do 500 error issues keep getting locked with no response or solution>

### ISSUE THREAD

**Issue by AdamMiltonBarker** [paypal/PayPal-Ruby-SDK#279]
I have found many 500 error issues on the net and they all get closed with no response. 

I am continually receiving 500 errors from the Sandbox.

**Comment by xiaoleih41** [comment]
Do you have a debug ID? Could you please provide more detail for us to investigate? 500 error could be caused by various reasons. We have to look into them case by case.

**Comment by pp-randy** [comment]
The majority of the locked threads for 500 errors would be in the context of a specific issue that caused it and that issue has since been resolved, those should have an update that it was resolved before a lock was put on it though.

**Comment by pp-randy** [comment]
Closing the issue due to inactivity.
