### ISSUE TITLE
【Question】How to integrate with rails

### ISSUE THREAD

**Issue by codeztestiamonia** [paypal/PayPal-Ruby-SDK#287]
### General information

SDK/Library version: paypal-sdk-rest (1.6.0)
Environment: Sandbox
`PayPal-Debug-ID` Sorry I can't find it.
 Language, language version, and OS: , Rails 5.1.1, ruby 2.4.1, mac OS X EI Cation 10.11.6

### Issue description
I tried to integrate paypal into rails application, but I can't do it well. I'd appreciate if someone could answer these questions.

As the paypal demo site shows, I implemented client side.
https://developer.paypal.com/demo/checkout/#/pattern/server

#index.html.erb

    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    
    <div id="paypal-button-container"></div>
    
    <script>
        paypal.Button.render({
    
            env: 'sandbox', // sandbox | production
    
            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,
    
            // payment() is called when the button is clicked
            payment: function() {
    
                // Set up a url on your server to create the payment
                var CREATE_URL = "<%= checkout_url %>";
    
                // Make a call to your server to set up the payment
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                        return res.paymentID;
                    });
            },
    
            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {
    
                // Set up a url on your server to execute the payment
                var EXECUTE_URL = "<%= execute_url %>";
    
                // Set up the data you need to pass to your server
                var data = {
                    paymentID: data.paymentID,
                    payerID: data.payerID
                };
    
                // Make a call to your server to execute the payment
                return paypal.request.post(EXECUTE_URL, data)
                    .then(function (res) {
                        window.alert('Payment Complete!');
                    });
            }
    
        }, '#paypal-button-container');
    </script>

#config/routes.rb

    Rails.application.routes.draw do
      get 'pages/index'
    
      post '/checkout' => 'paypal#checkout'
      get '/execute' =>  'paypal#execute'
    end

Using "PayPal-Ruby-SDK"
#paypal_controller.rb

    require 'paypal-sdk-rest'
    include PayPal::SDK::REST
    include PayPal::SDK::Core::Logging
    
    class PaypalController < ApplicationController
      skip_before_action :verify_authenticity_token
    
      def checkout
        @payment = Payment.new({
          :intent =>  "sale",
    
          # ###Payer
          # A resource representing a Payer that funds a payment
          # Payment Method as 'paypal'
          :payer =>  {
            :payment_method =>  "paypal" },
    
          # ###Redirect URLs
          :redirect_urls => {
            :return_url => "http://localhost:3000/execute",
            :cancel_url => "http://localhost:3000/" },
    
          # ###Transaction
          # A transaction defines the contract of a
          # payment - what is the payment for and who
          # is fulfilling it.
          :transactions =>  [{
    
            # Item List
            :item_list => {
              :items => [{
                :name => "item",
                :sku => "item",
                :price => "5",
                :currency => "USD",
                :quantity => 1 }]},
    
            # ###Amount
            # Let's you specify a payment amount.
            :amount =>  {
              :total =>  "5",
              :currency =>  "USD" },
            :description =>  "This is the payment transaction description." }]})
    
        # Create Payment and return status
        if @payment.create
          # Redirect the user to given approval url
          @redirect_url = @payment.links.find{|v| v.rel == "approval_url" }.href
          logger.info "Payment[#{@payment.id}]"
          logger.info "Redirect: #{@redirect_url}"
        else
          logger.error @payment.error.inspect
        end
      end
    
      def execute
        payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
    
        if payment.execute(payer_id: params[:PayerID]) 
          render text: 'Payment Complete'
        else
          render text: payment.error 
        end
      end
    end

![Image of Error Console Log](https://i.stack.imgur.com/UZaHw.png)

# Copy of error console log
ppxo_xc_ppcheckout_error Object {error: "Error: SyntaxError: Unexpected end of JSON input↵ …://www.paypalobjects.com/api/checkout.js:1968:13)", timestamp: 1496219680655, windowID: "80430b198c", pageID: "f6110e21df", referer: "http://localhost:3000"…}country: "US"env: "sandbox"error: "Error: SyntaxError: Unexpected end of JSON input↵    at JSON.parse (<anonymous>)↵    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:10964:39)↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2042:118)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:1948:73)↵    at messageListener (https://www.paypalobjects.com/api/checkout.js:1968:13)"host: "www.sandbox.paypal.com"lang: "en"pageID: "f6110e21df"path: "/webapps/hermes/button"referer: "http://localhost:3000"timestamp: 1496219680655uid: "6836e1fd82"ver: "4.0.78"windowID: "80430b198c"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__() 

 Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:10964:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2042:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:1948:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:1968:13)
__webpack_require__.i.window.console.window.console.(anonymous function) @ index.js:536
print @ logger.js:53
log @ logger.js:161
error @ logger.js:214
error @ logger.js:36
Component.logError @ index.js:491
(anonymous) @ index.js:1177
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
ParentComponent.error @ index.js:1175
(anonymous) @ decorators.js:24
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
descriptor.value @ decorators.js:23
(anonymous) @ index.js:65
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ index.js:1149
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
options.respond @ client.js:92
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:120
receiveMessage @ index.js:92
messageListener @ index.js:117
types.js:120 Uncaught Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:10964:39)
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:10964:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2042:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:1948:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:1968:13)
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:120
receiveMessage @ index.js:92
messageListener @ index.js:117

**Comment by yob** [comment]
I suspect that iInside your `checkout` and `execute` actions, you need to return JSON data to the client.

For `checkout`, something like:

```ruby
    if @payment.create
      render json: {success: true, paymentID: @payment.id}
    else
      render json: {success: false}
    end
```

For `execute`, something like:

```ruby
    if payment.execute(payer_id: params[:PayerID]) 
      render json {msg: 'Payment Complete'}
    else
      render json: {msg: payment.error}
    end
```

**Comment by codeztestiamonia** [comment]
It worked! Thank you so much!
