### ISSUE TITLE
Webhook Event for Fee PAYMENT.SALE.COMPLETED

### ISSUE THREAD

**Issue by bstarr322** [paypal/PayPal-Ruby-SDK#288]
```
gem 'paypal-sdk-core', :git => 'https://github.com/paypal/sdk-core-ruby.git'
gem 'paypal-sdk-rest', :git => 'https://github.com/paypal/rest-api-sdk-ruby.git'

GIT
  remote: https://github.com/paypal/rest-api-sdk-ruby.git
  revision: 52a6688861023ebb2a3f5c9c9133844fe93b13c5
  specs:
    paypal-sdk-rest (1.6.0)
      multi_json (~> 1.0)
      xml-simple

GIT
  remote: https://github.com/paypal/sdk-core-ruby.git
  revision: 384b9ab6af7e23a2d5da9c9b84b3fc2ac1f4e5cb
  specs:
    paypal-sdk-core (0.3.4)
      multi_json (~> 1.0)
      xml-simple
```

## 1. How to check WebhookEvent for Fee
I've integrated subscription by credit card and set PAYMENT.SALE.COMPLETED. But I got 2 webhook events for purchasing one subscription.
For example, if I subscribe to $24.99/month, then I used to get 2 PAYMENT.SALE.COMPLETED webhook events for $24.99 and $1.03(guess it is fee amount).
So I'd like to filter fee webhook events. Are there any fields in webhook response which shows fee webhookevent?

My webhook handler is as following:
```
if params['event_type'] == 'PAYMENT.SALE.COMPLETED'
      if params['resource']['billing_agreement_id'].present? && Subscription.find_by(:paypal_agreement_id => params['resource']['billing_agreement_id']).present?
        payment_amount = params['resource']['amount']['total']
        billing_agreement_id = params['resource']['billing_agreement_id']
        PaypalHook::PaymentSucceeded.new(billing_agreement_id, payment_amount, 'card')
      end
      head :ok
    elsif params['PAYMENT.SALE.DENIED']
      if params['resource']['billing_agreement_id'].present? && Subscription.find_by(:paypal_agreement_id => params['resource']['billing_agreement_id']).present?
        payment_amount = params['resource']['amount']['total']
        billing_agreement_id = params['resource']['billing_agreement_id']
        PaypalHook::PaymentFailed.new(billing_agreement_id, payment_amount, 'card')
      end
      head 404
end
```

## 2. How to charge Fee to merchant, not to buyer
Our service should charge fee to merchant, not to buyer. So I set setup_fee to 0.

```
plan = Plan.new({
      :name => self.unique_key,
      :description => self.title,
      :type => 'fixed',
      :payment_definitions => [{
        :name => self.unique_key,
        :type => 'REGULAR',
        :frequency_interval => self.interval_count.to_s,
        :frequency => self.interval.upcase,
        :cycles => '999',
        :amount => {
          :currency => 'USD',
          :value => (self.price / 100.0).ceil(2).to_s
        }
      }],
      :merchant_preferences => {
        :setup_fee => {
          :currency => 'USD',
          # :value => ((self.price / 100.0) * 0.029 + 0.3).ceil(2).to_s
          :value => 0
        },
        :cancel_url => packages_url,
        :return_url => profile_url + "#subscription",
        :max_fail_attempts => '0',
        :auto_bill_amount => 'YES',
        :initial_fail_amount_action => 'CONTINUE'
      }
    })
```

I want you to review my code and give me solutions.
Thank you

**Comment by xiaoleih41** [comment]
Could you please share the `debug_Ids` or `Sale_Ids` of  the transactions you mentioned above? This will help us figure out the cause. PayPal doesn't send out a separate **webhook** for `transaction_fee`.   I want to make sure that you are aware of  the difference between the `setup_fee` and `transaction_fee`.  `setup_fee` is an optional initial amount charged when the buyer approves the agreement. It is an amount defined by you if you want to charge an amount upfront. `transaction_fee` and it's rate  is determined by PayPal. `transaction_fee` is always taken from the merchant's account.

**Comment by bstarr322** [comment]
Thank you for the answer, @xiaoleih41.
I understood that transaction_fee is always taken from the merchant and it's ok. And if I set setup_fee to 0, it means that I want an upfront?

And I'll reproduce the above webhook and let you know the debug_Ids or Sale_Ids soon.
Thanks again for your advice.

**Comment by xiaoleih41** [comment]
If  you do not define `setup_fee` then there's no upfront charge for the buyer when he approves the agreement. The use case for `setup_fee` could be that some merchant wants to start his subscriptions all at the beginning of the calendar month. If someone signs up in the middle of the month, the merchant would like to charge the subscription amount covers the rest of the first month only before the normal full amount monthly fee kicks in for the next month. Please let me know if it makes sense to you.

**Comment by xiaoleih41** [comment]
Close this ticket due to inactivity. Please resubmit if you have additional questions.

**Comment by bstarr322** [comment]
Hello, @xiaoleih41.

I charged $24.99/month recurring subscription and got a webhook event as following: 

```
{
	"id": "WH-8RN9330940763772W-0L307218M5479953X",
	"create_time": "2017-06-12T15:04:42.172Z",
	"resource_type": "sale",
	"event_type": "PAYMENT.SALE.COMPLETED",
	"summary": "Payment completed for $ 1.03 USD",
	"resource": {
		"amount": {
			"total": "1.03",
			"currency": "USD",
			"details": {}
		},
		"id": "8BE35754P7604052S",
		"receipt_id": "3934770226493115",
		"update_time": "2017-06-12T15:04:14Z",
		"create_time": "2017-06-12T15:04:14Z",
		"payment_mode": "INSTANT_TRANSFER",
		"state": "completed",
		"links": [
			{
				"href": "https://api.sandbox.paypal.com/v1/payments/sale/8BE35754P7604052S",
				"rel": "self",
				"method": "GET"
			},
			{
				"href": "https://api.sandbox.paypal.com/v1/payments/sale/8BE35754P7604052S/refund",
				"rel": "refund",
				"method": "POST"
			}
		],
		"soft_descriptor": "PHILIPPKLEI",
		"billing_agreement_id": "I-KLNPCUAEF1DG",
		"transaction_fee": {
			"value": "0.33",
			"currency": "USD"
		},
		"protection_eligibility": "INELIGIBLE"
	},
	"links": [
		{
			"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-8RN9330940763772W-0L307218M5479953X",
			"rel": "self",
			"method": "GET",
			"encType": "application/json"
		},
		{
			"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-8RN9330940763772W-0L307218M5479953X/resend",
			"rel": "resend",
			"method": "POST",
			"encType": "application/json"
		}
	],
	"event_version": "1.0"
}
```

I can see it is obviously the notification about transaction_fee, but wonder why transaction_fee is also considered as PAYMENT.SALE.COMPLETED. Is there any way I can distinguish transaction_fee?

**Comment by xiaoleih41** [comment]
Can you please share your requesting API minus password? The $1.03 is considered as a recurring payment in your transaction history and it's transaction fee is $0.33. It was a payment sent to the receiver.
