### ISSUE TITLE
PayPal::SDK::Core::Exceptions::ServerError on payment execution

### ISSUE THREAD

**Issue by redjoker011** [paypal/PayPal-Ruby-SDK#289]
### General information

* SDK/Library version: paypal-sdk-rest (1.6.0)
* Environment: Production
* `PayPal-Debug-ID` values: No Debug ID
* Language, language version, and OS: Ruby on Rails, Ubuntu 16.04

### Issue description
We experience PayPal::SDK::Core::Exceptions::ServerError during payment execution in Production without debug any id and the api call is not recorded on live API calls in developer dashboard.

 Failed.  Response code = 500.  Response message = Internal Server Error.

What is the possible cause of the error?Please help thanks

**Comment by xiaoleih41** [comment]
Was it successful in sanbox?  This error could be temporary connectivity issue for live environment. Please make sure that you have all the live credentials configured correctly and all the necessary permission enabled within your live app when you make the payment. What type of payment call are you trying to make? You may consider to contact https://www.paypal-techsupport.com/ for production environment issue.

**Comment by redjoker011** [comment]
yup transactions are successful in sandbox but raise an exception error in production during the payment execution.Credentials are also setup properly .maybe i should contact the tech support thanks.

**Comment by xiaoleih41** [comment]
Close this ticket due to inactivity.
