### ISSUE TITLE
Transfer to bank account

### ISSUE THREAD

**Issue by BrunoAwdd** [paypal/PayPal-Ruby-SDK#294]
I would like to know if there is any way in the API to control the transfer of money from the PayPal account to the bank account.
I'm creating a marketplace. And it's not worth having multiple paypal accounts for each person who signs up. For this reason, I would like to know if there is any tool that allows the automation of the transfer to the bank accounts (each logista will have his account registered in my marketplace), and I will select it and make the transfer.

**Comment by pp-randy** [comment]
Have you looked into the [Braintree Marketplace](https://www.braintreepayments.com/products/braintree-marketplace)? 

PayPal supports withdrawal from a PayPal Account to a bank account but it is a configured process per account and not controlled by an API.

**Comment by pp-randy** [comment]
Closing the issue, please let me know if you have further questions.
