### ISSUE TITLE
uninitialized constant PayPal::SDK::Core::Util::HTTPHelper::ResourceInvalid

### ISSUE THREAD

**Issue by tomasbecklin** [paypal/PayPal-Ruby-SDK#295]
### General information

* SDK/Library version: 1.6.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: ruby, 2.3.1p112, OSX

### Issue description
When calling `create` on a new payout `PayPal::SDK::REST::Payout.new`. 

We've had this code in production for at least a year and this just started to happen today when running rspec. Updated to `1.6.0` 4 months ago.

* Code
```
      @payout = PayPal::SDK::REST::Payout.new(
        {
          :sender_batch_header => {
            :sender_batch_id => SecureRandom.hex(8),
            :email_subject => 'You have been payed!',
            :recipient_type => 'EMAIL'
          },
          :items => [
            {
              :recipient_type => 'EMAIL',
              :amount => {
                :value => @amount,
                :currency => 'USD'
              },
              :note => '...',
              :receiver => @email,
              :sender_item_id => "{SecureRandom.hex(3)}_#{@payout_id}"
            }
          ]
        }
      )
      begin
        @payout_batch = @payout.create
        @id = @payout_batch.batch_header.payout_batch_id
      rescue PayPal::SDK::REST::ResourceNotFound => err
        raise PaymentProcessor::APIError,
          "Paypal payment error: #{@payout.error.inspect}"

      end
```

**Comment by pp-randy** [comment]
This looks like `PayPal::SDK::REST::ResourceNotFound` is undefined from the error it appears to be `PayPal::SDK::Core::Exceptions::ResourceNotFound`
https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/exceptions.rb#L76

Are you able to get the actual error details for the payout?

**Comment by tomasbecklin** [comment]
No error unfortunately. `@error=nil`

**Comment by tomasbecklin** [comment]
Debugged `https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/util/http_helper.rb`

Payload that fails
```{:method=>:post, :action=>"v1/payments/payouts", :query=>{:sync_mode=>false}, :params=>{"sender_batch_header"=>{"sender_batch_id"=>"4c7b8a7c9132e112", "email_subject"=>"[DroneBase] You have been payed!", "recipient_type"=>"EMAIL"}, "items"=>[{"recipient_type"=>"EMAIL", "amount"=>{"currency"=>"USD", "value"=>"100"}, "note"=>"Thanks for flying a mission for us!", "receiver"=>"delmy.mohr@example.com", "sender_item_id"=>"603d23_1234"}]}, :header=>{"Authorization"=>"Bearer xxxxxxxxxxxxx", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.0 (paypal-sdk-core 1.6.0; ruby 2.3.1p112-x86_64-darwin15;OpenSSL 1.0.2h  3 May 2016)", "PayPal-Request-Id"=>"cec0cfa1-8acc-44b2-b671-876229395ceb"}, :uri=>#<URI::HTTPS https://api.sandbox.paypal.com/v1/payments/payouts?sync_mode=false>, :http=>#<Net::HTTP api.sandbox.paypal.com:443 open=false>, :body=>"{\"sender_batch_header\":{\"sender_batch_id\":\"4c7b8a7c9132e112\",\"email_subject\":\" You have been payed!\",\"recipient_type\":\"EMAIL\"},\"items\":[{\"recipient_type\":\"EMAIL\",\"amount\":{\"currency\":\"USD\",\"value\":\"100\"},\"note\":\"Thanks !\",\"receiver\":\"delmy.mohr@example.com\",\"sender_item_id\":\"603d23_1234\"}]}"}```

response:
```<Net::HTTPUnprocessableEntity 422 Unprocessable Entity readbody=true>```

**Comment by pp-randy** [comment]
Are you able to get a debug_id either from the response JSON or the response HTTP Header?

**Comment by tomasbecklin** [comment]
```"{\"name\":\"INSUFFICIENT_FUNDS\",\"message\":\"An internal service error has occurred.\",\"debug_id\":\"cdbf9b9fde859\",\"information_link\":\"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors\"}"```

**Comment by pp-randy** [comment]
You need to have enough PayPal Balance to cover the payout.

**Comment by pp-randy** [comment]
I sent you some sandbox money, please try again.

**Comment by tomasbecklin** [comment]
Working now. Thank you for the help!

**Comment by casiodk** [comment]
I have the same error, how do you get sandbox money

**Comment by pp-randy** [comment]
Create a new account with a high balance or create some transactions.  You can send money from the new account to your existing instead of recreating everything.

**Comment by casiodk** [comment]
it keeps failing, i have tried multiple accounts

Response debug ID = 269e30551d015, 269e30551d015.

**Comment by xiaoleih41** [comment]
You have to make sure your API caller account/payout account has positive balance.  You cannot send a payout without the enough balance to cover the payout. Please create a new account with a positive balance and send money (not payout) to the API account to help bring up the balance on that account.
