### ISSUE TITLE
UNAUTHORIZED_AGREEMENT_REQUEST

### ISSUE THREAD

**Issue by gullocean** [paypal/PayPal-Ruby-SDK#301]
Hello,
The site is running on PayPal Live mode.
SDK versions are:
```
GIT
  remote: https://github.com/paypal/rest-api-sdk-ruby.git
  revision: 52a6688861023ebb2a3f5c9c9133844fe93b13c5
  specs:
    paypal-sdk-rest (1.6.0)
      multi_json (~> 1.0)
      xml-simple

GIT
  remote: https://github.com/paypal/sdk-core-ruby.git
  revision: 384b9ab6af7e23a2d5da9c9b84b3fc2ac1f4e5cb
  specs:
    paypal-sdk-core (0.3.4)
      multi_json (~> 1.0)
      xml-simple
```
```
Ruby Version: 2.4.0
gem 'rails', '~> 5.0.1'
```
And the error response is:
`Response.body={"name":"UNAUTHORIZED_AGREEMENT_REQUEST","message":"You don't have permission to create such agreement.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"6a246eef394d4"}Response.header={"date"=>["Wed, 19 Jul 2017 18:52:22 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["6a246eef394d4", "6a246eef394d4"], "content-language"=>["*"], "http_x_pp_az_locator"=>["slca.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DLIVE5.API.1%26silo_version%3D880%26app%3Dapiplatformproxyserv%26TIME%3D1722445657%26HTTP_X_PP_AZ_LOCATOR%3Dslca.slc; Expires=Wed, 19 Jul 2017 19:22:22 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["226"], "cache-control"=>["max-age=0, no-cache, no-store, must-revalidate"], "pragma"=>["no-cache"], "connection"=>["close"], "content-type"=>["application/json"]}`

It is working in sandbox and I can get paypal plans which were created in live mode.
Looking forward to quick solutions from you.
Best

**Comment by pp-randy** [comment]
Do you have Billing Agreements selected in your Live App settings?  
![image](https://user-images.githubusercontent.com/6819909/28386258-a3f4f978-6c90-11e7-8d97-7ca122603fd1.png)

**Comment by pp-randy** [comment]
Also since this is a production issue you can engage PayPal Technical Support at https://www.paypal-techsupport.com/.

**Comment by gullocean** [comment]
Thank you @pp-randy.
I'll have a look at Live App setting.

**Comment by pp-randy** [comment]
Closing the issue, Technical Support should be able to assist you further if its not an App permission setting.
