### ISSUE TITLE
Update billing plan succeeds but throws JSON parse error in production

### ISSUE THREAD

**Issue by GabeIsman** [paypal/PayPal-Ruby-SDK#302]
### General information

* SDK/Library version: 1.6.0
* Environment: Production, not Sandbox
* `PayPal-Debug-ID` values: 6483e2fc44ee9
* Language, language version, and OS: Ruby 2.3.1, Linux (Heroku)

### Issue description

Calls to activate billing plans in production succeed (status is 200) but the client library chokes on the response. In Sandbox mode the body of the response seems to be totally empty, whereas in Production the response body seems to be some kind of whitespace, possibly a single tab. I get the same error by just running `MultiJson.load("\t")`.

```
MultiJson::ParseError: JSON::ParserError
	from /app/vendor/bundle/ruby/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load'
	from /app/vendor/bundle/ruby/2.3.0/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	from /app/vendor/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:144:in `format_response'
	from /app/vendor/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:87:in `api_call'
	from /app/vendor/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:96:in `api_call'
	from /app/vendor/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:109:in `patch'
	from /app/vendor/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/rest/data_types.rb:2041:in `update'
```

Any guidance?

**Comment by pikoloshanti** [comment]
We're having exactly the same issue.

**Comment by krossa** [comment]
Same story

**Comment by pp-randy** [comment]
Thank you for reporting the issue.  

I have created a REST API issue here for tracking https://github.com/paypal/PayPal-REST-API-issues/issues/120, please follow this issue for further tracking.

**Comment by GabeIsman** [comment]
@pp-randy Thanks for looking into this.

I would respectfully suggest that leaving this issue open might prevent other people from filing duplicates. Since this is a production bug actively causing payments to fail, I imagine other people are also concerned about it.
