### ISSUE TITLE
Model name conflicts

### ISSUE THREAD

**Issue by kirqe** [paypal/PayPal-Ruby-SDK#304]
* SDK/Library version:  gem version 1.6.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values:  "dceef850b16eb", "dceef850b16eb"
* Language, language version, and OS:  ruby 2.4.0, rails Rails 5.1.2, OSX 10.11.6

### Issue description

https://stackoverflow.com/questions/45507303/paypal-ruby-sdk-model-name-conflict

I have a Plan model in my app. And sometimes I'm caching the following error. **After restarting the server it goes away for a while.**

gem version(1.6.0)

How can it be fixed?

`NoMethodError in Subscriptions#index`

    undefined method `map' for #<PayPal::SDK::REST::DataTypes::PlanList:0x007fbc494c13c0>
    Did you mean?  tap

--

      Rendering subscriptions/index.html.erb within layouts/application
      Rendered subscriptions/index.html.erb within layouts/application (3.3ms)
    Completed 500 Internal Server Error in 2145ms (ActiveRecord: 8.3ms)
    
    
    
    ActionView::Template::Error (undefined method `map' for #<PayPal::SDK::REST::DataTypes::PlanList:0x007fbc494c13c0>
    Did you mean?  tap):
         7:       <div class="field">
         8:         <p class="control has-icons-left is-expanded">
         9:           <%= form.input_field :plan_id,
        10:            collection: @plans.map {|plan| ["#{plan.name} - $#{plan.cost}", plan.id]},
        11:            wrapper_html: { class: ' select is-fullwidth' }, class: 'input', label: false, prompt: 'Select a plan' %>
        12:           <span class="icon is-small is-left">
        13:             <i class="fa fa-bars"></i>
    
    app/views/subscriptions/index.html.erb:10:in `block in _app_views_subscriptions_index_html_erb___836818763133109538_70223330120860'
    app/views/subscriptions/index.html.erb:2:in `_app_views_subscriptions_index_html_erb___836818763133109538_70223330120860'

`@plans` is just `Plan.all`

```
  def index
    @plans = Plan.all
    p "--------"
    p current_user.subscription
    p "--------"
  end
```
web console
<img width="1058" alt="screen shot 2017-08-04 at 18 25 50" src="https://user-images.githubusercontent.com/5272402/28975558-2167dd4e-7943-11e7-9a7e-a1e944208774.png">

**Comment by pp-randy** [comment]
@kirqe were you able to resolve this issue based on the stackoverflow feedback?  I have escalated internally for some additional eyes on this.

**Comment by kirqe** [comment]
@pp-randy 

I didn't get any specific answers.

Here's what I noticed.

Here a part of code that executes the payment `if payment.execute(payer_id: params[:PayerID])`

If I temporary set it to `if payment.execute(blalalalparams[:PayerID])` and try to complete the payment, I'm going to get an error (as expected)

Then If I fix the code and set it back to `(payer_id: params[:PayerID])` and refresh the page 
I'm getting the following.

<img width="680" alt="screen shot 2017-08-08 at 19 42 23" src="https://user-images.githubusercontent.com/5272402/29083587-eca42f0e-7c71-11e7-82d7-55510cd54ec3.png">

Then if I go to a page that utilizes `@plans = Plan.all` I'm still getting complains (**same as in my first message**) about the plans until I restart my server.

But if the code is correct and nothing interrupts the payment, it works just fine.

**Comment by pp-randy** [comment]
I see this new issue might be related https://github.com/paypal/PayPal-Ruby-SDK/issues/305

**Comment by kirqe** [comment]
@pp-randy I found the following issue where it's recommended to use namespaces instead of including a module. eg `PayPal::SDK::REST::Payment`

https://github.com/paypal/PayPal-Ruby-SDK/issues/24

Looks like I'm not getting any errors anymore. Thanks

**Comment by pp-randy** [comment]
Awesome.  I'm still catching up on my Ruby...  Thank you for letting me know.
