### ISSUE TITLE
create_profile

### ISSUE THREAD

**Issue by edenisn** [paypal/PayPal-Ruby-SDK#308]
Do you have analog method https://github.com/fnando/paypal-recurring/blob/f99a340bc21e67f6e90cd242a106bd5e82c7bc24/lib/paypal/recurring/base.rb#L175 in your gem?

**Comment by pp-randy** [comment]
I did a search for Analog and don't see one https://github.com/paypal/PayPal-Ruby-SDK/search?utf8=%E2%9C%93&q=analog&type=

**Comment by edenisn** [comment]
Thanks! @pp-randy
