### ISSUE TITLE
Reference Transactions support

### ISSUE THREAD

**Issue by edmz** [paypal/PayPal-Ruby-SDK#309]
I've been reading the code in this repo and haven't found anything that looks like Reference Transactions. _(Though I really don't know exactly what to look for.)_

We already implement Billing Agreements/Plans but need a way to use Reference Transactions as defined in the NVP/SOAP API:

> Use reference transactions to set up recurring payments for varying amounts of money on a varying schedule. 

So, are Reference Transactions supported in this API? If not, is there a way to achieve that using the REST API?

Thanks in advance

**Comment by pp-randy** [comment]
I do not have an ETA on Reference Transactions being available on REST API we are tracking the request here: https://github.com/paypal/PayPal-REST-API-issues/issues/44

I know its being actively worked on, but again I'm not sure in a public release date.
