### ISSUE TITLE
Get error PayPal Connection Exception :: 500 in production

### ISSUE THREAD

**Issue by Yardan** [paypal/PayPal-Ruby-SDK#313]
### General information

* SDK/Library version: 1.11
* Environment: Production
* `PayPal-Debug-ID` values: 92f2bf6023cc1
* Language, language version, and OS: PHP 7.0.19-1 Debian GNU/Linux 9.0 (stretch)

### Issue description

In production we get error: 
```
PayPal Connection Exception :: 500
```
Customer tried to order something. I tried reproduce it, but couldn't. It happen only once.

When customer order something php executes standard script:
```
$context = new ApiContext(new OAuthTokenCredential($clientId, $clientSecret));
-- some code ---
 \PayPal\Api\Payment::create($context)
```
Error details:
```
PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"92f2bf6023cc1"}
```

**Comment by xiaoleih41** [comment]
This looks like a temporary internal connection error. If it happens again, please contact www.paypal-techsupport.com and they can track production bug and let you know if it's a temporary glitch or a bug that have been logged.

**Comment by xiaoleih41** [comment]
Close this issue as correct contact path has been provided.
