### ISSUE TITLE
[minor] logs `undefined method `encType='` on Payout.get()

### ISSUE THREAD

**Issue by engshien** [paypal/PayPal-Ruby-SDK#314]
### General information

* SDK/Library version: 1.6.1
* Environment: Sandbox (occurs in Production also)
* `PayPal-Debug-ID` values: ["c313531813d27", "c313531813d27"]
* Language, language version, and OS: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

### Issue description

On calling `PayPal::SDK::REST::Payout.get(id)`, I get the proper response but I am also getting the following log message

```
D, [2017-10-19T13:16:03.182250 #40012] DEBUG -- : undefined method `encType=' for #<PayPal::SDK::REST::DataTypes::Links:0x007fabb520c688>
Did you mean?  enctype=
               enctype
```

The issue appears to be
```
... Response.body={..."encType":"application/json"...
```
while `lib/paypal-sdk/rest/data_types.rb` has it defined as `enctype` (lowercase 't')

**Comment by xiaoleih41** [comment]
Can you help me find out where `encType` is located at? I will report the issue.

**Comment by bluk** [comment]
Thanks for the report. Will be part of the next release.
