### ISSUE TITLE
Billing Plan / Agreements - Add Ruby code samples to give parity with other supported langs

### ISSUE THREAD

**Issue by eliotsykes** [paypal/PayPal-Ruby-SDK#316]
The code samples linked to from the docs below are missing any Ruby samples (C#, JAVA, Node.js, PHP, Python links are provided)

https://developer.paypal.com/docs/api/payments.billing-plans

**Comment by pp-randy** [comment]
@eliotsykes will the spec test help you for now? https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/subscription_examples_spec.rb

**Comment by eliotsykes** [comment]
Hi @pp-randy, the https://github.com/paypal/PayPal-Ruby-SDK/tree/master/spec directory is helping, thanks 👍

**Comment by thedanielhanke** [comment]
news on this?

the spec https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/subscription_examples_spec.rb is missing/xit-ing the important parts..

**Comment by chibeepatag** [comment]
How do you find an agreement using the token?

After creating the agreement, the id is null. After the user approved the payment in the payPal site I redirect back to my page but how do I get hold of the agreeement without the id?

**Comment by darkslab** [comment]
@chibeepatag I guess something like this works:
`PayPal::SDK::REST::Agreement.new({
  token: 'EC-XXXXXXXXXXXXXXXXX'
}).execute!
`

**Comment by sucithrashanu** [comment]
@eliotsykes 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
