### ISSUE TITLE
Refund no longer works

### ISSUE THREAD

**Issue by SaimonL** [paypal/PayPal-Ruby-SDK#318]
Hi I was using this gem to purchase and do refund from PayPal. Suddenly few months back the refund just stopped working.

I checked the document and it matched what I had:
https://developer.paypal.com/docs/api/quickstart/refund-payment/

```ruby
sale = Sale.find("7DY409201T7922549")

refund = sale.refund({
  :amount => {
    :total => "1.31",
    :currency => "USD"
  }
})
```

When using any order's transaction_id it always finds the order, however when I execute refund like above I always get this same error:
```json
{
  "name": "UNKNOWN_ERROR",
  "message": "An unknown error occurred.",
  "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
  "debug_id": "6ff1a8729491b"
}
```

I went to the page https://developer.paypal.com/docs/api/payments/#errors and did not find "UNKNOWN_ERROR".

Also I am trying to ask this same question to PayPal buts I am unable to login to their form its keeps redirecting to their login form after successful login. Can someone provide a link where I can post this bug in PayPal.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.

**Comment by SaimonL** [comment]
Thanks for looking into this. 

The steps I took were:
1. Using developer.paypal.com create an account "buyer@example.com" as personal.
2. Using developer.paypal.com create an account "seller@example.com" as business.
3. Using developer.paypal.com create an App and linked it to "buyer@example.com".
4. Then get that Apps secret and client ID etc...
5. Is Rails web application purchase something using "buyer@example.com".
6. Then later on 1 day later I login sandbox.paypal.com as "buyer@example.com" and I can see my order there.
7. Then I login as "seller@example.com" and I can see the orders there as well.
8. No I check to match transaction_id which matches with the order I see logged in as "seller@example.com"
9. No in Rails web application I try to do a refund and I get that "**UNKNOWN_ERROR**" even though I logged in as "buyer@example.com" and in different browser logged in as "seller@example.com" and looking at the order right now.
10. I did a CURL as PayPal mentioned in their doc and still I get the same problem (https://developer.paypal.com/docs/api/payments/#sale_refund).

Now remember this was working fine with the same code and account back in July 2017.
My guess is PayPal broke their end. By brother has separate PayPal business account and he has the same problem.

I will try creating another sandbox account and try again.

**Comment by xiaoleih41** [comment]
Please create a new one as the business account is at 'closed' status. You cannot do refund from a closed account.

**Comment by SaimonL** [comment]
All this were done from business account that we has been using it in production since 2014.
We have over thousands of transactions in production that we do manual refund on.

**Comment by xiaoleih41** [comment]
You are correct. Based on the info you have provided, it found the sandbox account was closed.
