### ISSUE TITLE
NoMethodError: undefined method `attributes_builder' for PayPal::SDK::REST::RequestDataType:Module

### ISSUE THREAD

**Issue by alosada** [paypal/PayPal-Ruby-SDK#319]
Hello! 

* SDK/Library version: paypal-sdk-rest (1.6.1) (from gemfile lock)
* Environment: Both
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Rails 4.2.7, Ruby 2.3.4, OS: Ubuntu 16.04

### Issue description

This is an interesting one, I'm running into the error bellow running a rake task. Running the same code on the rails console works fails intermittently. No method calls upon Paypal. 

```
NoMethodError: undefined method `attributes_builder' for PayPal::SDK::REST::RequestDataType:Module
/Users/alejandro/Documents/code/donadora/app/models/project.rb:731:in `finish_projects'
/Users/alejandro/Documents/code/donadora/lib/tasks/projects.rake:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => projects:finish
```

The rake task is: 

```
desc "This task finishes off the projects."
  task :finish => :environment do
    p "Finishing projects. Started at: #{Time.now}"
    Project.finish_all
  end
end
```
And the method: 

```
def self.finish_all
  Project.visible.where(finished: false).each do |project|
    if project.finish!
      p "#{project.name} finished."
      project.handle_milestone
    end
  end
end
```

So ` rake projects:finish` breaks,`Projects.finish_all` in console breaks SOMETIMES, running `Project.visible.where(finished: false).each { |project| project.handle_milestone if project.finish! }
`  works. same behavior regardless of environment.

**Comment by xiaoleih41** [comment]
Do you have any debugId or anything I can take a look at?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please reopen when additional info is provided.
