### ISSUE TITLE
Hook for when user cancels through Paypal?

### ISSUE THREAD

**Issue by regoje** [paypal/PayPal-Ruby-SDK#320]
Hi, 

I can't find references to this anywhere it the docs:

Is there a hook that's triggered when a user cancels a subscription through Paypal or is the developer expected to periodically check for agreement state?

**Comment by xiaoleih41** [comment]
You should get [BILLING.SUBSCRIPTION.CANCELLED](https://developer.paypal.com/docs/integration/direct/webhooks/event-names/#supported-webhook-events) once you subscribed the webhooks. You can always subscribe IPN at the same time to have double assurance.

**Comment by regoje** [comment]
I honestly don't know how I missed that. Thanks.

**Comment by regoje** [comment]
I honestly don't know how I missed that. Thanks.
