### ISSUE TITLE
Billing agreements API

### ISSUE THREAD

**Issue by shime** [paypal/PayPal-Ruby-SDK#328]
Looks like there's no support for [Billing agreements API](https://developer.paypal.com/docs/api/payments.billing-agreements) or [Billing plans API](https://developer.paypal.com/docs/api/payments.billing-plans).

Any plans to add this soon?

**Comment by jaypatel512** [comment]
We do have [Plan API](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L2073) and [Agreements](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L2233)

**Comment by shime** [comment]
Some documentation would be nice.

**Comment by jaypatel512** [comment]
@shime ! You are correct. I assumed we had samples for those already. We will re-open this and keep this as a placeholder to add samples for billing plan and agreement. Thank you for pointing that out.

**Comment by xiaoleih41** [comment]
You can find the documentation on [billing agreement](https://developer.paypal.com/docs/api/payments.billing-agreements) and [billing plan](https://developer.paypal.com/docs/api/payments.billing-plans] from the developer.paypal.com.

**Comment by shime** [comment]
@xiaoleih41 yeah that's the API documentation, I'm talking about documentation for this SDK.

**Comment by pp-randy** [comment]
Closing as a duplicate of https://github.com/paypal/PayPal-Ruby-SDK/issues/316.  The test case might be helpful to you in the mean time https://github.com/paypal/PayPal-Ruby-SDK/tree/master/spec.
