### ISSUE TITLE
README and SDK docs show two ways to configure the environment

### ISSUE THREAD

**Issue by octopusinvitro** [paypal/PayPal-Ruby-SDK#332]
### General information

* SDK/Library version: 1.7.2
* Environment: sandbox or live
* `PayPal-Debug-ID` values: not applicable
* Language, language version, and OS: Ruby 2.4.1 on Ubuntu 16.04

### Issue description

Hello, 
According to the gem's README, in order to configure the environment, one should invoke:

```ruby
  PayPal::SDK::REST.set_config(
# ...etc.
```

However, [according to the API docs](https://developer.paypal.com/docs/api/quickstart/environment/), one should invoke:

```ruby
  PayPal::SDK.configure(
# ...etc.
```

which of the two is the recommended way?

**Comment by bluk** [comment]
Hello, the recommended way is to use `PayPal::SDK::REST.set_config(` for new integrations. We will get the documentation updated.
