### ISSUE TITLE
Sale objects return nil for parent_payment

### ISSUE THREAD

**Issue by matthiassiegel** [paypal/PayPal-Ruby-SDK#333]
Ruby SDK 1.7.2
Production environment

According to the [docs](https://developer.paypal.com/docs/api/payments/#sale_get) you can call `parent_payment` on a sale object to get the ID of the parent payment.

I tried several sale IDs, both from one-off transactions and transactions that were created through billing agreements, and they always return `nil` for `parent_payment`.

```ruby
[2] pry(main)> sale = PayPal::SDK::REST::Sale.find(sale_id)
I, [2018-01-25T11:11:46.644463 #57893]  INFO -- : Request[post]: https://api.paypal.com/v1/oauth2/token
I, [2018-01-25T11:11:47.586357 #57893]  INFO -- : Response[200]: OK, Duration: 0.942s
I, [2018-01-25T11:11:47.594064 #57893]  INFO -- : Request[get]: https://api.paypal.com/v1/payments/sale/(...)
I, [2018-01-25T11:11:48.773545 #57893]  INFO -- : Response[200]: OK, Duration: 1.179s
=> #<PayPal::SDK::REST::DataTypes::Sale:0x00007fbd718e88f8 (...)
[3] pry(main)> sale.parent_payment
=> nil

```

**Comment by xiaoleih41** [comment]
Are these transaction parent payment transaction themselves?

**Comment by matthiassiegel** [comment]
I don't know what you mean. I have a transaction ID (note that in the NVP API this is called transaction ID, but in the REST API it appears to be a sale ID, super confusing) and I can use it to look up the sale object using the REST API, as shown above. But I want to look up the corresponding payment which has more information.

**Comment by xiaoleih41** [comment]
The **parent payment** is a read only field in the response when you query the **sale_id**

**Comment by matthiassiegel** [comment]
Yes I know, and the problem is that the field is always `nil`. It should return the payment ID `PAY-xxxxx`.

After further investigation this looks like an API problem. The `parent_payment` field is not included in the API response when querying `https://api.paypal.com/v1/payments/sale/[sale_id]`.

I've opened a ticket [here](https://github.com/paypal/PayPal-REST-API-issues/issues/190). Closing this one.
