### ISSUE TITLE
Using a custom button

### ISSUE THREAD

**Issue by octopusinvitro** [paypal/PayPal-Ruby-SDK#334]
### General information

* SDK/Library version: 1.7.2
* Environment: sandbox or live
* `PayPal-Debug-ID` values: not applicable
* Language, language version, and OS: Ruby 2.4.1 on Ubuntu 16.04

### Issue description

Hello, this is not really an issue but more of a question, sorry to post here, feel free to redirect me.

We are trying to set up a payment and it looks like we can not do it 100% server side. [According to this documentation page](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/server-side-REST-integration/), it seems like we would have to use the `https://www.paypalobjects.com/api/checkout.js` library in the front-end:

> Note: You must pass `redirect_urls` in the create-payment request but PayPal does not automatically call these URLs. PayPal invokes your `onAuthorize` function when the buyer authorizes the payment. At this point you can choose to redirect the buyer.

The problem with this is that apparently we can only do that through `paypal.Button.render({ ... })`, which will render the PayPal button, but we want users to click our custom form button. Is there a way to still have PayPal invoke `onAuthorize` with your JavaScript library and our custom button, or can we rather have PayPal hit the urls that we set in `redirect_urls` directly, so that we don't need the `onAuthorize` function and hence the JavaScript library.

I am thinking of something like Stripe, which [allows you to have complete control in a very simple checkout workflow](https://stripe.com/docs/checkout#integration-custom).

Thanks

**Comment by xiaoleih41** [comment]
Due to the overall customer experience regarding PayPal branding PayPal  will need you to integrate our hosted button to ensure the consistence of customer experience and avoid necessary confusion.  However we do have various options in term of button styles. Please take a look at [here](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/) to see if you can build the button with all the options that PayPal is offerning

**Comment by octopusinvitro** [comment]
Thanks @xiaoleih41 .

Does that mean that there is absolutely no way to avoid the PayPal button. It would really break our design and hence our own branding.

We had already looked at the button styles page you point to but it doesn't solve the problem. The experience with Stripe is still consistent and creates no confusion for our users despite using our custom form. In fact, the presence of the extra PayPal button is more likely to create confusion than if there was only our form button.

Is there any other PayPal payment flow that would allow us to avoid the PayPal button?

**Comment by xiaoleih41** [comment]
I know historically, we did allow customized button but we also found out that many customers were having trouble to click on those buttons as they didn't trust it was linked to their real PayPal account. I do not believe we have this option anymore but you can always contact our sales team and see if some legacy option is still available to certain merchant.

**Comment by pp-randy** [comment]
Closing the issue as the answer has been provided.
