### ISSUE TITLE
"INTERNAL_SERVICE_ERROR" Paypal Paiment by Credit_Card

### ISSUE THREAD

**Issue by oussama-sahloul** [paypal/PayPal-Ruby-SDK#346]
i just tried to make validation for Credit Card before finale Sale, 
Code is so simple , but i can't understand why it show that message to me 
**"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred."**

`<?php
// 1. Autoload the SDK Package. This will include all the files and classes to your autoloader
include 'PayPal-PHP-SDK/autoload.php';
// 2. Provide your Secret Key. Replace the given one with your app clientId, and Secret
// https://developer.paypal.com/webapps/developer/applications/myapps

use \PayPal\Rest\ApiContext;
use \PayPal\Auth\OAuthTokenCredential;
use \PayPal\Api\Address;
use \PayPal\Api\CreditCard;
use \PayPal\Api\CreditCardToken;
use \PayPal\Api\FundingInstrument;
use \PayPal\Api\Payer;
use \PayPal\Api\Amount;
use \PayPal\Api\Transaction;
use \PayPal\Api\Payment;

function authorization() {
    
    $apiContext = new ApiContext(
        new OAuthTokenCredential(
            'ClientID',     // ClientID
            'ClientSecret'      // ClientSecret
        )
    );
    
    
    $addr = new Address();
    $addr->setLine1("xxxxxxxxx")
        ->setLine2("xxxxxxxxx")
        ->setCity("xxxxxxxxx")
        ->setState("xx")
        ->setPostalCode("xxxxx")
        ->setCountryCode("xx")
        ->setPhone("xxx-xxx-xxxx");

    $card = new CreditCard();
    $card->setType("visa")
        ->setNumber("xxxxxxxxxx")
        ->setExpireMonth("xx")
        ->setExpireYear("xxxx")
        ->setCvv2("xxx")
        ->setFirstName("xxxxx")
        ->setLastName("xxxxx")
        ->setBillingAddress($addr);
    
    $card->create($apiContext);
    $mycard=json_decode($card, true);
    $cardID  = $mycard['id'];
	
    $creditCardToken = new CreditCardToken();
    $creditCardToken->setCreditCardId($cardID);
    
    
    $fundingInstrument = new FundingInstrument();
    $fundingInstrument->setCreditCardToken($creditCardToken);
    
    /*=======*/
    $payer = new Payer();
    $payer->setPaymentMethod("credit_card")
            ->setFundingInstruments(array($fundingInstrument));
   
    $amount = new Amount();
    $amount->setCurrency('USD')
    ->setTotal(1);
    
    $transaction = new Transaction();
    $transaction->setAmount($amount)->setDescription("Payment description.");;
    
    $payment = new Payment();
    $payment->setIntent('authorize')
            ->setPayer($payer)
            ->setTransactions(array($transaction));
    
    
    
   
    try {
        $payment->create($apiContext);
        echo $payment;
        echo "\n\nRedirect user to approval_url: " . $payment->getApprovalLink() . "\n";
    }
    catch (\PayPal\Exception\PayPalConnectionException $ex) {
        // This will print the detailed information on the exception.
        //REALLY HELPFUL FOR DEBUGGING
        echo 'issues<br/>';
        echo $ex->getData();
    }
    die();
}

authorization();`

**Comment by xiaoleih41** [comment]
If the card number has been used before in Sandbox, it may trigger this 500 error. However, payment by direct credit card has been deprecated. No more new application will be approved. Please consider to integrate Braintree SDK instead. For detail, please refer to README. MD.
