### ISSUE TITLE
Turn off request and response logging

### ISSUE THREAD

**Issue by stefansedich** [paypal/PayPal-Ruby-SDK#356]
How does one turn off the INFO level request/response logging? I could use a null logger but it would still be nice to get errors, is it intended that these are not able to be disabled easily?

**Comment by hlcfan** [comment]
Are you able to set the logger level? Like
```
PayPal::SDK.logger.level = Logger::WARN
```
or
```
PayPal::SDK.logger.level = Logger::ERROR
```
