### ISSUE TITLE
Express Checkout redirects to paypal site, without executing payment endpoint on iOS

### ISSUE THREAD

**Issue by choonggg** [paypal/PayPal-Ruby-SDK#362]
* SDK/Library version: 1.6.0
* Environment: Production
* `PayPal-Debug-ID` values: none
* Language, language version, and OS: Ruby backend, iOS safari

### Issue description
 
Not sure if this is the place to discuss Express Checkout but I don't see anywhere else I can post this. Support site doesn't work.

Issue is happening on iOS safari Express Checkout without logging in using credit card. The execute payment endpoint does not get executed and it redirects to Paypal's homepage.

Site is https://bluethumb.com.au

Steps to recreate
- make sure you're logged out of Paypal in the browser (mobile)
- in the pop-up, choose to pay directly with a card
- entering all the details and confirming it takes you to paypal and not back to the cart
- the order doesn't go through

Do let me know what you need so we could move forward faster.

**Comment by choonggg** [comment]
This is in the community forum, looks like the same issue on our end posted last year.
https://www.paypal-community.com/t5/About-Payments/BUG-in-express-checkout-new/m-p/1254807

**Comment by prakash-gangadharan** [comment]
Hi @choonggg, if this not an integration issue with PayPal-Ruby-SDK, refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
