### ISSUE TITLE
Add error message locale translation 

### ISSUE THREAD

**Issue by ngetahun** [paypal/PayPal-Ruby-SDK#369]
### General information

* SDK/Library version: paypal-sdk-rest (1.7.2)
* Environment: doesn't apply
* `PayPal-Debug-ID` values: doesn't apply
* Language, language version, and OS: 

### Issue description

This is more of a feature request. The sdk lacks locale translation files and support for I18n for the error messages thrown. It would be great to have this available.

**Comment by sucithrashanu** [comment]
@ngetahun 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.


Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
