### ISSUE TITLE
Is it possible to use checkout.js, then charge a card after the fact?

### ISSUE THREAD

**Issue by zachfeldman** [paypal/PayPal-Ruby-SDK#372]
Is it possible to have a customer checkout using checkout.js, then sometime after this charge their card using the Ruby API/this library? For instance, if a guest stayed in a hotel, then needed to be charged for incidentals.

I know this is possible with Stripe, but I've had a really hard time divining if it's possible with Paypal from the millions of questions and answers and thousands of pages of documentation that exist for this thing. Sorry if this is the wrong place to ask this question, if so just let me know if there's a better forum.

**Comment by Trupti21** [comment]
@zachfeldman ,
Can you be more precise  about your question?
Actually there are two checkouts available in paypal SDK's [check this](https://developer.paypal.com/docs/checkout/?mark=payment)
1. If customer is having paypal account.
2. Guest checkout.
And If you have ".js" extension file So you can use [Node SDK](https://github.com/paypal/PayPal-Node-SDK).

Thanks

**Comment by Trupti21** [comment]
Close this ticket due to inactivity. Please resubmit if you have additional questions.
