### ISSUE TITLE
Can not create payment in env=test

### ISSUE THREAD

**Issue by trungle1612** [paypal/PayPal-Ruby-SDK#374]
### General information
* SDK/Library version: v2
* Environment: Sandbox
* `PayPal-Debug-ID` values: nothing
* Language, language version, and OS: Ruby 2.4, Ubuntu: 16.04

### Issue description

I want to create payment in env=test, but i can't create a payment
Error message:
```
NoMethodError: undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
Did you mean?  <
from /home/hp/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:219:in `writing'
```

**Comment by sucithrashanu** [comment]
@trungle1612 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.


Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
