### ISSUE TITLE
where do I get client_id and client_secret?

### ISSUE THREAD

**Issue by yegor256** [paypal/PayPal-Ruby-SDK#376]
Would be great if you can explain in the README where should I get `client_id` and `client_secret`. I can't find the right place in PayPal [online documentation](https://developer.paypal.com/docs/api/overview/).

**Comment by rwojnarowski** [comment]
https://developer.paypal.com -> Dashboard -> Create App

**Comment by prakash-gangadharan** [comment]
Hi @yegor256, below is the link which has steps to generate REST API credentials for the sandbox and live environments.
https://developer.paypal.com/docs/api/overview/#get-credentials
