### ISSUE TITLE
billing/subscriptions

### ISSUE THREAD

**Issue by varyonic** [paypal/PayPal-Ruby-SDK#378]
It appears this SDK is still using the `/v1/billing-plans` endpoint deprecated (April 2019?) in favor of `/v1/billing/subscriptions`. Is that correct? Any plans to add support? Would a PR be considered?

**Comment by varyonic** [comment]
My SDK extension to support subscriptions is now available from my profile and RubyGems. Please star if you find it useful or interesting.

**Comment by Trupti21** [comment]
@varyonic ,
If you have any query please reopen the issue.

Thanks

**Comment by prakash-gangadharan** [comment]
Hi @varyonic, current REST sdks still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.

**Comment by prakash-gangadharan** [comment]
Hi @varyonic
* If you find solution to an [issue/improvements](https://github.com/paypal/PayPal-Ruby-SDK/issues) in sdk that would be helpful to everyone, feel free to send us a pull request.
* The ideal approach to create a fix would be to fork the repository, create a branch in your repository, and make a pull request out of it.
* It is desirable if there is enough comments/documentation and Tests included in the pull request.
* For general idea of contribution, please follow the guidelines mentioned [here](https://guides.github.com/activities/contributing-to-open-source/).
