### ISSUE TITLE
SDK out of sync with Documentation 

### ISSUE THREAD

**Issue by ahbou** [paypal/PayPal-Ruby-SDK#381]
This SDK and the beta 2.0 are both out of sync with the subscription docs at: https://developer.paypal.com/docs/api/subscriptions/v1/

It still uses basic auth instead of the access token.
Also creating a plan isn't compatible with the smart banner.

### General information

* SDK/Library version: 1.7.2
* Environment: Both
* Language, language version, and OS: Ruby

**Comment by sucithrashanu** [comment]
@ahbou 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.


Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
