### ISSUE TITLE
Agreement issues on new gem release(0.8.1)

### ISSUE THREAD

**Issue by yoonwaiyan** [paypal/PayPal-Ruby-SDK#68]
1.
I want to search for transactions for an agreement. After getting the bill information(`bill = Paypal::Agreement.find("<agreement_id>")`), I called the transactions method like this:
```ruby
      transactions = Paypal::Agreement.transactions({
        :"agreement-id" => "<agreement_id>",
        start_date: "2014-10-01",
        end_date: "2014-12-13"
        })
```

but it returns an error:
```ruby
URI::InvalidComponentError: bad component(expected absolute path component): /v1/payments/billing-agreements/{agreement-id}/transactions
	from /Users/mac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/generic.rb:824:in `check_path'
	from /Users/mac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/generic.rb:871:in `path='
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/rest.rb:123:in `format_request'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/base.rb:83:in `api_call'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/rest.rb:95:in `api_call'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/base.rb:102:in `get'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-rest-0.8.1/lib/paypal-sdk/rest/data_types.rb:1507:in `transactions'
	from (irb):48
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/mac/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

2.
I want to charge users by setting outstanding balance manually by using the set_balance method in the newest gem release. I searched for an agreement(`bill = Paypal::Agreement.find("<agreement_id>")`) and I tested the set_balance function and it returns a 400 error with this error message:
```ruby
#<PayPal::SDK::REST::DataTypes::Agreement:0x007fedfccc83e0 @error={"name"=>"CANT_INCREASE_OUTSTANDING_AMOUNT", "message"=>"Cannot increase delinquent amount", "information_link"=>"https://developer.paypal.com/webapps/developer/docs/api/#CANT_INCREASE_OUTSTANDING_AMOUNT", "debug_id"=>"a9d26337777af"}`
```
so I accessed the documentation and this is the reason: "Bill outstanding amount cannot be increased.". May I know what's the reason(or possibilities) behind this limitation? That agreement is a subscription to a plan which does not bill users automatically. 

By the way, I hope that the documentation for Ruby section can be improved as there are some missing examples for Ruby section in the documentation which I have to refer to the docset for the method calls available. The hyperlink provided in the error above is not really working as I have to search the error name manually.

**Comment by juwlee** [comment]
@yoonwaiyan fixes and code samples have been released. Can you try it?

**Comment by yoonwaiyan** [comment]
@juwlee yup, transactions and agreement issues are solved, thanks. There's another issue on the new release though, I'll open another issue ticket.
