### ISSUE TITLE
Error in billing plan update

### ISSUE THREAD

**Issue by PaulDaviesC** [paypal/PayPal-Ruby-SDK#74]
When I try to use the update method in class Plane it is giving me error as below :

NameError: uninitialized constant PayPal::SDK::REST::DataTypes::Plan::PatchRequest
from /home/pauldc/.rvm/gems/ruby-2.1.2/gems/paypal-sdk-rest-0.9.1/lib/paypal-sdk/rest/data_types.rb:1277:in `update'

I believe this is a bug. If not a bug, then what I am doing wrong?

**Comment by juwlee** [comment]
@PaulDaviesC thanks for reporting. This is the same kind of issue as #68 and will be fixed in the next release.
