### ISSUE TITLE
500 Internal Error with rest SDK payment creation

### ISSUE THREAD

**Issue by cannapages** [paypal/PayPal-Ruby-SDK#79]
Hello I am trying to solve a cryptic error when I submit a payment in my sandbox environment.

Here is a gist of our implementation code
https://gist.github.com/cannapages/d06a3470cf7bba5ab7b4

The error I am about to describe happens at line 33 of the above mentioned implementation code

When I try to create a payment with incorrect credentials such as an expired card your server serves back a 200 response containing the correct error messages

If however I submit a test card number correctly such as 4111111111111111 and a correct expiration date your server lags and finally gives a 500 response. 

PayPal::SDK::Core::Exceptions::ServerError at /checkout/transactions
Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = 77075b9a9d83b.

Here is an inspect on the @payment object at the point of failure
https://gist.github.com/cannapages/6639300f922cd5ea1b1b

**Comment by ppmtscory** [comment]
@cannapages This has to do with the card number (41111...) you are using.  This test number is so overused within our sandbox environment that you'll get the Internal Server Error 98% of the time.  We clear it out of our system every so often, but it doesn't take long to get overused and fail again.  To remedy this, you can either use a card number from one of your sandbox accounts or you can use a [card number generator](https://ppmts.custhelp.com/app/answers/detail/a_id/750/kw/sandbox%20credit%20card). The card would need to pass a standard luhn check to be a valid card number.
