### ISSUE TITLE
Refresh Tokens in Future Payments

### ISSUE THREAD

**Issue by geomobile-haptimap** [paypal/PayPal-Ruby-SDK#80]
Hi all,

according to the documentation for Future Payments the server immediately has to exchange short-lived Authorization Code for long-lived Refresh / Access Tokens.

But the code from Future Payment example

access_token  = FuturePayment.exch_token(auth_code)

only returns access token and NOT the additional information such as refresh token, expires_in, etc.

Did I miss something?

Thanks in advance for any help!

Bastian

**Comment by juwlee** [comment]
@geomobile-haptimap thanks for pointing it out. We are working on a fix which will be released soon.

**Comment by jziaja** [comment]
This should be fixed in the latest release, as `exch_token` now returns a `tokeninfo` object that contains both the access & refresh token along with the expiration time and other information.  Please reopen this issue if you still encounter a problem  Thanks!
