### ISSUE TITLE
401 Error while payment execute in sandbox mode

### ISSUE THREAD

**Issue by pencilcheck** [paypal/PayPal-Ruby-SDK#81]
Never changed anything, the rspec tests were passing a few months ago now they aren't.

```
PayPal::SDK::Core::Exceptions::UnauthorizedAccess:
       Failed.  Response code = 401.  Response message = Unauthorized.
```

Using latest PayPal-Ruby-SDK (0.10.0)
```
    paypal-sdk-core (0.3.1)
      multi_json (~> 1.0)
      xml-simple
    paypal-sdk-rest (0.10.0)
      paypal-sdk-core (~> 0.3.1)
```

**Comment by juwlee** [comment]
@pencilcheck can you tell me which rspec test used to pass but is now failing? (I do not see a failure from rspec payment test suite on my local environment.) Does your request work with sample credentials? Also, have you tried curl?

**Comment by pencilcheck** [comment]
Sorry, it's not paypal's rspec, but in our project we uses factory_girls to create users with credit cards and the offending lines:
```
      paypal_card = PayPal::SDK::REST::CreditCard.new attributes.except(:user)
      paypal_card.create
```
Is the second line here when I call create. The fake attributes are taking from the paypal's create credit card sample:
```
    type "visa"
    number "4417119669820331"
    expire_month "11"
    expire_year "2018"
    cvv2 "874"
    first_name "Joe"
    last_name "Shopper"
```

**Comment by juwlee** [comment]
@pencilcheck can you clarify so I can understand the issue correctly? Did you get the unauthorized error from CreditCard.create(), not from payment.execute() as described in the subject? Also, have you got a chance to try the sample credentials and curl?

**Comment by pencilcheck** [comment]
Unless the sample credentials have changed, the error comes from the .create() method. I'm on the latest version, so is it really necessary to test it on curl?

**Comment by juwlee** [comment]
@pencilcheck I tested credit card creation but did not see 401. If you are using the sample credentials, please create and try your own. If your own credentials throw 401, that probably means an account issue and PayPal MTS should be able to handle the issuer better.

**Comment by pencilcheck** [comment]
@juwlee ok, then the most likely issue might be the latter. I'm using my credential when I was running rspec. How do I contact PayPal MTS to my account looked at?

**Comment by juwlee** [comment]
@pencilcheck here is a link to [PayPal Merchant Technical Services](https://ppmts.custhelp.com/).

**Comment by pencilcheck** [comment]
@juwlee just upgraded to the latest version (was at 0.10.0)

This is the log when I call `paypal_card.create`

```
I, [2015-01-30T17:26:25.278724 #62292]  INFO -- : PayPal-Request-Id: e8eb0284-d783-429c-bc84-a40d1081b400
I, [2015-01-30T17:26:25.278752 #62292]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/vault/credit-card
I, [2015-01-30T17:26:25.281391 #62292]  INFO -- : Response[401]: Unauthorized, Duration: 0.003s
I, [2015-01-30T17:26:25.273410 #62292]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/oauth2/token
I, [2015-01-30T17:26:25.278591 #62292]  INFO -- : Response[200]: OK, Duration: 0.005s
I, [2015-01-30T17:26:25.278724 #62292]  INFO -- : PayPal-Request-Id: e8eb0284-d783-429c-bc84-a40d1081b400
I, [2015-01-30T17:26:25.278752 #62292]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/vault/credit-card
I, [2015-01-30T17:26:25.281391 #62292]  INFO -- : Response[401]: Unauthorized, Duration: 0.003s
PayPal::SDK::Core::Exceptions::UnauthorizedAccess: Failed.  Response code = 401.  Response message = Unauthorized.
from /Users/penn/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/paypal-sdk-rest-1.0.0/lib/paypal-sdk/core/util/http_helper.rb:135:in `handle_response'
```

Can you tell me how to report to MTS for this specific problem? Because seems like the server doesn't tell much about what's going on in the background and seems like requesting for a access token (the line where it requests https://api.sandbox.paypal.com/v1/oauth2/token) seems to be working, so it could be a server + account combination problem.

**Comment by boufalghala** [comment]
i need help future payment work in sandbox when i try live mode this is error

<img width="942" alt="capture d ecran 2017-11-20 a 14 51 57" src="https://user-images.githubusercontent.com/31658578/33074385-48a16640-cec6-11e7-8fd2-b5e06cf66eb5.png">
"debug_id" = 5ba196222d74f;
    "information_link" = "https://developer.paypal.com/docs/api/payments/#errors";
    message = "Unauthorized payment.";
    name = "UNAUTHORIZED_PAYMENT";

**Comment by xiaoleih41** [comment]
@boufalghala Are you approved for future payment? Was it funded by credit card? You may contact www.paypal-techsupport.com  and provide more detail information. I suspect it's a  permission issue on your live app. I am closing this thread as your issue is different from the original issue on the thread.

**Comment by boufalghala** [comment]
@xiaoleih41 how to enable future payments I want pay with PayPal I am sure is not error from my code

**Comment by xiaoleih41** [comment]
Click the enable next to the future payment feature in your developer account.
