### ISSUE TITLE
How to generate an authorization code using PayPal-Ruby-SDK for future payment?

### ISSUE THREAD

**Issue by sameerf3** [paypal/PayPal-Ruby-SDK#82]
I am trying to generate access token for paypal for future payment using  PayPal-Ruby-SDK [example][1].

    it "Exchange Authorization Code for Refresh / Access Tokens" do
        # put your authorization code for testing here
        auth_code = ''
        if auth_code != ''
          access_token  = FuturePayment.exch_token(auth_code)
          access_token.should_not be_nil
        end
    end

It requires an authorization code which I am unable to find how to generate. Is there any documentation regarding this?

  [1]: https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/payments_examples_spec.rb#L149

**Comment by jaypatel512** [comment]
You need to have Mobile SDK integration to get authorization code for doing future payments. 
It is explained in detailed in [PayPal-IOS-SDK](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md). 

Similar documentation would apply for [PayPal-Android-SDK](https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/future_payments_server.md)

**Comment by juwlee** [comment]
@sameerf3 please see [this doc](https://developer.paypal.com/webapps/developer/docs/integration/mobile/make-future-payment/) on how future payment works.

**Comment by sameerf3** [comment]
Thanks @jaypatel512 @juwlee , Actually I wanted to use future payment from website, but got to know that currently Paypal only support future payment for mobile sdks.
