### ISSUE TITLE
Payee attribute

### ISSUE THREAD

**Issue by lws68825** [paypal/PayPal-Ruby-SDK#83]
Hi, I just read the latest source code of Payment, I find that there is no attribute defined in the Payee class. Why?
      class Payee < Base
        def self.load_members
        end
      end

**Comment by juwlee** [comment]
@lws68825 looks like it was missed in the last code generation. I have added the missing properties in 3d3a21c0b44e513207b0414c5d0722b9d1c15e17 . Thanks for the catch!
