### ISSUE TITLE
Coveralls declared as runtime dependency instead of development

### ISSUE THREAD

**Issue by colszowka** [paypal/PayPal-Ruby-SDK#84]
In the latest release 1.0.0, coveralls has [been added](https://github.com/paypal/PayPal-Ruby-SDK/commit/064d97d2e49e89433ef84fcf8b9b25af74842544) as a runtime dependency and hence will be installed on production environments for all users of the sdk, even though it's a development tool. The declaration should be changed to `add_development_dependency`.

**Comment by juwlee** [comment]
@colszowka thanks for pointing it out. It has been fixed in 360facf554b9397b8134030f0395b0a98f4d32f2 . Also, lease feel free to submit a pull request for this type of patch/suggestion.
