### ISSUE TITLE
FuturePayment class not available in version 1.0

### ISSUE THREAD

**Issue by colszowka** [paypal/PayPal-Ruby-SDK#85]
The class `PayPal::SDK::REST::DataTypes::FuturePayment` is not available when using the v1.0 gem because it is hidden in the file `extended_data_types.rb` which is defined as an autoload ExtendedDataTypes in https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest.rb

One has to do `require 'paypal-sdk/rest/extended_data_types'` to get it loaded. 

Referencing `PayPal::SDK::REST::ExtendedDataTypes` actually also does not trigger the autoload, instead giving a `NameError: uninitialized constant PayPal::SDK::REST::ExtendedDataTypes` because `extended_data_types.rb` actually does not define a constant `PayPal::SDK::REST::ExtendedDataTypes`

Putting it all together, when I try to exchange the token for a FuturePayment, I get an error:

```
> PayPal::SDK::REST::DataTypes::FuturePayment.exch_token t
NameError: uninitialized constant VERSION
```

..which is where I gave up. I am not sure this is worthy of a 1.0.0 label to be honest.

**Comment by juwlee** [comment]
@colszowka thanks for bringing it to our attention. It seems the future payment class is better placed in data_types.rb along with other data models. I will move it back there along with some other fixes.

**Comment by jziaja** [comment]
This fix should be available in the current release. Please reopen if you still encounter a problem. Thanks!
