### ISSUE TITLE
paypal.crt not included in gem

### ISSUE THREAD

**Issue by johnkolen** [paypal/PayPal-Ruby-SDK#86]
data/paypal.crt isn't tagged for inclusion in gemspec. Given that Core::Util:HTTPHelper#default_ca_file hard codes this file, it's a good idea to add it to the gemspec.

**Comment by juwlee** [comment]
@johnkolen thanks for the suggestion. Would you send it in the form of pull request?

**Comment by jhilden** [comment]
@juwlee I can't believe this is tagged as an "enhancement" :(   As far as I see it this is a ciritical bug, see #90
I wonder why there haven't been more users reporting issues yet.

thanks for the fix @johnkolen

**Comment by juwlee** [comment]
@jhilden @johnkolen I have reviewed and merged the PR. The updated gem has been released.
