### ISSUE TITLE
401 with credentials of classic API (username/password/signature)

### ISSUE THREAD

**Issue by jgauby** [paypal/PayPal-Ruby-SDK#87]
The gem merchant-sdk-ruby will be deprecated in the future (https://github.com/paypal/merchant-sdk-ruby). I need to use credentials for Classic APIs, with username/password/signature. Nothing in the documentation. But, this feature seems to be possible, some hints in the code : 
* https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/authentication.rb#L29
* https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/generators/paypal/sdk/templates/paypal.yml#L10

With this code, I obtain "Failed.  Response code = 401.  Response message = Unauthorized.".

    PayPal::SDK.configure(
      mode: "sandbox",
      username: "my username",
      password: "my password",
      signature: "my signature"
    )
    @payment = PayPal::SDK::REST::Payment.new(
      intent: "sale",
      payer: {
        payment_method: "paypal"
      },
      redirect_urls: {
        return_url: " ... ",
        cancel_url: " ... "
      },
      transactions: [ informations of my transaction ]
    )
    @payment.create

What is wrong ?

**Comment by juwlee** [comment]
@jgauby this SDK works with REST APIs but not with Classic. I have removed the unnecessary code in 31eaf8cbc7e597e8000105f4c5a69c2fd523402b . Thanks for pointing it out.
