### ISSUE TITLE
Travis runs only two examples

### ISSUE THREAD

**Issue by jgonera** [paypal/PayPal-Ruby-SDK#95]
https://travis-ci.org/paypal/PayPal-Ruby-SDK/jobs/50389401

Why are we running only specs that have a `unit` tag?

**Comment by juwlee** [comment]
Hi @jgonera , we want to separate ```integration``` tests from ```unit``` tests to ensure builds do not fail on API system instability. There is [rspec execution guide](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/spec/README.md) if you want to try it yourself. Please make sure to put credentials with the right scopes enabled in config.

**Comment by jgonera** [comment]
@juwlee I understand that you don't want to run some of the integration tests in Travis, but 2 specs doesn't seem like the right number to run in CI. For example, when I run tests locally with `bundle exec rspec` tests for `PayPal::SDK::Core::Config` run and they don't seem to be integration tests.

In other words, are you sure that these:

```
Payments
  Validate user-agent
  Examples
    REST
      Modifiy global configuration
```

are the only tests that should run in Travis? I can't believe that out of 72 examples only 2 are unit tests.

Specs for `PayPal::SDK::Core::Config` are tagged neither `unit` nor `integration`. It seems like they're unit tests to me. I think only specs tagged as `integration` should be ignored in Travis.
