### ISSUE TITLE
Constantly getting INTERNAL_SERVICE_ERROR on payment.create

### ISSUE THREAD

**Issue by joelbarker2011** [paypal/PayPal-Ruby-SDK#96]
Over the last couple of days or so, I have repeatedly been getting INTERNAL_SERVICE_ERROR responses from the PayPal Rest API when making calls to https://api.sandbox.paypal.com/v1/payments/payment. The latest response:

    {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"7226daa964257"}

Other debug_ids I've gotten today are: 20e56c11855aa, 3d96d3004f1d5, 7899ecf324cbb.

For debugging purposes, I've switched to using `curl` in a simple bash script:

```
#!/bin/bash

CLIENT_ID='(my PayPal client id)'
SECRET='(my PayPal client secret)'

time curl https://api.sandbox.paypal.com/v1/oauth2/token \
 -H "Accept: application/json" \
 -H "Accept-Language: en_US" \
 -u "$CLIENT_ID:$SECRET" \
 -d "grant_type=client_credentials"

echo
echo "Enter access token: "
read ACCESS_TOKEN
# here I copy and paste the access token from the previous curl call
echo "Access token: >$ACCESS_TOKEN<"
echo

time curl -v https://api.sandbox.paypal.com/v1/payments/payment \
-H "Content-Type:application/json" \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-d '{
  "intent":"sale",
  "payer":{
    "payment_method":"credit_card",
    "funding_instruments":[
      {
        "credit_card":{
          "number":"4417119669820331",
          "type":"visa",
          "expire_month":11,
          "expire_year":2018,
          "cvv2":"874",
          "first_name":"Betsy",
          "last_name":"Buyer",
          "billing_address":{
            "line1":"111 First Street",
            "city":"Saratoga",
            "state":"CA",
            "postal_code":"95070",
            "country_code":"US"
          }
        }
      }
    ]
  },
  "transactions":[
    {
      "amount":{
        "total":"7.47",
        "currency":"USD",
        "details":{
          "subtotal":"7.41",
          "tax":"0.03",
          "shipping":"0.03"
        }
      },
      "description":"This is the payment transaction description."
    }
  ]
}'
```

The details of the curl calls were taken straight from the [examples in PayPal's REST API Reference] (https://developer.paypal.com/docs/api/). Calls through the PayPal-Ruby-SDK have been almost identical (I've varied some of the credit card and payee details), and result in the same error.

I've made the calls from multiple physical locations (and therefore multiple different IP addresses) and at different times of day). I have not tried on the live server.

Looking around, I'm seeing an awful lot of bug reports (in GitHub and StackOverflow) about basically the same issue. Sometimes it comes down to [server downtime issues] (https://www.paypal-notify.com/eventnotification/search?eventSearchType=PayPalSiteStatus); that doesn't appear to be the problem here. [Some of the issues] (https://github.com/paypal/PayPal-Ruby-SDK/issues/34) I've seen [don't seem to have any real solution] (https://github.com/paypal/PayPal-PHP-SDK/issues/112); presumably they clear up just as unexpectedly as they began. [Others] (http://stackoverflow.com/questions/24127038/http-timeout-with-paypal-rest-api-for-all-credit-types-but-visa) [don't even have an attempt at a solution] (http://stackoverflow.com/questions/28461264/sandbox-rest-api-getting-internal-service-error).

Do these issues point to a deeper problem with the PayPal Rest API? Is the API not really ready for prime time? Should I be using Braintree or Stripe instead?

Thanks.

**Comment by jziaja** [comment]
Have you tried changing the credit card number you're testing with?

**Comment by juwlee** [comment]
@joelbarker2011 as @jziaja suggested, please try a different card number. [credit card number generator](https://ppmts.custhelp.com/app/answers/detail/a_id/750) may come handy.

**Comment by joelbarker2011** [comment]
Besides the number above, I've been using 4111111111111111 (visa), 5555555555554444 (mastercard), and 4417119669820331 (visa). The CVV2 code has varied from "123" to "874" to random 3-digit codes. The expiration month and year have usually been random months in 2018, but I've used others too.

Thanks for the number generator; using a new (visa) number just worked. Does the Rest API have a known problem with using the same numbers multiple times? If so, is this documented anywhere? If not, are there other undocumented limitations like this that I and other developers should be aware of?

Thanks.
