### ISSUE TITLE
How to get shipping address?

### ISSUE THREAD

**Issue by simo2409** [paypal/PayPal-Ruby-SDK#98]
I'm using payment_details(:payKey => @response.payKey) method to retrieve payment details but there is not the payer's shipping address. Looking at documentation I couldn't find a way to get it via accountId or any other data.

Am I missing anything?

Thank you

**Comment by juwlee** [comment]
@simo2409 please see #17 for reference. Specifically, "according to https://developer.paypal.com/webapps/developer/docs/api/#execute-an-approved-paypal-payment, when you execute a paypal payment that has been approved by the payer, the payer_info object in the response has a shipping_address object which is the shipping address for the payer paypal account."

**Comment by simo2409** [comment]
Thank you juwlee
